PyBooster: chemistry.c File Reference
chemistry.c File Reference
Chemistry-related Functions.
#include "chemistry.h"
Functions
int iselement (const char *__restrict__ name)
double pka (const double ka)
double pkb (const double kb)
static size_t strlenx (const char *__restrict__ str)
Variables
const char elementlist [128][16]
Detailed Description
Chemistry-related Functions.
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.18
DESCRIPTION
Chemistry-specific functions that perform calculations or truth-tests
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file chemistry.c.
Function Documentation
int iselement (const char *__restrict__ name)
Check if the given string is a name of a chemical element
Parameters
[in] name String to test
Return values
0 False: This is not a name of a chemical element
1 True: This is a name of a chemical element
Definition at line 220 of file chemistry.c.
References elementlist, and strlenx().
Referenced by chemistry_iselement().
double pka (const double ka)
Calculate the pKa from Ka (Acid Dissociation Constant)
Chemistry Explanation
[HA] = [H+] + [A-]; Molar concentrations
Ka = ([H+][A-]) / [HA]
Ka = ([X][0.01M+X]) / (0.02M-X); Ka = 10^-5M
X = 0.00001 * (0.02 / 0.01) = 2*(10^-5) = [H+]
pH = -log(2*(10^-5)) = 4.7
Parameters
[in] ka Acid Dissociation Constant
Returns
pka value
Definition at line 197 of file chemistry.c.
double pkb (const double kb)
Calculate the pKb from Kb (Base Dissociation Constant)
Parameters
[in] kb Base Dissociation Constant
Returns
pkb value
Definition at line 208 of file chemistry.c.
Referenced by chemistry_pkb().
static size_t strlenx (const char *__restrict__ str) static
Private Function: Returns the length of a string
Definition at line 174 of file chemistry.c.
Referenced by iselement(), tools_isstralnum(), tools_isstralpha(), tools_isstrgraphical(), tools_isstrhex(), tools_isstrlowercase(), tools_isstrnum(), tools_isstrprintable(), tools_isstrpunctuation(), tools_isstruppercase(), tools_isstrwhitespace(), tools_strreplace(), and tools_uppercasestr().
Variable Documentation
const char elementlist[128][16]
Initial value:
= {
    "hydrogen",
    "helium",
    "lithium",
    "beryllium",
    "boron",
    "carbon",
    "nitrogen",
    "oxygen",
    "fluorine",
    "neon",
    "sodium",
    "magnesium",
    "aluminium",
    "silicon",
    "phosphorus",
    "sulfur",
    "chlorine",
    "argon",
    "potassium",
    "calcium",
    "scandium",
    "titanium",
    "vanadium",
    "chromium",
    "manganese",
    "iron",
    "cobalt",
    "nickel",
    "copper",
    "zinc",
    "gallium",
    "germanium",
    "arsenic",
    "selenium",
    "bromine",
    "krypton",
    "rubidium",
    "strontium",
    "yttrium",
    "zirconium",
    "niobium",
    "molybdenum",
    "technetium",
    "ruthenium",
    "rhodium",
    "palladium",
    "silver",
    "cadmium",
    "indium",
    "tin",
    "antimony",
    "tellurium",
    "iodine",
    "xenon",
    "cesium",
    "barium",
    "lanthanum",
    "cerium",
    "praseodymium",
    "neodymium",
    "promethium",
    "samarium",
    "europium",
    "gadolinium",
    "terbium",
    "dysprosium",
    "holmium",
    "erbium",
    "thulium",
    "ytterbium",
    "lutetium",
    "hafnium",
    "tantalum",
    "tungsten",
    "rhenium",
    "osmium",
    "iridium",
    "platinum",
    "gold",
    "mercury",
    "thallium",
    "lead",
    "bismuth",
    "polonium",
    "astatine",
    "radon",
    "francium",
    "radium",
    "actinium",
    "thorium",
    "protactinium",
    "uranium",
    "neptunium",
    "plutonium",
    "americium",
    "curium",
    "berkelium",
    "californium",
    "einsteinium",
    "fermium",
    "mendelevium",
    "nobelium",
    "lawrencium",
    "rutherfordium",
    "dubnium",
    "seaborgium",
    "bohrium",
    "hassium",
    "meitnerium",
    "darmstadtium",
    "roentgenium",
    "copernicium",
    "ununtrium",
    "flerovium",
    "ununpentium",
    "livermorium",
    "ununseptium",
    "ununoctium",
    "ununennium",
    "unbinilium",
    "unbiunium",
}
Array containing the names of the Periodic Table of Elements
Definition at line 40 of file chemistry.c.
Referenced by iselement().