PyBooster: chemistry.h File Reference
chemistry.h File Reference
Chemistry-related Functions (header)
#include "MACROS.h"
#include <math.h>
#include "chemistry_types.h"
Functions
int iselement (const char *__restrict__ name)
double pka (const double ka)
double pkb (const double kb)
Variables
const char elementlist [128][16]
Detailed Description
Chemistry-related Functions (header)
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.18
DESCRIPTION
Chemistry-specific functions that perform calculations or truth-tests
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file chemistry.h.
Function Documentation
int iselement (const char *__restrict__ name)
Check if the given string is a name of a chemical element
Parameters
[in] name String to test
Return values
0 False: This is not a name of a chemical element
1 True: This is a name of a chemical element
Definition at line 220 of file chemistry.c.
References elementlist, and strlenx().
Referenced by chemistry_iselement().
double pka (const double ka)
Calculate the pKa from Ka (Acid Dissociation Constant)
Chemistry Explanation
[HA] = [H+] + [A-]; Molar concentrations
Ka = ([H+][A-]) / [HA]
Ka = ([X][0.01M+X]) / (0.02M-X); Ka = 10^-5M
X = 0.00001 * (0.02 / 0.01) = 2*(10^-5) = [H+]
pH = -log(2*(10^-5)) = 4.7
Parameters
[in] ka Acid Dissociation Constant
Returns
pka value
Definition at line 197 of file chemistry.c.
double pkb (const double kb)
Calculate the pKb from Kb (Base Dissociation Constant)
Parameters
[in] kb Base Dissociation Constant
Returns
pkb value
Definition at line 208 of file chemistry.c.
Referenced by chemistry_pkb().
Variable Documentation
const char elementlist[128][16]
Array containing the names of the Periodic Table of Elements
Definition at line 40 of file chemistry.c.
Referenced by iselement().