PyBooster: fuzzy_logic.h File Reference
fuzzy_logic.h File Reference
Fuzzy Logic (header)
#include "MACROS.h"
Macros
#define FAND(x, y) (fuzzymin(2, (x), (y)))
#define FNAND(x, y) (100 - fuzzymin(2, (x), (y)))
#define FNEG(x) (100 - (x))
#define FNOR(x, y) (100 - fuzzymax(2, (x), (y)))
#define FNOT(x) (100 - (x))
#define FNXOR(x, y) (fuzzymin(2, fuzzymin(2, (x), (y)), (100 - (fuzzymax(2, (x), (y))))))
#define FOR(x, y) (fuzzymax(2, (x), (y)))
#define FXNOR(x, y) (fuzzymin(2, fuzzymin(2, (x), (y)), (100 - (fuzzymax(2, (x), (y))))))
#define FXOR(x, y) (fuzzymin(2, (100 - fuzzymin(2, (x), (y))), fuzzymax(2, (x), (y))))
Typedefs
typedef signed int fuzzy
Functions
fuzzy bool2fuzzy (const bool logic)
bool fuzzy2bool (const fuzzy logic)
int fuzzymax (const int count,...)
int fuzzymin (const int count,...)
int mno (const int count,...)
Variables
const fuzzy absolutely
const fuzzy certain
const fuzzy definite
const fuzzy false_f
const fuzzy impossible
const fuzzy indeterminate
const fuzzy likely
const fuzzy possible
const fuzzy true_f
const fuzzy uncertain
const fuzzy undefined
const fuzzy unknown
const fuzzy unlikely
Detailed Description
Fuzzy Logic (header)
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.18
DESCRIPTION
Light-weight Fuzzy-Logic library and conversions between fuzzy and boolean datatypes
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file fuzzy_logic.h.
Macro Definition Documentation
#define FAND (x, y) (fuzzymin(2, (x), (y)))
Definition at line 41 of file fuzzy_logic.h.
#define FNAND (x, y) (100 - fuzzymin(2, (x), (y)))
Definition at line 45 of file fuzzy_logic.h.
#define FNEG (x) (100 - (x))
Definition at line 43 of file fuzzy_logic.h.
#define FNOR (x, y) (100 - fuzzymax(2, (x), (y)))
Definition at line 46 of file fuzzy_logic.h.
#define FNOT (x) (100 - (x))
Definition at line 44 of file fuzzy_logic.h.
#define FNXOR (x, y) (fuzzymin(2, fuzzymin(2, (x), (y)), (100 - (fuzzymax(2, (x), (y))))))
Definition at line 49 of file fuzzy_logic.h.
#define FOR (x, y) (fuzzymax(2, (x), (y)))
Definition at line 42 of file fuzzy_logic.h.
#define FXNOR (x, y) (fuzzymin(2, fuzzymin(2, (x), (y)), (100 - (fuzzymax(2, (x), (y))))))
Definition at line 48 of file fuzzy_logic.h.
#define FXOR (x, y) (fuzzymin(2, (100 - fuzzymin(2, (x), (y))), fuzzymax(2, (x), (y))))
Definition at line 47 of file fuzzy_logic.h.
Typedef Documentation
typedef signed int fuzzy
Fuzzy-Logic Datatype (signed integer)
Definition at line 52 of file fuzzy_logic.h.
Function Documentation
fuzzy bool2fuzzy (const bool logic)
Convert boolean-logic to fuzzy-logic
Definition at line 71 of file fuzzy_logic.c.
References false_f, and true_f.
bool fuzzy2bool (const fuzzy logic)
Convert fuzzy-logic to boolean-logic
Definition at line 78 of file fuzzy_logic.c.
int fuzzymax (const int count, ...)
Return the largest (maximum) number
Definition at line 84 of file fuzzy_logic.c.
Referenced by mno().
int fuzzymin (const int count, ...)
Return the smallest (minimum) number
Definition at line 99 of file fuzzy_logic.c.
Referenced by mno().
int mno (const int count, ...)
Minimal Negation Operator (just one false) - Return result
Definition at line 114 of file fuzzy_logic.c.
References fuzzymax(), and fuzzymin().
Variable Documentation
const fuzzy absolutely
True
Definition at line 64 of file fuzzy_logic.c.
const fuzzy certain
Probably true
Definition at line 58 of file fuzzy_logic.c.
const fuzzy definite
True
Definition at line 62 of file fuzzy_logic.c.
const fuzzy false_f
False
Definition at line 46 of file fuzzy_logic.c.
Referenced by bool2fuzzy().
const fuzzy impossible
False
Definition at line 48 of file fuzzy_logic.c.
const fuzzy indeterminate
Vague; Has several values; Meaningless
Definition at line 44 of file fuzzy_logic.c.
const fuzzy likely
Higher probability of being true than false
Definition at line 56 of file fuzzy_logic.c.
const fuzzy possible
Could be true or false; either-or
Definition at line 54 of file fuzzy_logic.c.
const fuzzy true_f
True
Definition at line 60 of file fuzzy_logic.c.
Referenced by bool2fuzzy().
const fuzzy uncertain
Probably false
Definition at line 50 of file fuzzy_logic.c.
const fuzzy undefined
Illogical; Has no determined value
Definition at line 42 of file fuzzy_logic.c.
const fuzzy unknown
Unable to process; No known logic
Definition at line 40 of file fuzzy_logic.c.
const fuzzy unlikely
Higher probability of being false than true
Definition at line 52 of file fuzzy_logic.c.