PyBooster: geometry.h File Reference
geometry.h File Reference
Geometry Equations (header)
#include "MACROS.h"
#include <math.h>
#include "MATH_MACROS.h"
#include "math_types.h"
Functions
double areacircle (const double radius)
long double areacirclel (const long double radius)
double areaellipse (const double radius1, const double radius2)
long double areaellipsel (const long double radius1, const long double radius2)
double areaequilateraltriangle (const double base)
long double areaequilateraltrianglel (const long double base)
double areaparallelogram (const double base, const double height)
long double areaparallelograml (const long double base, const long double height)
double arearectangle (const double length, const double width)
long double arearectanglel (const long double length, const long double width)
double arearhombus (const double base)
long double arearhombusl (const long double base)
double areasector (const double radius, const double angle_radians)
long double areasectorl (const long double radius, const long double angle_radians)
double areasquare (const double length)
unsigned long int areasquare_int (const unsigned long int length)
double areasquare_shape (const square shape)
long double areasquare_shapel (const squarel shape)
ullint areasquare_ull (const ullint length)
long double areasquarel (const long double length)
double areatrapezoid (const double base1, const double base2, const double height)
long double areatrapezoidl (const long double base1, const long double base2, const long double height)
double areatriangle (const double base, const double height)
long double areatrianglel (const long double base, const long double height)
double distance (const double x1, const double y1, const double x2, const double y2)
double distance_point (point location1, point location2)
long double distance_pointl (pointl location1, pointl location2)
float distancef (const float x1, const float y1, const float x2, const float y2)
long double distancel (const long double x1, const long double y1, const long double x2, const long double y2)
int is_point_in_rectangle (const point p, const rectangle r)
double lengtharc (const double radius, const double angle_radians)
float lengtharcf (const float radius, const float angle_radians)
long double lengtharcl (const long double radius, const long double angle_radians)
double perimetercircle (const double radius)
long double perimetercirclel (const long double radius)
double perimeterparallelogram (const double base, const double side)
long double perimeterparallelograml (const long double base, const long double side)
double perimeterrectangle (const double length, const double width)
long double perimeterrectanglel (const long double length, const long double width)
double perimeterrhombus (const double base)
long double perimeterrhombusl (const long double base)
double perimetersquare (const double side)
long double perimetersquarel (const long double side)
double perimetertrapezoid (const double side1, const double side2, const double side3, const double side4)
long double perimetertrapezoidl (const long double side1, const long double side2, const long double side3, const long double side4)
double perimetertriangle (const double side1, const double side2, const double side3)
long double perimetertrianglel (const long double side1, const long double side2, const long double side3)
doublepair_t polar2xy (const double hypo, const double angle)
static double squareroot (const double num)
static float squarerootf (const float num)
static long double squarerootl (const long double num)
double surfaceareacone (const double radius, const double height)
float surfaceareaconef (const float radius, const float height)
long double surfaceareaconel (const long double radius, const long double height)
double surfaceareacube (const double length)
float surfaceareacubef (const float length)
long double surfaceareacubel (const long double length)
double surfaceareacylinder (const double radius, const double height)
float surfaceareacylinderf (const float radius, const float height)
long double surfaceareacylinderl (const long double radius, const long double height)
double surfacearearectangularprism (const double length, const double width, const double height)
float surfacearearectangularprismf (const float length, const float width, const float height)
long double surfacearearectangularprisml (const long double length, const long double width, const long double height)
double surfaceareasphere (const double radius)
float surfaceareaspheref (const float radius)
long double surfaceareaspherel (const long double radius)
double surfaceareasquarepyramid (const double side, const double length)
float surfaceareasquarepyramidf (const float side, const float length)
long double surfaceareasquarepyramidl (const long double side, const long double length)
double surfaceareatorus (const double radius1, const double radius2)
float surfaceareatorusf (const float radius1, const float radius2)
long double surfaceareatorusl (const long double radius1, const long double radius2)
double volumecone (const double radius, const double height)
float volumeconef (const float radius, const float height)
long double volumeconel (const long double radius, const long double height)
double volumecylinder (const double radius, const double height)
float volumecylinderf (const float radius, const float height)
long double volumecylinderl (const long double radius, const long double height)
double volumeellipsoid (const double radius1, const double radius2, const double radius3)
float volumeellipsoidf (const float radius1, const float radius2, const float radius3)
long double volumeellipsoidl (const long double radius1, const long double radius2, const long double radius3)
double volumehemisphere (const double radius)
float volumehemispheref (const float radius)
long double volumehemispherel (const long double radius)
double volumeparallelepiped (const double length, const double width, const double height)
float volumeparallelepipedf (const float length, const float width, const float height)
long double volumeparallelepipedl (const long double length, const long double width, const long double height)
double volumeprism (const double length, const double base)
float volumeprismf (const float length, const float base)
long double volumeprisml (const long double length, const long double base)
double volumerectanglarprism (const double length, const double width, const double height)
float volumerectanglarprismf (const float length, const float width, const float height)
long double volumerectanglarprisml (const long double length, const long double width, const long double height)
double volumesphere (const double radius)
float volumespheref (const float radius)
long double volumespherel (const long double radius)
double volumesquarepyramid (const double height, const double base)
float volumesquarepyramidf (const float height, const float base)
long double volumesquarepyramidl (const long double height, const long double base)
double volumetetrahedron (const double height, const double base)
float volumetetrahedronf (const float height, const float base)
long double volumetetrahedronl (const long double height, const long double base)
double volumetorus (const double radius1, const double radius2)
float volumetorusf (const float radius1, const float radius2)
long double volumetorusl (const long double radius1, const long double radius2)
doublepair_t xy2polar (const double x, const double y)
Variables
double(* linelength_point)(point location1, point location2)
long double(* linelength_pointl)(pointl location1, pointl location2)
Detailed Description
Geometry Equations (header)
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.20
DESCRIPTION
Various geometric functions such as volume, area, distance, boolean tests, etc.
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
FUNCTION_NAMING_SCHEME
func() -> double
funcl() -> long double
funcf() -> float
func_int() -> unsigned long int
func_ull() -> unsigned long long int
func_signed() -> signed long long int
func_shape() -> shape (double)
func_shapel() -> shapel (long double)
Definition in file geometry.h.
Function Documentation
double areacircle (const double radius)
Return the area of a circle (double)
Definition at line 212 of file geometry.c.
References PI.
long double areacirclel (const long double radius)
Return the area of a circle (long double)
Definition at line 218 of file geometry.c.
References PIl.
double areaellipse (const double radius1, const double radius2)
Return the area of a ellipse (double)
Definition at line 224 of file geometry.c.
References PI.
long double areaellipsel (const long double radius1, const long double radius2)
Return the area of a ellipse (long double)
Definition at line 230 of file geometry.c.
References PIl.
double areaequilateraltriangle (const double base)
Return the area of a equilateral triangle (double)
Definition at line 236 of file geometry.c.
References SQRT_3_DIV_4.
long double areaequilateraltrianglel (const long double base)
Return the area of a equilateral triangle (long double)
Definition at line 242 of file geometry.c.
References SQRT_3_DIV_4l.
double areaparallelogram (const double base, const double height)
Return the area of a parallelogram (double)
Definition at line 248 of file geometry.c.
long double areaparallelograml (const long double base, const long double height)
Return the area of a parallelogram (double)
Definition at line 254 of file geometry.c.
double arearectangle (const double length, const double width)
Return the area of a rectangle (double)
Definition at line 260 of file geometry.c.
long double arearectanglel (const long double length, const long double width)
Return the area of a rectangle (long double)
Definition at line 266 of file geometry.c.
double arearhombus (const double base)
Return the area of a rhombus (double)
Definition at line 272 of file geometry.c.
long double arearhombusl (const long double base)
Return the area of a rhombus (long double)
Definition at line 278 of file geometry.c.
double areasector (const double radius, const double angle_radians)
Return the area of a circular sector (double)
Definition at line 284 of file geometry.c.
long double areasectorl (const long double radius, const long double angle_radians)
Return the area of a circular sector (long double)
Definition at line 290 of file geometry.c.
double areasquare (const double length)
Return the area of a square (double)
Definition at line 296 of file geometry.c.
unsigned long int areasquare_int (const unsigned long int length)
Return the area of a square (long int)
Definition at line 308 of file geometry.c.
double areasquare_shape (const square shape)
Return the area of a square (square)
Definition at line 320 of file geometry.c.
References square::length.
long double areasquare_shapel (const squarel shape)
Return the area of a square (square)
Definition at line 326 of file geometry.c.
References squarel::length.
ullint areasquare_ull (const ullint length)
Return the area of a square (unsigned long long int)
Definition at line 314 of file geometry.c.
long double areasquarel (const long double length)
Return the area of a square (long double)
Definition at line 302 of file geometry.c.
double areatrapezoid (const double base1, const double base2, const double height)
Return the area of a trapezoid (double)
Definition at line 332 of file geometry.c.
long double areatrapezoidl (const long double base1, const long double base2, const long double height)
Return the area of a trapezoid (long double)
Definition at line 338 of file geometry.c.
double areatriangle (const double base, const double height)
Return the area of a triangle (double)
Definition at line 344 of file geometry.c.
long double areatrianglel (const long double base, const long double height)
Return the area of a triangle (long double)
Definition at line 350 of file geometry.c.
double distance (const double x1, const double y1, const double x2, const double y2)
Return the distance between two points (double)
Definition at line 173 of file geometry.c.
References squareroot().
Referenced by physics_speed().
double distance_point (point location1, point location2)
Return the distance between two points (double)
Definition at line 191 of file geometry.c.
References squareroot(), point::x, and point::y.
long double distance_pointl (pointl location1, pointl location2)
Return the distance between two points (long double)
Definition at line 197 of file geometry.c.
References squarerootl(), pointl::x, and pointl::y.
float distancef (const float x1, const float y1, const float x2, const float y2)
Return the distance between two points (float)
Definition at line 185 of file geometry.c.
References squarerootf().
long double distancel (const long double x1, const long double y1, const long double x2, const long double y2)
Return the distance between two points (long double)
Definition at line 179 of file geometry.c.
References squarerootl().
int is_point_in_rectangle (const point p, const rectangle r)
Test if the point is within the rectangle
Definition at line 143 of file geometry.c.
References rectangle::height, rectangle::width, point::x, and point::y.
double lengtharc (const double radius, const double angle_radians)
Return the length of an arc (double)
Definition at line 359 of file geometry.c.
float lengtharcf (const float radius, const float angle_radians)
Return the length of an arc (float)
Definition at line 371 of file geometry.c.
long double lengtharcl (const long double radius, const long double angle_radians)
Return the length of an arc (long double)
Definition at line 365 of file geometry.c.
double perimetercircle (const double radius)
Return the perimeter of a circle (double)
Definition at line 380 of file geometry.c.
References PI2.
long double perimetercirclel (const long double radius)
Return the perimeter of a circle (long double)
Definition at line 386 of file geometry.c.
References PI2l.
double perimeterparallelogram (const double base, const double side)
Return the perimeter of a parallelogram (double)
Definition at line 392 of file geometry.c.
long double perimeterparallelograml (const long double base, const long double side)
Return the perimeter of a parallelogram (long double)
Definition at line 398 of file geometry.c.
double perimeterrectangle (const double length, const double width)
Return the perimeter of a rectangle (double)
Definition at line 416 of file geometry.c.
long double perimeterrectanglel (const long double length, const long double width)
Return the perimeter of a rectangle (long double)
Definition at line 422 of file geometry.c.
double perimeterrhombus (const double base)
Return the perimeter of a rhombus (double)
Definition at line 404 of file geometry.c.
long double perimeterrhombusl (const long double base)
Return the perimeter of a rhombus (long double)
Definition at line 410 of file geometry.c.
double perimetersquare (const double side)
Return the perimeter of a square (double)
Definition at line 428 of file geometry.c.
long double perimetersquarel (const long double side)
Return the perimeter of a square (long double)
Definition at line 434 of file geometry.c.
double perimetertrapezoid (const double side1, const double side2, const double side3, const double side4)
Return the perimeter of a trapezoid (double)
Definition at line 440 of file geometry.c.
long double perimetertrapezoidl (const long double side1, const long double side2, const long double side3, const long double side4)
Return the perimeter of a trapezoid (long double)
Definition at line 446 of file geometry.c.
double perimetertriangle (const double side1, const double side2, const double side3)
Return the perimeter of a triangle (double)
Definition at line 452 of file geometry.c.
long double perimetertrianglel (const long double side1, const long double side2, const long double side3)
Return the perimeter of a triangle (long double)
Definition at line 458 of file geometry.c.
doublepair_t polar2xy (const double hypo, const double angle)
Return the (x,y)-coordinates for the given polar-coordinates
Definition at line 161 of file geometry.c.
References doublepair_t::x, and doublepair_t::y.
static double squareroot (const double num) static
Return the Square-Root of a positive number (Limit: 1000000000000000.0)
Private Function: Returns the Square-Root of a positive number (Limit: 1000000000000000.0)
Definition at line 671 of file mathfunc.c.
static float squarerootf (const float num) static
Return the Square-Root of a positive number (Limit: 1000000000.0)
Definition at line 700 of file mathfunc.c.
static long double squarerootl (const long double num) static
Return the Square-Root of a positive number
Definition at line 729 of file mathfunc.c.
double surfaceareacone (const double radius, const double height)
Return the surface area of a cone (double)
Definition at line 467 of file geometry.c.
References PI, and squareroot().
float surfaceareaconef (const float radius, const float height)
Return the surface area of a cone (float)
Definition at line 479 of file geometry.c.
References PIf, and squarerootf().
long double surfaceareaconel (const long double radius, const long double height)
Return the surface area of a cone (long double)
Definition at line 473 of file geometry.c.
References PIl, and squarerootl().
double surfaceareacube (const double length)
Return the surface area of a cube (double)
Definition at line 485 of file geometry.c.
float surfaceareacubef (const float length)
Return the surface area of a cube (float)
Definition at line 497 of file geometry.c.
long double surfaceareacubel (const long double length)
Return the surface area of a cube (long double)
Definition at line 491 of file geometry.c.
double surfaceareacylinder (const double radius, const double height)
Return the surface area of a cylinder (double)
Definition at line 503 of file geometry.c.
References PI2.
float surfaceareacylinderf (const float radius, const float height)
Return the surface area of a cylinder (float)
Definition at line 515 of file geometry.c.
References PI2f.
long double surfaceareacylinderl (const long double radius, const long double height)
Return the surface area of a cylinder (long double)
Definition at line 509 of file geometry.c.
References PI2l.
double surfacearearectangularprism (const double length, const double width, const double height)
Return the surface area of a rectangular prism (double)
Definition at line 521 of file geometry.c.
float surfacearearectangularprismf (const float length, const float width, const float height)
Return the surface area of a rectangular prism (float)
Definition at line 533 of file geometry.c.
long double surfacearearectangularprisml (const long double length, const long double width, const long double height)
Return the surface area of a rectangular prism (long double)
Definition at line 527 of file geometry.c.
double surfaceareasphere (const double radius)
Return the surface area of a sphere (double)
Definition at line 539 of file geometry.c.
References PI4.
float surfaceareaspheref (const float radius)
Return the surface area of a sphere (float)
Definition at line 551 of file geometry.c.
References PI4f.
long double surfaceareaspherel (const long double radius)
Return the surface area of a sphere (long double)
Definition at line 545 of file geometry.c.
References PI4l.
double surfaceareasquarepyramid (const double side, const double length)
Return the surface area of a square pyramid (double)
Definition at line 557 of file geometry.c.
float surfaceareasquarepyramidf (const float side, const float length)
Return the surface area of a square pyramid (float)
Definition at line 569 of file geometry.c.
long double surfaceareasquarepyramidl (const long double side, const long double length)
Return the surface area of a square pyramid (long double)
Definition at line 563 of file geometry.c.
double surfaceareatorus (const double radius1, const double radius2)
Return the surface area of a torus (double)
Definition at line 575 of file geometry.c.
References PI.
float surfaceareatorusf (const float radius1, const float radius2)
Return the surface area of a torus (float)
Definition at line 587 of file geometry.c.
References PIf.
long double surfaceareatorusl (const long double radius1, const long double radius2)
Return the surface area of a torus (long double)
Definition at line 581 of file geometry.c.
References PIl.
double volumecone (const double radius, const double height)
Return the volume of a cone (double)
Definition at line 597 of file geometry.c.
References PI_1_3.
float volumeconef (const float radius, const float height)
Return the volume of a cone (float)
Definition at line 609 of file geometry.c.
References PI_1_3f.
long double volumeconel (const long double radius, const long double height)
Return the volume of a cone (long double)
Definition at line 603 of file geometry.c.
References PI_1_3l.
double volumecylinder (const double radius, const double height)
Return the volume of a cylinder (double)
Definition at line 615 of file geometry.c.
References PI.
float volumecylinderf (const float radius, const float height)
Return the volume of a cylinder (float)
Definition at line 627 of file geometry.c.
References PIf.
long double volumecylinderl (const long double radius, const long double height)
Return the volume of a cylinder (long double)
Definition at line 621 of file geometry.c.
References PIl.
double volumeellipsoid (const double radius1, const double radius2, const double radius3)
Return the volume of a ellipsoid (double)
Definition at line 633 of file geometry.c.
References PI_4_3.
float volumeellipsoidf (const float radius1, const float radius2, const float radius3)
Return the volume of a ellipsoid (float)
Definition at line 645 of file geometry.c.
References PI_4_3f.
long double volumeellipsoidl (const long double radius1, const long double radius2, const long double radius3)
Return the volume of a ellipsoid (long double)
Definition at line 639 of file geometry.c.
References PI_4_3l.
double volumehemisphere (const double radius)
Return the volume of a hemisphere (double)
Definition at line 669 of file geometry.c.
References PI_2_3.
float volumehemispheref (const float radius)
Return the volume of a hemisphere (float)
Definition at line 681 of file geometry.c.
References PI_2_3f.
long double volumehemispherel (const long double radius)
Return the volume of a hemisphere (long double)
Definition at line 675 of file geometry.c.
References PI_2_3l.
double volumeparallelepiped (const double length, const double width, const double height)
Return the volume of a parallelepiped (double)
Definition at line 651 of file geometry.c.
float volumeparallelepipedf (const float length, const float width, const float height)
Return the volume of a parallelepiped (float)
Definition at line 663 of file geometry.c.
long double volumeparallelepipedl (const long double length, const long double width, const long double height)
Return the volume of a parallelepiped (long double)
Definition at line 657 of file geometry.c.
double volumeprism (const double length, const double base)
Return the volume of a prism (double)
Definition at line 687 of file geometry.c.
float volumeprismf (const float length, const float base)
Return the volume of a prism (float)
Definition at line 699 of file geometry.c.
long double volumeprisml (const long double length, const long double base)
Return the volume of a prism (long double)
Definition at line 693 of file geometry.c.
double volumerectanglarprism (const double length, const double width, const double height)
Return the volume of a rectanglar prism (double)
Definition at line 705 of file geometry.c.
float volumerectanglarprismf (const float length, const float width, const float height)
Return the volume of a rectanglar prism (float)
Definition at line 717 of file geometry.c.
long double volumerectanglarprisml (const long double length, const long double width, const long double height)
Return the volume of a rectanglar prism (long double)
Definition at line 711 of file geometry.c.
double volumesphere (const double radius)
Return the volume of a sphere (double)
Definition at line 723 of file geometry.c.
References PI_4_3.
float volumespheref (const float radius)
Return the volume of a sphere (float)
Definition at line 735 of file geometry.c.
References PI_4_3f.
long double volumespherel (const long double radius)
Return the volume of a sphere (long double)
Definition at line 729 of file geometry.c.
References PI_4_3l.
double volumesquarepyramid (const double height, const double base)
Return the volume of a square pyramid (double)
Definition at line 741 of file geometry.c.
float volumesquarepyramidf (const float height, const float base)
Return the volume of a square pyramid (float)
Definition at line 753 of file geometry.c.
long double volumesquarepyramidl (const long double height, const long double base)
Return the volume of a square pyramid (long double)
Definition at line 747 of file geometry.c.
double volumetetrahedron (const double height, const double base)
Return the volume of a tetrahedron (double)
Definition at line 759 of file geometry.c.
float volumetetrahedronf (const float height, const float base)
Return the volume of a tetrahedron (float)
Definition at line 771 of file geometry.c.
long double volumetetrahedronl (const long double height, const long double base)
Return the volume of a tetrahedron (long double)
Definition at line 765 of file geometry.c.
double volumetorus (const double radius1, const double radius2)
Return the volume of a torus (double)
Definition at line 777 of file geometry.c.
References PI_SQUARED_1_4.
float volumetorusf (const float radius1, const float radius2)
Return the volume of a torus (float)
Definition at line 789 of file geometry.c.
References PI_SQUARED_1_4f.
long double volumetorusl (const long double radius1, const long double radius2)
Return the volume of a torus (long double)
Definition at line 783 of file geometry.c.
References PI_SQUARED_1_4l.
doublepair_t xy2polar (const double x, const double y)
Return the polar-coordinates for the given (x,y)-coordinates
Definition at line 152 of file geometry.c.
References squareroot(), doublepair_t::x, and doublepair_t::y.
Variable Documentation
double(* linelength_point) (point location1, point location2)
Definition at line 76 of file geometry.h.
long double(* linelength_pointl) (pointl location1, pointl location2)
Definition at line 77 of file geometry.h.