PyBooster: mathfunc.c File Reference
mathfunc.c File Reference
Math Functions.
#include "mathfunc.h"
Functions
int abs_int (const int num)
double absd (const double num)
float absf (const float num)
long double absl (const long double num)
double acot (const double radians)
float acotf (const float radians)
double acoth (const double radians)
float acothf (const float radians)
long double acothl (const long double radians)
long double acotl (const long double radians)
double acsc (const double radians)
float acscf (const float radians)
double acsch (const double radians)
float acschf (const float radians)
long double acschl (const long double radians)
long double acscl (const long double radians)
double arc_angle (const double arc_length, const double radius)
double arccot (const double radians)
float arccotf (const float radians)
double arccoth (const double radians)
float arccothf (const float radians)
long double arccothl (const long double radians)
long double arccotl (const long double radians)
double arccsc (const double radians)
float arccscf (const float radians)
double arccsch (const double radians)
float arccschf (const float radians)
long double arccschl (const long double radians)
long double arccscl (const long double radians)
double arcexcot (const double radians)
float arcexcotf (const float radians)
double arcexcoth (const double radians)
float arcexcothf (const float radians)
long double arcexcothl (const long double radians)
long double arcexcotl (const long double radians)
double arcexcsc (const double radians)
float arcexcscf (const float radians)
double arcexcsch (const double radians)
float arcexcschf (const float radians)
long double arcexcschl (const long double radians)
long double arcexcscl (const long double radians)
double arcexsec (const double radians)
float arcexsecf (const float radians)
double arcexsech (const double radians)
float arcexsechf (const float radians)
long double arcexsechl (const long double radians)
long double arcexsecl (const long double radians)
double arcsec (const double radians)
float arcsecf (const float radians)
double arcsech (const double radians)
float arcsechf (const float radians)
long double arcsechl (const long double radians)
long double arcsecl (const long double radians)
double arcvercos (const double radians)
float arcvercosf (const float radians)
double arcvercosh (const double radians)
float arcvercoshf (const float radians)
long double arcvercoshl (const long double radians)
long double arcvercosl (const long double radians)
double arcversin (const double radians)
float arcversinf (const float radians)
double arcversinh (const double radians)
float arcversinhf (const float radians)
long double arcversinhl (const long double radians)
long double arcversinl (const long double radians)
double asec (const double radians)
float asecf (const float radians)
double asech (const double radians)
float asechf (const float radians)
long double asechl (const long double radians)
long double asecl (const long double radians)
double ATAN2 (const double y, const double x)
ullint bit_length (const ullint num)
double complex cacot (const double complex radians)
float complex cacotf (const float complex radians)
double complex cacoth (const double complex radians)
float complex cacothf (const float complex radians)
long double complex cacothl (const long double complex radians)
long double complex cacotl (const long double complex radians)
double complex cacsc (const double complex radians)
float complex cacscf (const float complex radians)
double complex cacsch (const double complex radians)
float complex cacschf (const float complex radians)
long double complex cacschl (const long double complex radians)
long double complex cacscl (const long double complex radians)
double complex carccot (const double complex radians)
float complex carccotf (const float complex radians)
double complex carccoth (const double complex radians)
float complex carccothf (const float complex radians)
long double complex carccothl (const long double complex radians)
long double complex carccotl (const long double complex radians)
double complex carccsc (const double complex radians)
float complex carccscf (const float complex radians)
double complex carccsch (const double complex radians)
float complex carccschf (const float complex radians)
long double complex carccschl (const long double complex radians)
long double complex carccscl (const long double complex radians)
double complex carcexcot (const double complex radians)
float complex carcexcotf (const float complex radians)
double complex carcexcoth (const double complex radians)
float complex carcexcothf (const float complex radians)
long double complex carcexcothl (const long double complex radians)
long double complex carcexcotl (const long double complex radians)
double complex carcexcsc (const double complex radians)
float complex carcexcscf (const float complex radians)
double complex carcexcsch (const double complex radians)
float complex carcexcschf (const float complex radians)
long double complex carcexcschl (const long double complex radians)
long double complex carcexcscl (const long double complex radians)
double complex carcexsec (const double complex radians)
float complex carcexsecf (const float complex radians)
double complex carcexsech (const double complex radians)
float complex carcexsechf (const float complex radians)
long double complex carcexsechl (const long double complex radians)
long double complex carcexsecl (const long double complex radians)
double complex carcsec (const double complex radians)
float complex carcsecf (const float complex radians)
double complex carcsech (const double complex radians)
float complex carcsechf (const float complex radians)
long double complex carcsechl (const long double complex radians)
long double complex carcsecl (const long double complex radians)
double complex carcvercos (const double complex radians)
float complex carcvercosf (const float complex radians)
double complex carcvercosh (const double complex radians)
float complex carcvercoshf (const float complex radians)
long double complex carcvercoshl (const long double complex radians)
long double complex carcvercosl (const long double complex radians)
double complex carcversin (const double complex radians)
float complex carcversinf (const float complex radians)
double complex carcversinh (const double complex radians)
float complex carcversinhf (const float complex radians)
long double complex carcversinhl (const long double complex radians)
long double complex carcversinl (const long double complex radians)
double complex casec (const double complex radians)
float complex casecf (const float complex radians)
double complex casech (const double complex radians)
float complex casechf (const float complex radians)
long double complex casechl (const long double complex radians)
long double complex casecl (const long double complex radians)
double complex ccos_arcsin (const double complex radians)
float complex ccos_arcsinf (const float complex radians)
long double complex ccos_arcsinl (const long double complex radians)
double complex ccos_arctan (const double complex radians)
float complex ccos_arctanf (const float complex radians)
long double complex ccos_arctanl (const long double complex radians)
double complex ccot (const double complex radians)
float complex ccotf (const float complex radians)
double complex ccoth (const double complex radians)
float complex ccothf (const float complex radians)
long double complex ccothl (const long double complex radians)
long double complex ccotl (const long double complex radians)
double complex ccrd (const double complex radians)
float complex ccrdf (const float complex radians)
long double complex ccrdl (const long double complex radians)
double complex ccsc (const double complex radians)
float complex ccscf (const float complex radians)
double complex ccsch (const double complex radians)
float complex ccschf (const float complex radians)
long double complex ccschl (const long double complex radians)
long double complex ccscl (const long double complex radians)
double complex cexcot (const double complex radians)
float complex cexcotf (const float complex radians)
double complex cexcoth (const double complex radians)
float complex cexcothf (const float complex radians)
long double complex cexcothl (const long double complex radians)
long double complex cexcotl (const long double complex radians)
double complex cexcsc (const double complex radians)
float complex cexcscf (const float complex radians)
double complex cexcsch (const double complex radians)
float complex cexcschf (const float complex radians)
long double complex cexcschl (const long double complex radians)
long double complex cexcscl (const long double complex radians)
double complex cexsec (const double complex radians)
float complex cexsecf (const float complex radians)
double complex cexsech (const double complex radians)
float complex cexsechf (const float complex radians)
long double complex cexsechl (const long double complex radians)
long double complex cexsecl (const long double complex radians)
double complex chacoversin (const double complex radians)
float complex chacoversinf (const float complex radians)
long double complex chacoversinl (const long double complex radians)
double complex chaversin (const double complex radians)
float complex chaversinf (const float complex radians)
long double complex chaversinl (const long double complex radians)
ullint clearlsb (ullint num)
double complement_angle_deg (const double angle)
float complement_angle_degf (const float angle)
long double complement_angle_degl (const long double angle)
double complex conjugate (const double complex num)
float complex conjugatef (const float complex num)
long double complex conjugatel (const long double complex num)
double cos_arcsin (const double radians)
float cos_arcsinf (const float radians)
long double cos_arcsinl (const long double radians)
double cos_arctan (const double radians)
float cos_arctanf (const float radians)
long double cos_arctanl (const long double radians)
double cot (const double radians)
float cotf (const float radians)
double coth (const double radians)
float cothf (const float radians)
long double cothl (const long double radians)
long double cotl (const long double radians)
double crd (const double radians)
float crdf (const float radians)
long double crdl (const long double radians)
double csc (const double radians)
float cscf (const float radians)
double csch (const double radians)
float cschf (const float radians)
long double cschl (const long double radians)
long double cscl (const long double radians)
double complex csec (const double complex radians)
float complex csecf (const float complex radians)
double complex csech (const double complex radians)
float complex csechf (const float complex radians)
long double complex csechl (const long double complex radians)
long double complex csecl (const long double complex radians)
double complex csin_arcsec (const double complex radians)
float complex csin_arcsecf (const float complex radians)
long double complex csin_arcsecl (const long double complex radians)
double complex csin_arctan (const double complex radians)
float complex csin_arctanf (const float complex radians)
long double complex csin_arctanl (const long double complex radians)
double complex cvercos (const double complex radians)
float complex cvercosf (const float complex radians)
double complex cvercosh (const double complex radians)
float complex cvercoshf (const float complex radians)
long double complex cvercoshl (const long double complex radians)
long double complex cvercosl (const long double complex radians)
double complex cversin (const double complex radians)
float complex cversinf (const float complex radians)
double complex cversinh (const double complex radians)
float complex cversinhf (const float complex radians)
long double complex cversinhl (const long double complex radians)
long double complex cversinl (const long double complex radians)
double div_and_mod (const double num1, const double num2)
int div_and_mod_int (const int num1, const int num2)
float div_and_modf (const float num1, const float num2)
ullint doublefactorial (const unsigned int num)
sllint doublefactoriallonglong (const sllint num)
double excot (const double radians)
float excotf (const float radians)
double excoth (const double radians)
float excothf (const float radians)
long double excothl (const long double radians)
long double excotl (const long double radians)
double excsc (const double radians)
float excscf (const float radians)
double excsch (const double radians)
float excschf (const float radians)
long double excschl (const long double radians)
long double excscl (const long double radians)
double exp_minus1 (const double num)
float exp_minus1f (const float num)
long double exp_minus1l (const long double num)
double exsec (const double radians)
float exsecf (const float radians)
double exsech (const double radians)
float exsechf (const float radians)
long double exsechl (const long double radians)
long double exsecl (const long double radians)
ullint factorial (const unsigned int num)
sllint factoriallonglong (const sllint num)
unsigned int fib (const unsigned int num)
double hacoversin (const double radians)
float hacoversinf (const float radians)
long double hacoversinl (const long double radians)
double haversin (const double radians)
float haversinf (const float radians)
long double haversinl (const long double radians)
unsigned int heptagonal_num (const unsigned int num)
sllint heptagonal_numlonglong (const sllint num)
ullint heptagonal_numull (const ullint num)
double heptagonal_root (const long num)
unsigned int hexagonal_num (const unsigned int num)
sllint hexagonal_numlonglong (const sllint num)
ullint hexagonal_numull (const ullint num)
double hexagonal_root (const long num)
double ipow (double num, const int exp)
int is_double_negative (double num)
int is_double_positive (double num)
int is_float_negative (float num)
int is_float_positive (float num)
int iscomposite (const int num)
int isdoublesquare (const double num)
int isdoubletriangular (const double num)
int isfloatsquare (const float num)
int isheptagonal (const long num)
int ishexagonal (const long num)
int islongcomposite (const long num)
int islongdoublesquare (const long double num)
int islonglongcomposite (const long long num)
int islonglongheptagonal (const long long num)
int islonglonghexagonal (const long long num)
int islonglongmersennenumber (const long long num)
int islonglongmersenneprime (const sllint num)
int islonglongpoweroftwo (const long long num)
int islonglongprime (const long long num)
int islonglongsquare (const long long num)
int islonglongtriangular (const long long num)
int islongprime (const long num)
int islongsquare (const long num)
int ismersennenumber (const unsigned int num)
int ismersenneprime (const unsigned int num)
int ispoweroftwo (const unsigned int num)
int isprime (const int num)
uint16_t isqrt16 (const uint16_t num)
uint32_t isqrt32 (const uint32_t num)
uint64_t isqrt64 (const uint64_t num)
uint8_t isqrt8 (const uint8_t num)
int issquare (const int num)
int istriangular (const long num)
int isulcomposite (const ulint num)
int isullcomposite (const ullint num)
int isullpoweroftwo (const ullint num)
int isullprime (const ullint num)
int isulprime (const ulint num)
int isunsignedcomposite (const unsigned int num)
int isunsignedprime (const unsigned int num)
double lanczos_sum (const double x)
double ln (const double num)
double lnp1 (const double num)
double LOG (const double num)
double LOG10 (const double num)
double LOG2 (const double num)
double log_plus1 (const double num)
float log_plus1f (const float num)
long double log_plus1l (const long double num)
unsigned long int longfib (const unsigned long int num)
sllint longlongfib (const sllint num)
double longmean (const slint count,...)
int max (const int count,...)
double maxd (const int count,...)
float maxf (const int count,...)
double mean (const int count,...)
float meanf (const int count,...)
long double meanl (const long long int count,...)
unsigned int mersenne_num (const unsigned int num)
sllint mersenne_numlonglong (const sllint num)
ullint mersenne_numull (const ullint num)
int min (const int count,...)
double mind (const int count,...)
float minf (const int count,...)
signed int mod_pow (const signed int base, const signed int exponent, const signed int modulus)
sllint mod_pow_longlong (const sllint base, const sllint exponent, const sllint modulus)
double norm (const double complex x)
float normf (const float complex x)
long double norml (const long double complex x)
unsigned int pentatope_num (const unsigned int num)
sllint pentatope_numlonglong (const sllint num)
ullint pentatope_numull (const ullint num)
double poly (const double x, const size_t n, const double *__restrict__ c)
unsigned long long int pow2 (const unsigned int num)
signed long long int pow2_longlong (const signed long long int num)
double pow_ten (const signed int num)
unsigned long long int pow_ten_int (const unsigned int num)
unsigned long long int pow_ten_int_fast (const unsigned int num)
double pow_ten_neg (const signed int num)
float pow_ten_negf (const signed int num)
long double pow_ten_negl (const slint num)
double pow_ten_pos (const unsigned int num)
float pow_ten_posf (const unsigned int num)
long double pow_ten_posl (const unsigned long int num)
long double pow_tenl (const signed int num)
unsigned int pronic (const unsigned int num)
sllint proniclonglong (const sllint num)
ullint pronicull (const ullint num)
quaternion qadd (const quaternion num1, const quaternion num2)
quaternion_float qaddf (const quaternion_float num1, const quaternion_float num2)
quaternion_long_double qaddl (const quaternion_long_double num1, const quaternion_long_double num2)
quaternion qconjugate (const quaternion num)
quaternion_float qconjugatef (const quaternion_float num)
quaternion_long_double qconjugatel (const quaternion_long_double num)
quaternion qdiv (const quaternion num1, const quaternion num2)
quaternion_float qdivf (const quaternion_float num1, const quaternion_float num2)
quaternion_long_double qdivl (const quaternion_long_double num1, const quaternion_long_double num2)
double qgeti (const quaternion num)
float qgetif (const quaternion_float num)
long double qgetil (const quaternion_long_double num)
double qgetj (const quaternion num)
float qgetjf (const quaternion_float num)
long double qgetjl (const quaternion_long_double num)
double qgetk (const quaternion num)
float qgetkf (const quaternion_float num)
long double qgetkl (const quaternion_long_double num)
quaternion qinv (const quaternion qnum)
void qinv_inplace (quaternion qnum)
void qinv_inplacef (quaternion_float qnum)
void qinv_inplacel (quaternion_long_double qnum)
quaternion_float qinvf (const quaternion_float qnum)
quaternion_long_double qinvl (const quaternion_long_double qnum)
double qlen (const quaternion num)
float qlenf (const quaternion_float num)
long double qlenl (const quaternion_long_double num)
quaternion qmid (const quaternion num1, const quaternion num2)
quaternion_float qmidf (const quaternion_float num1, const quaternion_float num2)
quaternion_long_double qmidl (const quaternion_long_double num1, const quaternion_long_double num2)
quaternion qmul (const quaternion num1, const quaternion num2)
quaternion_float qmulf (const quaternion_float num1, const quaternion_float num2)
quaternion_long_double qmull (const quaternion_long_double num1, const quaternion_long_double num2)
quaternion qneg (const quaternion qnum)
void qneg_inplace (quaternion qnum)
void qneg_inplacef (quaternion_float qnum)
void qneg_inplacel (quaternion_long_double qnum)
quaternion_float qnegf (const quaternion_float qnum)
quaternion_long_double qnegl (const quaternion_long_double qnum)
double qnorm (const quaternion num)
float qnormf (const quaternion_float num)
long double qnorml (const quaternion_long_double num)
double qreal (const quaternion num)
float qrealf (const quaternion_float num)
long double qreall (const quaternion_long_double num)
quaternion qscalar (const quaternion num)
quaternion_float qscalarf (const quaternion_float num)
quaternion_long_double qscalarl (const quaternion_long_double num)
quaternion qsqrt (const quaternion num)
quaternion_float qsqrtf (const quaternion_float num)
quaternion_long_double qsqrtl (const quaternion_long_double num)
quaternion qsub (const quaternion num1, const quaternion num2)
quaternion_float qsubf (const quaternion_float num1, const quaternion_float num2)
quaternion_long_double qsubl (const quaternion_long_double num1, const quaternion_long_double num2)
ullint quadfactorial (const unsigned int num)
sllint quadfactoriallonglong (const sllint num)
quaternion qvector (const quaternion num)
quaternion_float qvectorf (const quaternion_float num)
quaternion_long_double qvectorl (const quaternion_long_double num)
quaternion qversor (const quaternion num)
quaternion_float qversorf (const quaternion_float num)
quaternion_long_double qversorl (const quaternion_long_double num)
double retint (const double x)
double sawtooth (const double x)
double sawtooth2 (const double x, const double period, const double amplitude)
double sec (const double radians)
float secf (const float radians)
double sech (const double radians)
float sechf (const float radians)
long double sechl (const long double radians)
long double secl (const long double radians)
double sgn (const double num)
signed int sgn_int (const signed int num)
float sgnf (const float num)
long double sgnl (const long double num)
double sigmoid (const double x)
double signed_pow (const signed int base, const signed int exponent)
long double signed_powl (const slint base, const slint exponent)
double sin_arcsec (const double radians)
float sin_arcsecf (const float radians)
long double sin_arcsecl (const long double radians)
double sin_arctan (const double radians)
float sin_arctanf (const float radians)
long double sin_arctanl (const long double radians)
double sin_wave_equation (const double amplitude, const double angle)
double sinpi (const double num)
uint8_t sqrt16 (const uint16_t num)
uint16_t sqrt32 (const uint32_t num)
uint32_t sqrt64 (const uint64_t num)
ullint sqrtull (const ullint num)
double squareroot (const double num)
float squarerootf (const float num)
long double squarerootl (const long double num)
double squarewave (const double x)
ullint superfactorial (const unsigned int num)
sllint superfactoriallonglong (const sllint num)
double supplement_angle_deg (const double angle)
float supplement_angle_degf (const float angle)
long double supplement_angle_degl (const long double angle)
unsigned int tetrahedral_num (const unsigned int num)
sllint tetrahedral_numlonglong (const sllint num)
ullint tetrahedral_numull (const ullint num)
int trianglewave (const int x)
unsigned int triangular_num (const unsigned int num)
sllint triangular_numlonglong (const sllint num)
ullint triangular_numull (const ullint num)
double triangular_root (const long num)
int unfactorial (const int num)
uint64_t unfactorial64 (const uint64_t num)
ullint unsigned_pow (const unsigned int base, const unsigned int exponent)
double vercos (const double radians)
float vercosf (const float radians)
double vercosh (const double radians)
float vercoshf (const float radians)
long double vercoshl (const long double radians)
long double vercosl (const long double radians)
double versin (const double radians)
float versinf (const float radians)
double versinh (const double radians)
float versinhf (const float radians)
long double versinhl (const long double radians)
long double versinl (const long double radians)
Variables
static const double LANCZOS_DEN_COEFFS__ [16]
static const double LANCZOS_NUM_COEFFS__ [16]
Detailed Description
Math Functions.
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.18
DESCRIPTION
Numerous mathematical and trigonometric functions. This extends the standard math library by providing by offering faster alternatives. Such functions include squareroot, fractorial, fib, haversin, isprime, ishexagonal, etc.
<math.h> contains
cos, sin, tan // General (Radians)
acos, asin, atan, atan2 // Arcs
cosh, sinh, tanh // Hyperbolics
acosh, asinh, atanh // Arc-Hyperbolics
hypot
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Types_of_Numbers
https://en.wikipedia.org/wiki/List_of_types_of_numbers
NATURAL/CARDINAL NUMBER (): Counting numbers {0, 1, 2, 3, }, are called natural numbers. (https://en.wikipedia.org/wiki/Natural_number)
INTEGER (): A number that can be written without a fractional component. For example, 17, 3, 0, and -1024 are integers, while 9.73, 5 12, and 2 are not integers. (https://en.wikipedia.org/wiki/Integer)
RATIONAL NUMBER (): Any number that can be expressed as the quotient or fraction p/q of two integers, p and q, with the denominator, q, not equal to zero. Since q may be equal to 1, every integer is a rational number. The decimal expansion of a rational number always either terminates after a finite number of digits or begins to repeat the same finite sequence of digits over and over. (https://en.wikipedia.org/wiki/Rational_number)
TRANSCENDENTAL NUMBER: A real or complex number that is not algebraic; that is, it is not a root of a non-zero polynomial equation with rational coefficients. The best-known transcendental numbers are and e. (https://en.wikipedia.org/wiki/Transcendental_number)
REAL NUMBER (): A value that represents a quantity along a continuous line. The real numbers include all the rational numbers, such as the integer -5 and the fraction 4/3, all the irrational numbers, such as 2 (1.41421356) and all transcendental numbers, such as (3.14159265). (https://en.wikipedia.org/wiki/Real_number)
IRRATIONAL NUMBER (): Any real number that cannot be expressed as a ratio of integers. Irrational numbers cannot be represented as terminating or repeating decimals. As a consequence of Cantor's proof that the real numbers are uncountable and the rationals countable, almost all real numbers are irrational. Irrational numbers include 2, , e, and . (https://en.wikipedia.org/wiki/Irrational_number)
IMAGINARY NUMBER: A complex number that can be written as a real number multiplied by the imaginary unit . (https://en.wikipedia.org/wiki/Imaginary_number)
COMPLEX NUMBER (): A number that can be expressed in the form a + b, where a and b are real numbers and is the imaginary unit, that satisfies the equation ^2=-1. In this expression, a is the real part and b is the imaginary part of the complex number. (https://en.wikipedia.org/wiki/Complex_number)
TESSARINE OR BICOMPLEX-NUMBER: A hypercomplex number in a commutative, associative algebra over real numbers with two imaginary units (designated i and k). (https://en.wikipedia.org/wiki/Bicomplex_number)
HYPERCOMPLEX NUMBER: An element of a unital algebra over the field of real numbers. Hypercomplex numbers include quaternions, octonions, sedenions, tessarines, coquaternions, and biquaternions. (https://en.wikipedia.org/wiki/Hypercomplex_number)
QUATERNION (): A number system that extends the complex numbers and applied to mechanics in three-dimensional space. A feature of quaternions is that multiplication of two quaternions is noncommutative. Hamilton defined a quaternion as the quotient of two directed lines in a three-dimensional space or equivalently as the quotient of two vectors. Quaternions form a four-dimensional associative normed division algebra over the real numbers, and therefore also a domain. In fact, the quaternions were the first noncommutative division algebra to be discovered. (https://en.wikipedia.org/wiki/Quaternion)
SPLIT-QUATERNION OR COQUATERNION: Elements of a 4-dimensional associative algebra. Unlike the quaternion algebra, the split-quaternions contain zero divisors, nilpotent elements, and nontrivial idempotents. As a mathematical structure, they form an algebra over the real numbers, which is isomorphic to the algebra of 22 real matrices. A coquaternion equals `w + xi + yj + zk`. (https://en.wikipedia.org/wiki/Split-quaternion)
BIQUATERNION: Are the numbers w + x i + y j + z k, where w, x, y, and z are complex numbers and the elements of {1, i, j, k} multiply as in the quaternion group. As there are three types of complex numbers, so there are three types of biquaternions (Ordinary Biquaternions, Split-biquaternions, and Dual quaternions). (https://en.wikipedia.org/wiki/Biquaternion)
OCTONION (): Normed division algebra over the real numbers. Octonions have eight dimensions; twice the number of dimensions of the quaternions. They are noncommutative and nonassociative, but satisfy a weaker form of associativity. (https://en.wikipedia.org/wiki/Octonion)
SEDENION (): 16-dimensional noncommutative and nonassociative numbers over the reals and obtained by applying the CayleyDickson construction to the octonions. (https://en.wikipedia.org/wiki/Sedenion)
Definition in file mathfunc.c.
Function Documentation
int abs_int (const int num)
Absolute value - strip the negative sign and return the number
Definition at line 4414 of file mathfunc.c.
Referenced by trianglewave().
double absd (const double num)
Absolute value - strip the negative sign and return the number
Definition at line 4420 of file mathfunc.c.
float absf (const float num)
Absolute value - strip the negative sign and return the number
Definition at line 4427 of file mathfunc.c.
long double absl (const long double num)
Absolute value - strip the negative sign and return the number
Definition at line 4434 of file mathfunc.c.
double acot (const double radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 1441 of file mathfunc.c.
float acotf (const float radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 1795 of file mathfunc.c.
double acoth (const double radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 1453 of file mathfunc.c.
float acothf (const float radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 1807 of file mathfunc.c.
long double acothl (const long double radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 1630 of file mathfunc.c.
long double acotl (const long double radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 1618 of file mathfunc.c.
double acsc (const double radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 1477 of file mathfunc.c.
float acscf (const float radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 1831 of file mathfunc.c.
double acsch (const double radians)
Return the Hyperbolic Arc-Cosecant (acsch(x)||arccsch(x) == asinh(1/x))
Definition at line 1489 of file mathfunc.c.
float acschf (const float radians)
Return the Hyperbolic Arc-Cosecant (acsch(x)||arccsch(x) == asinh(1/x))
Definition at line 1843 of file mathfunc.c.
long double acschl (const long double radians)
Return the Hyperbolic Arc-Cosecant (acsch(x)||arccsch(x) == asinh(1/x))
Definition at line 1666 of file mathfunc.c.
long double acscl (const long double radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 1654 of file mathfunc.c.
double arc_angle (const double arc_length, const double radius)
Return the angle (in radians) of an arc given arc-length and radius
Definition at line 146 of file mathfunc.c.
double arccot (const double radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 1447 of file mathfunc.c.
float arccotf (const float radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 1801 of file mathfunc.c.
double arccoth (const double radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 1459 of file mathfunc.c.
float arccothf (const float radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 1813 of file mathfunc.c.
long double arccothl (const long double radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 1636 of file mathfunc.c.
long double arccotl (const long double radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 1624 of file mathfunc.c.
double arccsc (const double radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 1483 of file mathfunc.c.
float arccscf (const float radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 1837 of file mathfunc.c.
double arccsch (const double radians)
Return the Hyperbolic Arc-Cosecant (acsc(x)||arccsch(x) == asinh(1/x))
Definition at line 1495 of file mathfunc.c.
float arccschf (const float radians)
Return the Hyperbolic Arc-Cosecant (acsc(x)||arccsch(x) == asinh(1/x))
Definition at line 1849 of file mathfunc.c.
long double arccschl (const long double radians)
Return the Hyperbolic Arc-Cosecant (acsc(x)||arccsch(x) == asinh(1/x))
Definition at line 1672 of file mathfunc.c.
long double arccscl (const long double radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 1660 of file mathfunc.c.
double arcexcot (const double radians)
Return the Arc-External Cotangent (arcexcot(x) == atan(1/(x+1)))
Definition at line 1966 of file mathfunc.c.
float arcexcotf (const float radians)
Return the Arc-External Cotangent (arcexcot(x) == atan(1/(x+1)))
Definition at line 2116 of file mathfunc.c.
double arcexcoth (const double radians)
Return the Hyperbolic Arc-External Cotangent [arcexcoth(x) == (1/atanh(x)-1)]
Definition at line 1972 of file mathfunc.c.
float arcexcothf (const float radians)
Return the Hyperbolic Arc-External Cotangent [arcexcoth(x) == (1/atanh(x)-1)]
Definition at line 2122 of file mathfunc.c.
long double arcexcothl (const long double radians)
Return the Hyperbolic Arc-External Cotangent [arcexcoth(x) == (1/atanh(x)-1)]
Definition at line 2047 of file mathfunc.c.
long double arcexcotl (const long double radians)
Return the Arc-External Cotangent (arcexcot(x) == atan(1/(x+1)))
Definition at line 2041 of file mathfunc.c.
double arcexcsc (const double radians)
Return the Arc-External Cosecant (arcexcsc(x) == asin(1/(x+1)))
Definition at line 1990 of file mathfunc.c.
float arcexcscf (const float radians)
Return the Arc-External Cosecant (arcexcsc(x) == asin(1/(x+1)))
Definition at line 2140 of file mathfunc.c.
double arcexcsch (const double radians)
Return the Hyperbolic Arc-External Cosecant [arcexcsch(x) == (1/asinh(x)-1)]
Definition at line 1996 of file mathfunc.c.
float arcexcschf (const float radians)
Return the Hyperbolic Arc-External Cosecant [arcexcsch(x) == (1/asinh(x)-1)]
Definition at line 2146 of file mathfunc.c.
long double arcexcschl (const long double radians)
Return the Hyperbolic Arc-External Cosecant [arcexcsch(x) == (1/asinh(x)-1)]
Definition at line 2071 of file mathfunc.c.
long double arcexcscl (const long double radians)
Return the Arc-External Cosecant (arcexcsc(x) == asin(1/(x+1)))
Definition at line 2065 of file mathfunc.c.
double arcexsec (const double radians)
Return the Arc-External Secant (arcexsec(x) == acos(1/(x+1)))
Definition at line 2014 of file mathfunc.c.
float arcexsecf (const float radians)
Return the Arc-External Secant (arcexsec(x) == acos(1/(x+1)))
Definition at line 2164 of file mathfunc.c.
double arcexsech (const double radians)
Return the Hyperbolic Arc-External Secant [arcexsech(x) == (1/acosh(x)-1)]
Definition at line 2020 of file mathfunc.c.
float arcexsechf (const float radians)
Return the Hyperbolic Arc-External Secant [arcexsech(x) == (1/acosh(x)-1)]
Definition at line 2170 of file mathfunc.c.
long double arcexsechl (const long double radians)
Return the Hyperbolic Arc-External Secant [arcexsech(x) == (1/acosh(x)-1)]
Definition at line 2095 of file mathfunc.c.
long double arcexsecl (const long double radians)
Return the Arc-External Secant (arcexsec(x) == acos(1/(x+1)))
Definition at line 2089 of file mathfunc.c.
double arcsec (const double radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 1519 of file mathfunc.c.
float arcsecf (const float radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 1873 of file mathfunc.c.
double arcsech (const double radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 1531 of file mathfunc.c.
float arcsechf (const float radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 1885 of file mathfunc.c.
long double arcsechl (const long double radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 1708 of file mathfunc.c.
long double arcsecl (const long double radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 1696 of file mathfunc.c.
double arcvercos (const double radians)
Return the Arc-Versed Cosine (arcvercos(x) == 1 - asin(x))
Definition at line 1573 of file mathfunc.c.
float arcvercosf (const float radians)
Return the Arc-Versed Cosine (arcvercos(x) == 1 - asin(x))
Definition at line 1927 of file mathfunc.c.
double arcvercosh (const double radians)
Return the Hyperbolic Arc-Versed Cosine (arcvercosh(x) == 1 - asinh(x))
Definition at line 1579 of file mathfunc.c.
float arcvercoshf (const float radians)
Return the Hyperbolic Arc-Versed Cosine (arcvercosh(x) == 1 - asinh(x))
Definition at line 1933 of file mathfunc.c.
long double arcvercoshl (const long double radians)
Return the Hyperbolic Arc-Versed Cosine (arcvercosh(x) == 1 - asinh(x))
Definition at line 1756 of file mathfunc.c.
long double arcvercosl (const long double radians)
Return the Arc-Versed Cosine (arcvercos(x) == 1 - asin(x))
Definition at line 1750 of file mathfunc.c.
double arcversin (const double radians)
Return the Arc-Versed Sine (arcversin(x) == 1 - acos(x))
Definition at line 1549 of file mathfunc.c.
float arcversinf (const float radians)
Return the Arc-Versed Sine (arcversin(x) == 1 - acos(x))
Definition at line 1903 of file mathfunc.c.
double arcversinh (const double radians)
Return the Hyperbolic Arc-Versed Sine (arcversinh(x) == 1 - acosh(x))
Definition at line 1555 of file mathfunc.c.
float arcversinhf (const float radians)
Return the Hyperbolic Arc-Versed Sine (arcversinh(x) == 1 - acosh(x))
Definition at line 1909 of file mathfunc.c.
long double arcversinhl (const long double radians)
Return the Hyperbolic Arc-Versed Sine (arcversinh(x) == 1 - acosh(x))
Definition at line 1732 of file mathfunc.c.
long double arcversinl (const long double radians)
Return the Arc-Versed Sine (arcversin(x) == 1 - acos(x))
Definition at line 1726 of file mathfunc.c.
double asec (const double radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 1513 of file mathfunc.c.
float asecf (const float radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 1867 of file mathfunc.c.
double asech (const double radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 1525 of file mathfunc.c.
float asechf (const float radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 1879 of file mathfunc.c.
long double asechl (const long double radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 1702 of file mathfunc.c.
long double asecl (const long double radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 1690 of file mathfunc.c.
double ATAN2 (const double y, const double x)
Returns the principal value of the arc tangent of y/x, expressed in radians
Definition at line 1387 of file mathfunc.c.
References PI.
ullint bit_length (const ullint num)
Return the number of bits used to represent the given number
Definition at line 4352 of file mathfunc.c.
References ullint.
Referenced by lib.basic::char2bitlen(), and mathfunc_bit_length().
double complex cacot (const double complex radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 3005 of file mathfunc.c.
References I_DOUBLE.
float complex cacotf (const float complex radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 3359 of file mathfunc.c.
References I_FLOAT.
double complex cacoth (const double complex radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 3017 of file mathfunc.c.
References I_DOUBLE.
float complex cacothf (const float complex radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 3371 of file mathfunc.c.
References I_FLOAT.
long double complex cacothl (const long double complex radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 3194 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex cacotl (const long double complex radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 3182 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex cacsc (const double complex radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 3041 of file mathfunc.c.
References I_DOUBLE.
float complex cacscf (const float complex radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 3395 of file mathfunc.c.
References I_FLOAT.
double complex cacsch (const double complex radians)
Return the Hyperbolic Arc-Cosecant (acsch(x)||arccsch(x) == asinh(1/x))
Definition at line 3053 of file mathfunc.c.
References I_DOUBLE.
float complex cacschf (const float complex radians)
Return the Hyperbolic Arc-Cosecant (acsch(x)||arccsch(x) == asinh(1/x))
Definition at line 3407 of file mathfunc.c.
References I_FLOAT.
long double complex cacschl (const long double complex radians)
Return the Hyperbolic Arc-Cosecant (acsch(x)||arccsch(x) == asinh(1/x))
Definition at line 3230 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex cacscl (const long double complex radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 3218 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex carccot (const double complex radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 3011 of file mathfunc.c.
References I_DOUBLE.
float complex carccotf (const float complex radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 3365 of file mathfunc.c.
References I_FLOAT.
double complex carccoth (const double complex radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 3023 of file mathfunc.c.
References I_DOUBLE.
float complex carccothf (const float complex radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 3377 of file mathfunc.c.
References I_FLOAT.
long double complex carccothl (const long double complex radians)
Return the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))
Definition at line 3200 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex carccotl (const long double complex radians)
Return the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))
Definition at line 3188 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex carccsc (const double complex radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 3047 of file mathfunc.c.
References I_DOUBLE.
float complex carccscf (const float complex radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 3401 of file mathfunc.c.
References I_FLOAT.
double complex carccsch (const double complex radians)
Return the Hyperbolic Arc-Cosecant (acsc(x)||arccsch(x) == asinh(1/x))
Definition at line 3059 of file mathfunc.c.
References I_DOUBLE.
float complex carccschf (const float complex radians)
Return the Hyperbolic Arc-Cosecant (acsc(x)||arccsch(x) == asinh(1/x))
Definition at line 3413 of file mathfunc.c.
References I_FLOAT.
long double complex carccschl (const long double complex radians)
Return the Hyperbolic Arc-Cosecant (acsc(x)||arccsch(x) == asinh(1/x))
Definition at line 3236 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex carccscl (const long double complex radians)
Return the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))
Definition at line 3224 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex carcexcot (const double complex radians)
Return the Arc-External Cotangent (arcexcot(x) == atan(1/(x+1)))
Definition at line 3530 of file mathfunc.c.
References I_DOUBLE.
float complex carcexcotf (const float complex radians)
Return the Arc-External Cotangent (arcexcot(x) == atan(1/(x+1)))
Definition at line 3680 of file mathfunc.c.
References I_FLOAT.
double complex carcexcoth (const double complex radians)
Return the Hyperbolic Arc-External Cotangent [arcexcoth(x) == (1/atanh(x)-1)]
Definition at line 3536 of file mathfunc.c.
References I_DOUBLE.
float complex carcexcothf (const float complex radians)
Return the Hyperbolic Arc-External Cotangent [arcexcoth(x) == (1/atanh(x)-1)]
Definition at line 3686 of file mathfunc.c.
References I_FLOAT.
long double complex carcexcothl (const long double complex radians)
Return the Hyperbolic Arc-External Cotangent [arcexcoth(x) == (1/atanh(x)-1)]
Definition at line 3611 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex carcexcotl (const long double complex radians)
Return the Arc-External Cotangent (arcexcot(x) == atan(1/(x+1)))
Definition at line 3605 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex carcexcsc (const double complex radians)
Return the Arc-External Cosecant (arcexcsc(x) == asin(1/(x+1)))
Definition at line 3554 of file mathfunc.c.
References I_DOUBLE.
float complex carcexcscf (const float complex radians)
Return the Arc-External Cosecant (arcexcsc(x) == asin(1/(x+1)))
Definition at line 3704 of file mathfunc.c.
References I_FLOAT.
double complex carcexcsch (const double complex radians)
Return the Hyperbolic Arc-External Cosecant [arcexcsch(x) == (1/asinh(x)-1)]
Definition at line 3560 of file mathfunc.c.
References I_DOUBLE.
float complex carcexcschf (const float complex radians)
Return the Hyperbolic Arc-External Cosecant [arcexcsch(x) == (1/asinh(x)-1)]
Definition at line 3710 of file mathfunc.c.
References I_FLOAT.
long double complex carcexcschl (const long double complex radians)
Return the Hyperbolic Arc-External Cosecant [arcexcsch(x) == (1/asinh(x)-1)]
Definition at line 3635 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex carcexcscl (const long double complex radians)
Return the Arc-External Cosecant (arcexcsc(x) == asin(1/(x+1)))
Definition at line 3629 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex carcexsec (const double complex radians)
Return the Arc-External Secant (arcexsec(x) == acos(1/(x+1)))
Definition at line 3578 of file mathfunc.c.
References I_DOUBLE.
float complex carcexsecf (const float complex radians)
Return the Arc-External Secant (arcexsec(x) == acos(1/(x+1)))
Definition at line 3728 of file mathfunc.c.
References I_FLOAT.
double complex carcexsech (const double complex radians)
Return the Hyperbolic Arc-External Secant [arcexsech(x) == (1/acosh(x)-1)]
Definition at line 3584 of file mathfunc.c.
References I_DOUBLE.
float complex carcexsechf (const float complex radians)
Return the Hyperbolic Arc-External Secant [arcexsech(x) == (1/acosh(x)-1)]
Definition at line 3734 of file mathfunc.c.
References I_FLOAT.
long double complex carcexsechl (const long double complex radians)
Return the Hyperbolic Arc-External Secant [arcexsech(x) == (1/acosh(x)-1)]
Definition at line 3659 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex carcexsecl (const long double complex radians)
Return the Arc-External Secant (arcexsec(x) == acos(1/(x+1)))
Definition at line 3653 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex carcsec (const double complex radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 3083 of file mathfunc.c.
References I_DOUBLE.
float complex carcsecf (const float complex radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 3437 of file mathfunc.c.
References I_FLOAT.
double complex carcsech (const double complex radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 3095 of file mathfunc.c.
References I_DOUBLE.
float complex carcsechf (const float complex radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 3449 of file mathfunc.c.
References I_FLOAT.
long double complex carcsechl (const long double complex radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 3272 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex carcsecl (const long double complex radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 3260 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex carcvercos (const double complex radians)
Return the Arc-Versed Cosine (arcvercos(x) == 1 - asin(x))
Definition at line 3137 of file mathfunc.c.
References I_DOUBLE.
float complex carcvercosf (const float complex radians)
Return the Arc-Versed Cosine (arcvercos(x) == 1 - asin(x))
Definition at line 3491 of file mathfunc.c.
References I_FLOAT.
double complex carcvercosh (const double complex radians)
Return the Hyperbolic Arc-Versed Cosine (arcvercosh(x) == 1 - asinh(x))
Definition at line 3143 of file mathfunc.c.
References I_DOUBLE.
float complex carcvercoshf (const float complex radians)
Return the Hyperbolic Arc-Versed Cosine (arcvercosh(x) == 1 - asinh(x))
Definition at line 3497 of file mathfunc.c.
References I_FLOAT.
long double complex carcvercoshl (const long double complex radians)
Return the Hyperbolic Arc-Versed Cosine (arcvercosh(x) == 1 - asinh(x))
Definition at line 3320 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex carcvercosl (const long double complex radians)
Return the Arc-Versed Cosine (arcvercos(x) == 1 - asin(x))
Definition at line 3314 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex carcversin (const double complex radians)
Return the Arc-Versed Sine (arcversin(x) == 1 - acos(x))
Definition at line 3113 of file mathfunc.c.
References I_DOUBLE.
float complex carcversinf (const float complex radians)
Return the Arc-Versed Sine (arcversin(x) == 1 - acos(x))
Definition at line 3467 of file mathfunc.c.
References I_FLOAT.
double complex carcversinh (const double complex radians)
Return the Hyperbolic Arc-Versed Sine (arcversinh(x) == 1 - acosh(x))
Definition at line 3119 of file mathfunc.c.
References I_DOUBLE.
float complex carcversinhf (const float complex radians)
Return the Hyperbolic Arc-Versed Sine (arcversinh(x) == 1 - acosh(x))
Definition at line 3473 of file mathfunc.c.
References I_FLOAT.
long double complex carcversinhl (const long double complex radians)
Return the Hyperbolic Arc-Versed Sine (arcversinh(x) == 1 - acosh(x))
Definition at line 3296 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex carcversinl (const long double complex radians)
Return the Arc-Versed Sine (arcversin(x) == 1 - acos(x))
Definition at line 3290 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex casec (const double complex radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 3077 of file mathfunc.c.
References I_DOUBLE.
float complex casecf (const float complex radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 3431 of file mathfunc.c.
References I_FLOAT.
double complex casech (const double complex radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 3089 of file mathfunc.c.
References I_DOUBLE.
float complex casechf (const float complex radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 3443 of file mathfunc.c.
References I_FLOAT.
long double complex casechl (const long double complex radians)
Return the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))
Definition at line 3266 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex casecl (const long double complex radians)
Return the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))
Definition at line 3254 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex ccos_arcsin (const double complex radians)
Return the Cosine of an Arc-Sine [sqrt(1-(x*x))]
Definition at line 3755 of file mathfunc.c.
References I_DOUBLE.
float complex ccos_arcsinf (const float complex radians)
Return the Cosine of an Arc-Sine [sqrt(1-(x*x))]
Definition at line 3809 of file mathfunc.c.
References I_FLOAT.
long double complex ccos_arcsinl (const long double complex radians)
Return the Cosine of an Arc-Sine [sqrt(1-(x*x))]
Definition at line 3782 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex ccos_arctan (const double complex radians)
Return the Cosine of an Arc-Tangent [1 / sqrt(1+(x*x))]
Definition at line 3761 of file mathfunc.c.
References I_DOUBLE.
float complex ccos_arctanf (const float complex radians)
Return the Cosine of an Arc-Tangent [1 / sqrt(1+(x*x))]
Definition at line 3815 of file mathfunc.c.
References I_FLOAT.
long double complex ccos_arctanl (const long double complex radians)
Return the Cosine of an Arc-Tangent [1 / sqrt(1+(x*x))]
Definition at line 3788 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex ccot (const double complex radians)
Return the Cotangent (cot(x) == 1/tan(x))
Definition at line 3035 of file mathfunc.c.
References I_DOUBLE.
float complex ccotf (const float complex radians)
Return the Cotangent (cot(x) == 1/tan(x))
Definition at line 3389 of file mathfunc.c.
References I_FLOAT.
double complex ccoth (const double complex radians)
Return the Hyperbolic Cotangent (coth(x) == 1/tanh(x))
Definition at line 3029 of file mathfunc.c.
References I_DOUBLE.
float complex ccothf (const float complex radians)
Return the Hyperbolic Cotangent (coth(x) == 1/tanh(x))
Definition at line 3383 of file mathfunc.c.
References I_FLOAT.
long double complex ccothl (const long double complex radians)
Return the Hyperbolic Cotangent (coth(x) == 1/tanh(x))
Definition at line 3206 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex ccotl (const long double complex radians)
Return the Cotangent (cot(x) == 1/tan(x))
Definition at line 3212 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex ccrd (const double complex radians)
Return the Chord
Definition at line 2999 of file mathfunc.c.
References I_DOUBLE.
float complex ccrdf (const float complex radians)
Return the Chord
Definition at line 3353 of file mathfunc.c.
References I_FLOAT.
long double complex ccrdl (const long double complex radians)
Return the Chord
Definition at line 3176 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex ccsc (const double complex radians)
Return the Cosecant (csc(x) == 1/sin(x))
Definition at line 3071 of file mathfunc.c.
References I_DOUBLE.
float complex ccscf (const float complex radians)
Return the Cosecant (csc(x) == 1/sin(x))
Definition at line 3425 of file mathfunc.c.
References I_FLOAT.
double complex ccsch (const double complex radians)
Return the Hyperbolic Cosecant (csch(x) == 1/sinh(x))
Definition at line 3065 of file mathfunc.c.
References I_DOUBLE.
float complex ccschf (const float complex radians)
Return the Hyperbolic Cosecant (csch(x) == 1/sinh(x))
Definition at line 3419 of file mathfunc.c.
References I_FLOAT.
long double complex ccschl (const long double complex radians)
Return the Hyperbolic Cosecant (csch(x) == 1/sinh(x))
Definition at line 3242 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex ccscl (const long double complex radians)
Return the Cosecant (csc(x) == 1/sin(x))
Definition at line 3248 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex cexcot (const double complex radians)
Return the External Cotangent [excot(x) == (1/tan(x))-1 == cot(x)-1]
Definition at line 3548 of file mathfunc.c.
References I_DOUBLE.
float complex cexcotf (const float complex radians)
Return the External Cotangent [excot(x) == (1/tan(x))-1 == cot(x)-1]
Definition at line 3698 of file mathfunc.c.
References I_FLOAT.
double complex cexcoth (const double complex radians)
Return the External Hyperbolic Cotangent [excoth(x) == (1/tanh(x)-1)]
Definition at line 3542 of file mathfunc.c.
References I_DOUBLE.
float complex cexcothf (const float complex radians)
Return the External Hyperbolic Cotangent [excoth(x) == (1/tanh(x)-1)]
Definition at line 3692 of file mathfunc.c.
References I_FLOAT.
long double complex cexcothl (const long double complex radians)
Return the External Hyperbolic Cotangent [excoth(x) == (1/tanh(x)-1)]
Definition at line 3617 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex cexcotl (const long double complex radians)
Return the External Cotangent [excot(x) == (1/tan(x))-1 == cot(x)-1]
Definition at line 3623 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex cexcsc (const double complex radians)
Return the External Cosecant [excsc(x) == (1/sin(x))-1 == csc(x)-1]
Definition at line 3572 of file mathfunc.c.
References I_DOUBLE.
float complex cexcscf (const float complex radians)
Return the External Cosecant [excsc(x) == (1/sin(x))-1 == csc(x)-1]
Definition at line 3722 of file mathfunc.c.
References I_FLOAT.
double complex cexcsch (const double complex radians)
Return the External Hyperbolic Cosecant [excsch(x) == (1/sinh(x)-1)]
Definition at line 3566 of file mathfunc.c.
References I_DOUBLE.
float complex cexcschf (const float complex radians)
Return the External Hyperbolic Cosecant [excsch(x) == (1/sinh(x)-1)]
Definition at line 3716 of file mathfunc.c.
References I_FLOAT.
long double complex cexcschl (const long double complex radians)
Return the External Hyperbolic Cosecant [excsch(x) == (1/sinh(x)-1)]
Definition at line 3641 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex cexcscl (const long double complex radians)
Return the External Cosecant [excsc(x) == (1/sin(x))-1 == csc(x)-1]
Definition at line 3647 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex cexsec (const double complex radians)
Return the External Secant [exsec(x) == (1/cos(x))-1 == sec(x)-1]
Definition at line 3596 of file mathfunc.c.
References I_DOUBLE.
float complex cexsecf (const float complex radians)
Return the External Secant [exsec(x) == (1/cos(x))-1 == sec(x)-1]
Definition at line 3746 of file mathfunc.c.
References I_FLOAT.
double complex cexsech (const double complex radians)
Return the External Hyperbolic Secant [exsech(x) == (1/cosh(x)-1)]
Definition at line 3590 of file mathfunc.c.
References I_DOUBLE.
float complex cexsechf (const float complex radians)
Return the External Hyperbolic Secant [exsech(x) == (1/cosh(x)-1)]
Definition at line 3740 of file mathfunc.c.
References I_FLOAT.
long double complex cexsechl (const long double complex radians)
Return the External Hyperbolic Secant [exsech(x) == (1/cosh(x)-1)]
Definition at line 3665 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex cexsecl (const long double complex radians)
Return the External Secant [exsec(x) == (1/cos(x))-1 == sec(x)-1]
Definition at line 3671 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex chacoversin (const double complex radians)
Return the Hacoversine (hacoversin(x) == 0.5*(1 - sin(x)))
Definition at line 3167 of file mathfunc.c.
References I_DOUBLE.
float complex chacoversinf (const float complex radians)
Return the Hacoversine (hacoversin(x) == 0.5*(1 - sin(x)))
Definition at line 3521 of file mathfunc.c.
References I_FLOAT.
long double complex chacoversinl (const long double complex radians)
Return the Hacoversine (hacoversin(x) == 0.5*(1 - sin(x)))
Definition at line 3344 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex chaversin (const double complex radians)
Return the Haversine (haversin(x) == 0.5*(1 - cos(x)))
Definition at line 3161 of file mathfunc.c.
References I_DOUBLE.
float complex chaversinf (const float complex radians)
Return the Haversine (haversin(x) == 0.5*(1 - cos(x)))
Definition at line 3515 of file mathfunc.c.
References I_FLOAT.
long double complex chaversinl (const long double complex radians)
Return the Haversine (haversin(x) == 0.5*(1 - cos(x)))
Definition at line 3338 of file mathfunc.c.
References I_LONG_DOUBLE.
ullint clearlsb (ullint num)
Clear least significant bit
Definition at line 4376 of file mathfunc.c.
References ullint.
double complement_angle_deg (const double angle)
Return the complement of an angle (all in degrees)
Definition at line 110 of file mathfunc.c.
float complement_angle_degf (const float angle)
Return the complement of an angle (all in degrees)
Definition at line 122 of file mathfunc.c.
long double complement_angle_degl (const long double angle)
Return the complement of an angle (all in degrees)
Definition at line 116 of file mathfunc.c.
double complex conjugate (const double complex num)
Return the conjugate of a complex number
Definition at line 3836 of file mathfunc.c.
References I_DOUBLE.
float complex conjugatef (const float complex num)
Return the conjugate of a complex number
Definition at line 3848 of file mathfunc.c.
References I_FLOAT.
long double complex conjugatel (const long double complex num)
Return the conjugate of a complex number
Definition at line 3842 of file mathfunc.c.
References I_LONG_DOUBLE.
double cos_arcsin (const double radians)
Return the Cosine of an Arc-Sine [sqrt(1-(x*x))]
Definition at line 2191 of file mathfunc.c.
References squareroot().
float cos_arcsinf (const float radians)
Return the Cosine of an Arc-Sine [sqrt(1-(x*x))]
Definition at line 2218 of file mathfunc.c.
References squarerootf().
long double cos_arcsinl (const long double radians)
Return the Cosine of an Arc-Sine [sqrt(1-(x*x))]
Definition at line 2245 of file mathfunc.c.
References squarerootl().
double cos_arctan (const double radians)
Return the Cosine of an Arc-Tangent [1 / sqrt(1+(x*x))]
Definition at line 2197 of file mathfunc.c.
References squareroot().
float cos_arctanf (const float radians)
Return the Cosine of an Arc-Tangent [1 / sqrt(1+(x*x))]
Definition at line 2224 of file mathfunc.c.
References squarerootf().
long double cos_arctanl (const long double radians)
Return the Cosine of an Arc-Tangent [1 / sqrt(1+(x*x))]
Definition at line 2251 of file mathfunc.c.
References squarerootl().
double cot (const double radians)
Return the Cotangent (cot(x) == 1/tan(x))
Definition at line 1471 of file mathfunc.c.
Referenced by sawtooth2().
float cotf (const float radians)
Return the Cotangent (cot(x) == 1/tan(x))
Definition at line 1825 of file mathfunc.c.
double coth (const double radians)
Return the Hyperbolic Cotangent (coth(x) == 1/tanh(x))
Definition at line 1465 of file mathfunc.c.
float cothf (const float radians)
Return the Hyperbolic Cotangent (coth(x) == 1/tanh(x))
Definition at line 1819 of file mathfunc.c.
long double cothl (const long double radians)
Return the Hyperbolic Cotangent (coth(x) == 1/tanh(x))
Definition at line 1642 of file mathfunc.c.
long double cotl (const long double radians)
Return the Cotangent (cot(x) == 1/tan(x))
Definition at line 1648 of file mathfunc.c.
double crd (const double radians)
Return the Chord
Definition at line 1435 of file mathfunc.c.
float crdf (const float radians)
Return the Chord
Definition at line 1789 of file mathfunc.c.
long double crdl (const long double radians)
Return the Chord
Definition at line 1612 of file mathfunc.c.
double csc (const double radians)
Return the Cosecant (csc(x) == 1/sin(x))
Definition at line 1507 of file mathfunc.c.
float cscf (const float radians)
Return the Cosecant (csc(x) == 1/sin(x))
Definition at line 1861 of file mathfunc.c.
double csch (const double radians)
Return the Hyperbolic Cosecant (csch(x) == 1/sinh(x))
Definition at line 1501 of file mathfunc.c.
float cschf (const float radians)
Return the Hyperbolic Cosecant (csch(x) == 1/sinh(x))
Definition at line 1855 of file mathfunc.c.
long double cschl (const long double radians)
Return the Hyperbolic Cosecant (csch(x) == 1/sinh(x))
Definition at line 1678 of file mathfunc.c.
long double cscl (const long double radians)
Return the Cosecant (csc(x) == 1/sin(x))
Definition at line 1684 of file mathfunc.c.
double complex csec (const double complex radians)
Return the Secant (sec(x) == 1/cos(x))
Definition at line 3107 of file mathfunc.c.
References I_DOUBLE.
float complex csecf (const float complex radians)
Return the Secant (sec(x) == 1/cos(x))
Definition at line 3461 of file mathfunc.c.
References I_FLOAT.
double complex csech (const double complex radians)
Return the Hyperbolic Secant (sech(x) == 1/cosh(x))
Definition at line 3101 of file mathfunc.c.
References I_DOUBLE.
float complex csechf (const float complex radians)
Return the Hyperbolic Secant (sech(x) == 1/cosh(x))
Definition at line 3455 of file mathfunc.c.
References I_FLOAT.
long double complex csechl (const long double complex radians)
Return the Hyperbolic Secant (sech(x) == 1/cosh(x))
Definition at line 3278 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex csecl (const long double complex radians)
Return the Secant (sec(x) == 1/cos(x))
Definition at line 3284 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex csin_arcsec (const double complex radians)
Return the Sine of an Arc-Tangent [sqrt((x*x)-1)/x]
Definition at line 3767 of file mathfunc.c.
References I_DOUBLE.
float complex csin_arcsecf (const float complex radians)
Return the Sine of an Arc-Tangent [sqrt((x*x)-1)/x]
Definition at line 3821 of file mathfunc.c.
References I_FLOAT.
long double complex csin_arcsecl (const long double complex radians)
Return the Sine of an Arc-Tangent [sqrt((x*x)-1)/x]
Definition at line 3794 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex csin_arctan (const double complex radians)
Return the Sine of an Arc-Tangent [x / sqrt(1+(x*x))]
Definition at line 3773 of file mathfunc.c.
References I_DOUBLE.
float complex csin_arctanf (const float complex radians)
Return the Sine of an Arc-Tangent [x / sqrt(1+(x*x))]
Definition at line 3827 of file mathfunc.c.
References I_FLOAT.
long double complex csin_arctanl (const long double complex radians)
Return the Sine of an Arc-Tangent [x / sqrt(1+(x*x))]
Definition at line 3800 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex cvercos (const double complex radians)
Return the Versed Cosine (vercos(x) == 1 - sin(x))
Definition at line 3155 of file mathfunc.c.
References I_DOUBLE.
float complex cvercosf (const float complex radians)
Return the Versed Cosine (vercos(x) == 1 - sin(x))
Definition at line 3509 of file mathfunc.c.
References I_FLOAT.
double complex cvercosh (const double complex radians)
Return the Hyperbolic Versed Cosine (vercosh(x) == 1 - sinh(x))
Definition at line 3149 of file mathfunc.c.
References I_DOUBLE.
float complex cvercoshf (const float complex radians)
Return the Hyperbolic Versed Cosine (vercosh(x) == 1 - sinh(x))
Definition at line 3503 of file mathfunc.c.
References I_FLOAT.
long double complex cvercoshl (const long double complex radians)
Return the Hyperbolic Versed Cosine (vercosh(x) == 1 - sinh(x))
Definition at line 3326 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex cvercosl (const long double complex radians)
Return the Versed Cosine (vercos(x) == 1 - sin(x))
Definition at line 3332 of file mathfunc.c.
References I_LONG_DOUBLE.
double complex cversin (const double complex radians)
Return the Versed Sine (versin(x) == 1 - cos(x))
Definition at line 3131 of file mathfunc.c.
References I_DOUBLE.
float complex cversinf (const float complex radians)
Return the Versed Sine (versin(x) == 1 - cos(x))
Definition at line 3485 of file mathfunc.c.
References I_FLOAT.
double complex cversinh (const double complex radians)
Return the Hyperbolic Versed Sine (versinh(x) == 1 - cosh(x))
Definition at line 3125 of file mathfunc.c.
References I_DOUBLE.
float complex cversinhf (const float complex radians)
Return the Hyperbolic Versed Sine (versinh(x) == 1 - cosh(x))
Definition at line 3479 of file mathfunc.c.
References I_FLOAT.
long double complex cversinhl (const long double complex radians)
Return the Hyperbolic Versed Sine (versinh(x) == 1 - cosh(x))
Definition at line 3302 of file mathfunc.c.
References I_LONG_DOUBLE.
long double complex cversinl (const long double complex radians)
Return the Versed Sine (versin(x) == 1 - cos(x))
Definition at line 3308 of file mathfunc.c.
References I_LONG_DOUBLE.
double div_and_mod (const double num1, const double num2)
Return the sum of division and modulus of the two given numbers
Definition at line 4463 of file mathfunc.c.
int div_and_mod_int (const int num1, const int num2)
Return the sum of division and modulus of the two given numbers
Definition at line 4457 of file mathfunc.c.
float div_and_modf (const float num1, const float num2)
Return the sum of division and modulus of the two given numbers
Definition at line 4469 of file mathfunc.c.
ullint doublefactorial (const unsigned int num)
Double Factorial (n!!); return 0 on error
Definition at line 907 of file mathfunc.c.
References ullint.
sllint doublefactoriallonglong (const sllint num)
Double Factorial (n!!); return 0 on error
Definition at line 936 of file mathfunc.c.
References sllint.
Referenced by mathfunc_doublefactorial().
double excot (const double radians)
Return the External Cotangent [excot(x) == (1/tan(x))-1 == cot(x)-1]
Definition at line 1984 of file mathfunc.c.
float excotf (const float radians)
Return the External Cotangent [excot(x) == (1/tan(x))-1 == cot(x)-1]
Definition at line 2134 of file mathfunc.c.
double excoth (const double radians)
Return the External Hyperbolic Cotangent [excoth(x) == (1/tanh(x)-1)]
Definition at line 1978 of file mathfunc.c.
float excothf (const float radians)
Return the External Hyperbolic Cotangent [excoth(x) == (1/tanh(x)-1)]
Definition at line 2128 of file mathfunc.c.
long double excothl (const long double radians)
Return the External Hyperbolic Cotangent [excoth(x) == (1/tanh(x)-1)]
Definition at line 2053 of file mathfunc.c.
long double excotl (const long double radians)
Return the External Cotangent [excot(x) == (1/tan(x))-1 == cot(x)-1]
Definition at line 2059 of file mathfunc.c.
double excsc (const double radians)
Return the External Cosecant [excsc(x) == (1/sin(x))-1 == csc(x)-1]
Definition at line 2008 of file mathfunc.c.
float excscf (const float radians)
Return the External Cosecant [excsc(x) == (1/sin(x))-1 == csc(x)-1]
Definition at line 2158 of file mathfunc.c.
double excsch (const double radians)
Return the External Hyperbolic Cosecant [excsch(x) == (1/sinh(x)-1)]
Definition at line 2002 of file mathfunc.c.
float excschf (const float radians)
Return the External Hyperbolic Cosecant [excsch(x) == (1/sinh(x)-1)]
Definition at line 2152 of file mathfunc.c.
long double excschl (const long double radians)
Return the External Hyperbolic Cosecant [excsch(x) == (1/sinh(x)-1)]
Definition at line 2077 of file mathfunc.c.
long double excscl (const long double radians)
Return the External Cosecant [excsc(x) == (1/sin(x))-1 == csc(x)-1]
Definition at line 2083 of file mathfunc.c.
double exp_minus1 (const double num)
Return base-e minus 1 for the given number
Definition at line 298 of file mathfunc.c.
float exp_minus1f (const float num)
Return base-e minus 1 for the given number
Definition at line 310 of file mathfunc.c.
long double exp_minus1l (const long double num)
Return base-e minus 1 for the given number
Definition at line 322 of file mathfunc.c.
double exsec (const double radians)
Return the External Secant [exsec(x) == (1/cos(x))-1 == sec(x)-1]
Definition at line 2032 of file mathfunc.c.
float exsecf (const float radians)
Return the External Secant [exsec(x) == (1/cos(x))-1 == sec(x)-1]
Definition at line 2182 of file mathfunc.c.
double exsech (const double radians)
Return the External Hyperbolic Secant [exsech(x) == (1/cosh(x)-1)]
Definition at line 2026 of file mathfunc.c.
float exsechf (const float radians)
Return the External Hyperbolic Secant [exsech(x) == (1/cosh(x)-1)]
Definition at line 2176 of file mathfunc.c.
long double exsechl (const long double radians)
Return the External Hyperbolic Secant [exsech(x) == (1/cosh(x)-1)]
Definition at line 2101 of file mathfunc.c.
long double exsecl (const long double radians)
Return the External Secant [exsec(x) == (1/cos(x))-1 == sec(x)-1]
Definition at line 2107 of file mathfunc.c.
ullint factorial (const unsigned int num)
Factorial (n!); return 0 on error
Definition at line 879 of file mathfunc.c.
References ullint.
sllint factoriallonglong (const sllint num)
Factorial (n!); return 0 on error
Definition at line 893 of file mathfunc.c.
References sllint.
Referenced by mathfunc_factorial().
unsigned int fib (const unsigned int num)
Fibonacci Number Generator; return 0 on error
Definition at line 1085 of file mathfunc.c.
double hacoversin (const double radians)
Return the Hacoversine (hacoversin(x) == 0.5*(1 - sin(x)))
Definition at line 1603 of file mathfunc.c.
float hacoversinf (const float radians)
Return the Hacoversine (hacoversin(x) == 0.5*(1 - sin(x)))
Definition at line 1957 of file mathfunc.c.
long double hacoversinl (const long double radians)
Return the Hacoversine (hacoversin(x) == 0.5*(1 - sin(x)))
Definition at line 1780 of file mathfunc.c.
double haversin (const double radians)
Return the Haversine (haversin(x) == 0.5*(1 - cos(x)))
Definition at line 1597 of file mathfunc.c.
float haversinf (const float radians)
Return the Haversine (haversin(x) == 0.5*(1 - cos(x)))
Definition at line 1951 of file mathfunc.c.
long double haversinl (const long double radians)
Return the Haversine (haversin(x) == 0.5*(1 - cos(x)))
Definition at line 1774 of file mathfunc.c.
unsigned int heptagonal_num (const unsigned int num)
Return the Nth Heptagonal Number ((5*(num^2) - 3 * num)/2)
Definition at line 1257 of file mathfunc.c.
sllint heptagonal_numlonglong (const sllint num)
Return the Nth Heptagonal Number ((5*(num^2) - 3 * num)/2)
Definition at line 1269 of file mathfunc.c.
References sllint.
Referenced by mathfunc_heptagonal_num().
ullint heptagonal_numull (const ullint num)
Return the Nth Heptagonal Number ((5*(num^2) - 3 * num)/2)
Definition at line 1263 of file mathfunc.c.
References ullint.
double heptagonal_root (const long num)
Return the Heptagonal root of the given number (((40*num+9)+3)/10)
Definition at line 870 of file mathfunc.c.
References squareroot().
unsigned int hexagonal_num (const unsigned int num)
Return the Nth Hexagonal Number
Definition at line 1227 of file mathfunc.c.
sllint hexagonal_numlonglong (const sllint num)
Return the Nth Hexagonal Number
Definition at line 1241 of file mathfunc.c.
References sllint.
Referenced by mathfunc_hexagonal_num().
ullint hexagonal_numull (const ullint num)
Return the Nth Hexagonal Number
Definition at line 1234 of file mathfunc.c.
References ullint.
double hexagonal_root (const long num)
Return the Hexagonal root of the given number (((8*num+1)+1)/4)
Definition at line 864 of file mathfunc.c.
References squareroot().
double ipow (double num, const int exp)
Fast power function (num^exp)
Definition at line 357 of file mathfunc.c.
int is_double_negative (double num)
Test if the double is negative
Definition at line 2426 of file mathfunc.c.
int is_double_positive (double num)
Test if the double is positive
Definition at line 2440 of file mathfunc.c.
int is_float_negative (float num)
Test if the float is negative
Definition at line 2419 of file mathfunc.c.
int is_float_positive (float num)
Test if the float is positive
Definition at line 2433 of file mathfunc.c.
int iscomposite (const int num)
Test if an int is composite
Definition at line 2813 of file mathfunc.c.
int isdoublesquare (const double num)
Test if a double is a perfect square
Definition at line 2483 of file mathfunc.c.
References squareroot().
Referenced by isdoubletriangular(), and mathfunc_isfloatsquare().
int isdoubletriangular (const double num)
Test if the given number is a Triangular Number
Definition at line 2515 of file mathfunc.c.
References isdoublesquare().
int isfloatsquare (const float num)
Test if a float is a perfect square
Definition at line 2474 of file mathfunc.c.
References squarerootf().
int isheptagonal (const long num)
Test if the given number is a Heptagonal Number
Definition at line 2540 of file mathfunc.c.
References squareroot().
int ishexagonal (const long num)
Test if the given number is a Hexagonal Number
Definition at line 2522 of file mathfunc.c.
References squareroot().
int islongcomposite (const long num)
Test if an long is composite
Definition at line 2871 of file mathfunc.c.
int islongdoublesquare (const long double num)
Test if a long double is a perfect square
Definition at line 2492 of file mathfunc.c.
References squarerootl().
int islonglongcomposite (const long long num)
Test if an long long is composite
Definition at line 2902 of file mathfunc.c.
Referenced by mathfunc_iscomposite().
int islonglongheptagonal (const long long num)
Test if the given number is a Heptagonal Number
Definition at line 2549 of file mathfunc.c.
References squarerootl().
Referenced by mathfunc_isheptagonal().
int islonglonghexagonal (const long long num)
Test if the given number is a Hexagonal Number
Definition at line 2531 of file mathfunc.c.
References squarerootl().
Referenced by mathfunc_ishexagonal().
int islonglongmersennenumber (const long long num)
Test if the given number is a Mersenne Number
Definition at line 2582 of file mathfunc.c.
Referenced by mathfunc_ismersennenumber().
int islonglongmersenneprime (const sllint num)
Test if the given number is a Mersenne Prime
Definition at line 2606 of file mathfunc.c.
References sllint.
Referenced by mathfunc_ismersenneprime().
int islonglongpoweroftwo (const long long num)
Test if the given number is a Power-of-Two
Definition at line 2564 of file mathfunc.c.
Referenced by mathfunc_ispoweroftwo().
int islonglongprime (const long long num)
Test if a long long int is prime
Definition at line 2724 of file mathfunc.c.
Referenced by mathfunc_isprime().
int islonglongsquare (const long long num)
Test if a number is a perfect square
Definition at line 2465 of file mathfunc.c.
References squarerootl().
Referenced by islonglongtriangular(), and mathfunc_issquare().
int islonglongtriangular (const long long num)
Test if the given number is a Triangular Number
Definition at line 2508 of file mathfunc.c.
References islonglongsquare().
Referenced by mathfunc_istriangular().
int islongprime (const long num)
Test if a long int is prime
Definition at line 2695 of file mathfunc.c.
int islongsquare (const long num)
Test if a number is a perfect square
Definition at line 2456 of file mathfunc.c.
References squareroot().
Referenced by istriangular().
int ismersennenumber (const unsigned int num)
Test if the given number is a Mersenne Number
Definition at line 2576 of file mathfunc.c.
int ismersenneprime (const unsigned int num)
Test if the given number is a Mersenne Prime
Definition at line 2588 of file mathfunc.c.
int ispoweroftwo (const unsigned int num)
Test if the given number is a Power-of-Two
Definition at line 2558 of file mathfunc.c.
int isprime (const int num)
Test if a signed int is prime
Definition at line 2633 of file mathfunc.c.
uint16_t isqrt16 (const uint16_t num)
Inverse Square Root of an integer
Definition at line 810 of file mathfunc.c.
uint32_t isqrt32 (const uint32_t num)
Inverse Square Root of an integer
Definition at line 826 of file mathfunc.c.
uint64_t isqrt64 (const uint64_t num)
Inverse Square Root of an integer
Definition at line 842 of file mathfunc.c.
uint8_t isqrt8 (const uint8_t num)
Inverse Square Root of an integer
Definition at line 794 of file mathfunc.c.
int issquare (const int num)
Test if a number is a perfect square
Definition at line 2447 of file mathfunc.c.
References squareroot().
int istriangular (const long num)
Test if the given number is a Triangular Number
Definition at line 2501 of file mathfunc.c.
References islongsquare().
int isulcomposite (const ulint num)
Test if an unsigned long int is composite
Definition at line 2933 of file mathfunc.c.
References ulint.
int isullcomposite (const ullint num)
Test if an unsigned long long int is composite
Definition at line 2963 of file mathfunc.c.
References ullint.
int isullpoweroftwo (const ullint num)
Test if the given number is a Power-of-Two
Definition at line 2570 of file mathfunc.c.
References ullint.
int isullprime (const ullint num)
Test if a unsigned long long int is prime
Definition at line 2783 of file mathfunc.c.
References ullint.
int isulprime (const ulint num)
Test if a unsigned long int is prime
Definition at line 2753 of file mathfunc.c.
References ulint.
int isunsignedcomposite (const unsigned int num)
Test if an unsigned int is composite
Definition at line 2841 of file mathfunc.c.
int isunsignedprime (const unsigned int num)
Test if an unsigned int is prime
Definition at line 2658 of file mathfunc.c.
double lanczos_sum (const double x)
Return the Lanczos Sum for the given number
Definition at line 4475 of file mathfunc.c.
References LANCZOS_DEN_COEFFS__, and LANCZOS_NUM_COEFFS__.
double ln (const double num)
Natural Logarithm
Definition at line 194 of file mathfunc.c.
double lnp1 (const double num)
Natural Logarithm plus 1
Definition at line 200 of file mathfunc.c.
double LOG (const double num)
log function that fixes odd behaviors on some platforms
Definition at line 236 of file mathfunc.c.
double LOG10 (const double num)
log10 function that fixes odd behaviors on some platforms
Definition at line 278 of file mathfunc.c.
double LOG2 (const double num)
log2 function that fixes odd behaviors on some platforms
Definition at line 253 of file mathfunc.c.
References m.
double log_plus1 (const double num)
Return logp1 for the given number
Definition at line 206 of file mathfunc.c.
float log_plus1f (const float num)
Return logp1 for the given number
Definition at line 216 of file mathfunc.c.
long double log_plus1l (const long double num)
Return logp1 for the given number
Definition at line 226 of file mathfunc.c.
unsigned long int longfib (const unsigned long int num)
Fibonacci Number Generator; return 0 on error
Definition at line 1109 of file mathfunc.c.
References ulint.
sllint longlongfib (const sllint num)
Fibonacci Number Generator; return 0 on error
Definition at line 1153 of file mathfunc.c.
References sllint.
double longmean (const slint count, ...)
Return the mean (average) of a set of numbers
Definition at line 2308 of file mathfunc.c.
References slint.
int max (const int count, ...)
Return the largest (maximum) number
Definition at line 2324 of file mathfunc.c.
Referenced by lib.color::rgb2cmyk(), lib.color::rgb2hls(), and lib.color::rgb2hsv().
double maxd (const int count, ...)
Return the largest (maximum) double
Definition at line 2386 of file mathfunc.c.
float maxf (const int count, ...)
Return the largest (maximum) float
Definition at line 2356 of file mathfunc.c.
double mean (const int count, ...)
Return the mean (average) of a set of numbers
Definition at line 2272 of file mathfunc.c.
float meanf (const int count, ...)
Return the mean (average) of a set of numbers
Definition at line 2284 of file mathfunc.c.
long double meanl (const long long int count, ...)
Return the mean (average) of a set of numbers
Definition at line 2296 of file mathfunc.c.
References sllint.
unsigned int mersenne_num (const unsigned int num)
Return the Nth Mersenne Number; return 0 on error
Definition at line 1335 of file mathfunc.c.
sllint mersenne_numlonglong (const sllint num)
Return the Nth Mersenne Number; return 0 on error
Definition at line 1357 of file mathfunc.c.
References sllint.
Referenced by mathfunc_mersenne_num().
ullint mersenne_numull (const ullint num)
Return the Nth Mersenne Number; return 0 on error
Definition at line 1346 of file mathfunc.c.
References ullint.
int min (const int count, ...)
xx
Definition at line 2339 of file mathfunc.c.
Referenced by lib.color::rgb2hls(), lib.color::rgb2hsi(), and lib.color::rgb2hsv().
double mind (const int count, ...)
Return the smallest (minimum) double
Definition at line 2401 of file mathfunc.c.
float minf (const int count, ...)
Return the smallest (minimum) float
Definition at line 2371 of file mathfunc.c.
signed int mod_pow (const signed int base, const signed int exponent, const signed int modulus)
Modulo Exponentiation (B^E % M)
Definition at line 629 of file mathfunc.c.
References lib.electronics::power().
sllint mod_pow_longlong (const sllint base, const sllint exponent, const sllint modulus)
Modulo Exponentiation (B^E % M)
Definition at line 643 of file mathfunc.c.
References lib.electronics::power(), and sllint.
double norm (const double complex x)
Return the norm value of the complex number
Definition at line 3855 of file mathfunc.c.
References squareroot().
float normf (const float complex x)
Return the norm value of the complex number
Definition at line 3875 of file mathfunc.c.
References squarerootf().
long double norml (const long double complex x)
Return the norm value of the complex number
Definition at line 3865 of file mathfunc.c.
References squarerootl().
unsigned int pentatope_num (const unsigned int num)
Return the Nth Pentatope Number
Definition at line 1309 of file mathfunc.c.
sllint pentatope_numlonglong (const sllint num)
Return the Nth Pentatope Number
Definition at line 1321 of file mathfunc.c.
References sllint.
Referenced by mathfunc_pentatope_num().
ullint pentatope_numull (const ullint num)
Return the Nth Pentatope Number
Definition at line 1315 of file mathfunc.c.
References ullint.
double poly (const double x, const size_t n, const double *__restrict__ c)
Generate a Polynomial and then evaluate the equation; if n=4, then c[4]*x^4 + c[3]*x^3 + c[2]*x^2 + c[1]*x + c[0]
Definition at line 4447 of file mathfunc.c.
unsigned long long int pow2 (const unsigned int num)
Return the power of 2^num, where "num" is a positive integer; return 0 on error
Definition at line 334 of file mathfunc.c.
References ullint.
signed long long int pow2_longlong (const signed long long int num)
Return the power of 2^num, where "num" is a positive integer; return 0 on error
Definition at line 345 of file mathfunc.c.
References sllint.
double pow_ten (const signed int num)
Return the power of 10^num (i.e. 10^num=OUTPUT); return 0 on error
Definition at line 374 of file mathfunc.c.
References lib.electronics::power().
Referenced by mathfunc_pow_ten().
unsigned long long int pow_ten_int (const unsigned int num)
Return the power of 10^num, where "num" is a positive integer; return 0 on error
Definition at line 420 of file mathfunc.c.
References lib.electronics::power(), and ullint.
Referenced by mathfunc_pow_ten_int().
unsigned long long int pow_ten_int_fast (const unsigned int num)
Return the power of 10^num ("num" is a positive integer less than 18); return 0 on error
Definition at line 437 of file mathfunc.c.
References ullint.
Referenced by mathfunc_pow_ten_int_fast().
double pow_ten_neg (const signed int num)
Return the power of 10^num for negative exponents (i.e. 10^-num=OUTPUT); return 0 on error
Definition at line 518 of file mathfunc.c.
References lib.electronics::power().
Referenced by mathfunc_pow_ten_neg().
float pow_ten_negf (const signed int num)
Return the power of 10^num for negative exponents (i.e. 10^num=OUTPUT); return 0 on error
Definition at line 537 of file mathfunc.c.
References lib.electronics::power().
long double pow_ten_negl (const slint num)
Return the power of 10^num for negative exponents (i.e. 10^num=OUTPUT); return 0 on error
Definition at line 556 of file mathfunc.c.
References lib.electronics::power(), and slint.
double pow_ten_pos (const unsigned int num)
Return the power of 10^num for positive exponents (i.e. 10^num=OUTPUT); return 0 on error
Definition at line 467 of file mathfunc.c.
References lib.electronics::power().
Referenced by mathfunc_pow_ten_pos().
float pow_ten_posf (const unsigned int num)
Return the power of 10^num for positive exponents (i.e. 10^num=OUTPUT); return 0 on error
Definition at line 484 of file mathfunc.c.
References lib.electronics::power().
long double pow_ten_posl (const unsigned long int num)
Return the power of 10^num for positive exponents (i.e. 10^num=OUTPUT); return 0 on error
Definition at line 501 of file mathfunc.c.
References lib.electronics::power().
long double pow_tenl (const signed int num)
Return the power of 10^num (i.e. 10^num=OUTPUT); return 0 on error
Definition at line 396 of file mathfunc.c.
References lib.electronics::power().
unsigned int pronic (const unsigned int num)
Return the Nth Pronic number
Definition at line 1059 of file mathfunc.c.
sllint proniclonglong (const sllint num)
Return the Nth Pronic number
Definition at line 1071 of file mathfunc.c.
References sllint.
Referenced by mathfunc_pronic().
ullint pronicull (const ullint num)
Return the Nth Pronic number
Definition at line 1065 of file mathfunc.c.
References ullint.
quaternion qadd (const quaternion num1, const quaternion num2)
Add two quaternion numbers
Definition at line 3923 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
Referenced by qmid().
quaternion_float qaddf (const quaternion_float num1, const quaternion_float num2)
Add two quaternion numbers
Definition at line 4077 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
Referenced by qmidf().
quaternion_long_double qaddl (const quaternion_long_double num1, const quaternion_long_double num2)
Add two quaternion numbers
Definition at line 4231 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
Referenced by qmidl().
quaternion qconjugate (const quaternion num)
Return the conjugate of the quaternion number
Definition at line 3911 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
quaternion_float qconjugatef (const quaternion_float num)
Return the conjugate of the quaternion number
Definition at line 4065 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qconjugatel (const quaternion_long_double num)
Return the conjugate of the quaternion number
Definition at line 4219 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion qdiv (const quaternion num1, const quaternion num2)
Divide two quaternion numbers
Definition at line 3945 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, quaternion::R, and squareroot().
Referenced by qversor().
quaternion_float qdivf (const quaternion_float num1, const quaternion_float num2)
Divide two quaternion numbers
Definition at line 4099 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, quaternion_float::R, and squarerootf().
Referenced by qversorf().
quaternion_long_double qdivl (const quaternion_long_double num1, const quaternion_long_double num2)
Divide two quaternion numbers
Definition at line 4253 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, quaternion_long_double::R, and squarerootl().
Referenced by qversorl().
double qgeti (const quaternion num)
Return the imaginary i num of the quaternion number
Definition at line 3893 of file mathfunc.c.
References quaternion::i.
float qgetif (const quaternion_float num)
Return the imaginary i num of the quaternion number
Definition at line 4047 of file mathfunc.c.
References quaternion_float::i.
long double qgetil (const quaternion_long_double num)
Return the imaginary i num of the quaternion number
Definition at line 4201 of file mathfunc.c.
References quaternion_long_double::i.
double qgetj (const quaternion num)
Return the imaginary j num of the quaternion number
Definition at line 3899 of file mathfunc.c.
References quaternion::j.
float qgetjf (const quaternion_float num)
Return the imaginary j num of the quaternion number
Definition at line 4053 of file mathfunc.c.
References quaternion_float::j.
long double qgetjl (const quaternion_long_double num)
Return the imaginary j num of the quaternion number
Definition at line 4207 of file mathfunc.c.
References quaternion_long_double::j.
double qgetk (const quaternion num)
Return the imaginary k num of the quaternion number
Definition at line 3905 of file mathfunc.c.
References quaternion::k.
float qgetkf (const quaternion_float num)
Return the imaginary k num of the quaternion number
Definition at line 4059 of file mathfunc.c.
References quaternion_float::k.
long double qgetkl (const quaternion_long_double num)
Return the imaginary k num of the quaternion number
Definition at line 4213 of file mathfunc.c.
References quaternion_long_double::k.
quaternion qinv (const quaternion qnum)
Inverse quaternion
Definition at line 3957 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
void qinv_inplace (quaternion qnum)
Inverse quaternion (in-place)
Definition at line 3964 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
void qinv_inplacef (quaternion_float qnum)
Inverse quaternion (in-place)
Definition at line 4118 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
void qinv_inplacel (quaternion_long_double qnum)
Inverse quaternion (in-place)
Definition at line 4272 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion_float qinvf (const quaternion_float qnum)
Inverse quaternion
Definition at line 4111 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qinvl (const quaternion_long_double qnum)
Inverse quaternion
Definition at line 4265 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
double qlen (const quaternion num)
Return the length of a quaternion
Definition at line 3989 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, quaternion::R, and squareroot().
Referenced by qmid().
float qlenf (const quaternion_float num)
Return the length of a quaternion
Definition at line 4143 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, quaternion_float::R, and squarerootf().
Referenced by qmidf().
long double qlenl (const quaternion_long_double num)
Return the length of a quaternion
Definition at line 4297 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, quaternion_long_double::R, and squarerootl().
Referenced by qmidl().
quaternion qmid (const quaternion num1, const quaternion num2)
Return the mid-point of two quaternions
Definition at line 3995 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, qadd(), qlen(), and quaternion::R.
Referenced by qsqrt().
quaternion_float qmidf (const quaternion_float num1, const quaternion_float num2)
Return the mid-point of two quaternions
Definition at line 4149 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, qaddf(), qlenf(), and quaternion_float::R.
Referenced by qsqrtf().
quaternion_long_double qmidl (const quaternion_long_double num1, const quaternion_long_double num2)
Return the mid-point of two quaternions
Definition at line 4303 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, qaddl(), qlenl(), and quaternion_long_double::R.
Referenced by qsqrtl().
quaternion qmul (const quaternion num1, const quaternion num2)
Multiply two quaternion numbers
Definition at line 3935 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
quaternion_float qmulf (const quaternion_float num1, const quaternion_float num2)
Multiply two quaternion numbers
Definition at line 4089 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qmull (const quaternion_long_double num1, const quaternion_long_double num2)
Multiply two quaternion numbers
Definition at line 4243 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion qneg (const quaternion qnum)
Return the negative quaternion
Definition at line 3974 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
void qneg_inplace (quaternion qnum)
Negate quaternion (in-place)
Definition at line 3980 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
void qneg_inplacef (quaternion_float qnum)
Negate quaternion (in-place)
Definition at line 4134 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
void qneg_inplacel (quaternion_long_double qnum)
Negate quaternion (in-place)
Definition at line 4288 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion_float qnegf (const quaternion_float qnum)
Return the negative quaternion
Definition at line 4128 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qnegl (const quaternion_long_double qnum)
Return the negative quaternion
Definition at line 4282 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
double qnorm (const quaternion num)
Return the norm value of the quaternion number
Definition at line 3917 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, quaternion::R, and squareroot().
float qnormf (const quaternion_float num)
Return the norm value of the quaternion number
Definition at line 4071 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, quaternion_float::R, and squarerootf().
long double qnorml (const quaternion_long_double num)
Return the norm value of the quaternion number
Definition at line 4225 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, quaternion_long_double::R, and squarerootl().
double qreal (const quaternion num)
Return the real number from the quaternion number
Definition at line 3887 of file mathfunc.c.
References quaternion::R.
float qrealf (const quaternion_float num)
Return the real number from the quaternion number
Definition at line 4041 of file mathfunc.c.
References quaternion_float::R.
long double qreall (const quaternion_long_double num)
Return the real number from the quaternion number
Definition at line 4195 of file mathfunc.c.
References quaternion_long_double::R.
quaternion qscalar (const quaternion num)
Return the scalar portion of the quaternion number
Definition at line 4020 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
quaternion_float qscalarf (const quaternion_float num)
Return the scalar portion of the quaternion number
Definition at line 4174 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qscalarl (const quaternion_long_double num)
Return the scalar portion of the quaternion number
Definition at line 4328 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion qsqrt (const quaternion num)
Return the squareroot of a quaternion
Definition at line 4014 of file mathfunc.c.
References qmid().
quaternion_float qsqrtf (const quaternion_float num)
Return the squareroot of a quaternion
Definition at line 4168 of file mathfunc.c.
References qmidf().
quaternion_long_double qsqrtl (const quaternion_long_double num)
Return the squareroot of a quaternion
Definition at line 4322 of file mathfunc.c.
References qmidl().
quaternion qsub (const quaternion num1, const quaternion num2)
Subtract two quaternion numbers
Definition at line 3929 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
quaternion_float qsubf (const quaternion_float num1, const quaternion_float num2)
Subtract two quaternion numbers
Definition at line 4083 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qsubl (const quaternion_long_double num1, const quaternion_long_double num2)
Subtract two quaternion numbers
Definition at line 4237 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
ullint quadfactorial (const unsigned int num)
Quadruple Factorial - (2n)!/n!; return 0 on error
Definition at line 966 of file mathfunc.c.
References ullint.
sllint quadfactoriallonglong (const sllint num)
Quadruple Factorial - (2n)!/n!; return 0 on error
Definition at line 982 of file mathfunc.c.
References sllint.
Referenced by mathfunc_quadfactorial().
quaternion qvector (const quaternion num)
Return the vector portion of the quaternion number
Definition at line 4027 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
quaternion_float qvectorf (const quaternion_float num)
Return the vector portion of the quaternion number
Definition at line 4181 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qvectorl (const quaternion_long_double num)
Return the vector portion of the quaternion number
Definition at line 4335 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion qversor (const quaternion num)
Return the versor the quaternion number
Definition at line 4034 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, qdiv(), and quaternion::R.
quaternion_float qversorf (const quaternion_float num)
Return the versor the quaternion number
Definition at line 4188 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, qdivf(), and quaternion_float::R.
quaternion_long_double qversorl (const quaternion_long_double num)
Return the versor the quaternion number
Definition at line 4342 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, qdivl(), and quaternion_long_double::R.
double retint (const double x)
Return rounded double (Return like Integer)
Definition at line 4441 of file mathfunc.c.
double sawtooth (const double x)
Sawtooth-Wave function
Definition at line 161 of file mathfunc.c.
double sawtooth2 (const double x, const double period, const double amplitude)
Advanced Sawtooth-Wave function (set period and amplitude)
Definition at line 167 of file mathfunc.c.
References cot(), and PI.
double sec (const double radians)
Return the Secant (sec(x) == 1/cos(x))
Definition at line 1543 of file mathfunc.c.
float secf (const float radians)
Return the Secant (sec(x) == 1/cos(x))
Definition at line 1897 of file mathfunc.c.
double sech (const double radians)
Return the Hyperbolic Secant (sech(x) == 1/cosh(x))
Definition at line 1537 of file mathfunc.c.
float sechf (const float radians)
Return the Hyperbolic Secant (sech(x) == 1/cosh(x))
Definition at line 1891 of file mathfunc.c.
long double sechl (const long double radians)
Return the Hyperbolic Secant (sech(x) == 1/cosh(x))
Definition at line 1714 of file mathfunc.c.
long double secl (const long double radians)
Return the Secant (sec(x) == 1/cos(x))
Definition at line 1720 of file mathfunc.c.
double sgn (const double num)
Signum function - extract sign
Definition at line 4390 of file mathfunc.c.
Referenced by squarewave().
signed int sgn_int (const signed int num)
Signum function - extract sign
Definition at line 4382 of file mathfunc.c.
float sgnf (const float num)
Signum function - extract sign
Definition at line 4398 of file mathfunc.c.
long double sgnl (const long double num)
Signum function - extract sign
Definition at line 4406 of file mathfunc.c.
double sigmoid (const double x)
Sigmoid-Curve function
Definition at line 173 of file mathfunc.c.
References E.
double signed_pow (const signed int base, const signed int exponent)
Return the power of base^exponent
Definition at line 589 of file mathfunc.c.
References lib.electronics::power().
long double signed_powl (const slint base, const slint exponent)
Return the power of base^exponent
Definition at line 609 of file mathfunc.c.
References lib.electronics::power(), and slint.
double sin_arcsec (const double radians)
Return the Sine of an Arc-Tangent [sqrt((x*x)-1)/x]
Definition at line 2203 of file mathfunc.c.
References squareroot().
float sin_arcsecf (const float radians)
Return the Sine of an Arc-Tangent [sqrt((x*x)-1)/x]
Definition at line 2230 of file mathfunc.c.
References squarerootf().
long double sin_arcsecl (const long double radians)
Return the Sine of an Arc-Tangent [sqrt((x*x)-1)/x]
Definition at line 2257 of file mathfunc.c.
References squarerootl().
double sin_arctan (const double radians)
Return the Sine of an Arc-Tangent [x / sqrt(1+(x*x))]
Definition at line 2209 of file mathfunc.c.
References squareroot().
float sin_arctanf (const float radians)
Return the Sine of an Arc-Tangent [x / sqrt(1+(x*x))]
Definition at line 2236 of file mathfunc.c.
References squarerootf().
long double sin_arctanl (const long double radians)
Return the Sine of an Arc-Tangent [x / sqrt(1+(x*x))]
Definition at line 2263 of file mathfunc.c.
References squarerootl().
double sin_wave_equation (const double amplitude, const double angle)
Return the y coordinate for a given angle (radians)
Definition at line 155 of file mathfunc.c.
double sinpi (const double num)
Return the Pi Sine of the given number; return 0.0 on error
Definition at line 1405 of file mathfunc.c.
References PI, and slint.
Referenced by mathfunc_sinpi().
uint8_t sqrt16 (const uint16_t num)
Approximate square root of an integer
Definition at line 758 of file mathfunc.c.
uint16_t sqrt32 (const uint32_t num)
Approximate square root of an integer
Definition at line 770 of file mathfunc.c.
uint32_t sqrt64 (const uint64_t num)
Approximate square root of an integer
Definition at line 782 of file mathfunc.c.
ullint sqrtull (const ullint num)
Approximate (and rounded) square-root of an unsigned long long int
Definition at line 660 of file mathfunc.c.
References ullint.
static double squareroot (const double num)
Return the Square-Root of a positive number (Limit: 1000000000000000.0)
Private Function: Returns the Square-Root of a positive number (Limit: 1000000000000000.0)
Definition at line 671 of file mathfunc.c.
Referenced by cos_arcsin(), cos_arctan(), heptagonal_root(), hexagonal_root(), isdoublesquare(), isheptagonal(), ishexagonal(), islongsquare(), issquare(), norm(), qdiv(), qlen(), qnorm(), sin_arcsec(), sin_arctan(), and triangular_root().
float squarerootf (const float num)
Return the Square-Root of a positive number (Limit: 1000000000.0)
Definition at line 700 of file mathfunc.c.
Referenced by cos_arcsinf(), cos_arctanf(), isfloatsquare(), normf(), qdivf(), qlenf(), qnormf(), sin_arcsecf(), and sin_arctanf().
long double squarerootl (const long double num)
Return the Square-Root of a positive number
Definition at line 729 of file mathfunc.c.
Referenced by cos_arcsinl(), cos_arctanl(), islongdoublesquare(), islonglongheptagonal(), islonglonghexagonal(), islonglongsquare(), norml(), qdivl(), qlenl(), qnorml(), sin_arcsecl(), and sin_arctanl().
double squarewave (const double x)
Square-Wave function
Definition at line 179 of file mathfunc.c.
References sgn().
ullint superfactorial (const unsigned int num)
Super-Factorial; return 0 on error
Definition at line 1001 of file mathfunc.c.
References ullint.
sllint superfactoriallonglong (const sllint num)
Super-Factorial; return 0 on error
Definition at line 1015 of file mathfunc.c.
Referenced by mathfunc_superfactorial().
double supplement_angle_deg (const double angle)
Return the supplement of an angle (all in degrees)
Definition at line 128 of file mathfunc.c.
float supplement_angle_degf (const float angle)
Return the supplement of an angle (all in degrees)
Definition at line 140 of file mathfunc.c.
long double supplement_angle_degl (const long double angle)
Return the supplement of an angle (all in degrees)
Definition at line 134 of file mathfunc.c.
unsigned int tetrahedral_num (const unsigned int num)
Return the Nth Tetrahedral Number
Definition at line 1283 of file mathfunc.c.
sllint tetrahedral_numlonglong (const sllint num)
Return the Nth Tetrahedral Number
Definition at line 1295 of file mathfunc.c.
References sllint.
Referenced by mathfunc_tetrahedral_num().
ullint tetrahedral_numull (const ullint num)
Return the Nth Tetrahedral Number
Definition at line 1289 of file mathfunc.c.
References ullint.
int trianglewave (const int x)
Triangle-Wave function
Definition at line 185 of file mathfunc.c.
References abs_int().
unsigned int triangular_num (const unsigned int num)
Return the Nth Triangular Number
Definition at line 1201 of file mathfunc.c.
sllint triangular_numlonglong (const sllint num)
Return the Nth Triangular Number
Definition at line 1213 of file mathfunc.c.
References sllint.
Referenced by mathfunc_triangular_num().
ullint triangular_numull (const ullint num)
Return the Nth Triangular Number
Definition at line 1207 of file mathfunc.c.
References ullint.
double triangular_root (const long num)
Return the Triangular root of the given number (((8*num+1)1)/2)
Definition at line 858 of file mathfunc.c.
References squareroot().
int unfactorial (const int num)
Find the number used to produce the factorial
Definition at line 1040 of file mathfunc.c.
uint64_t unfactorial64 (const uint64_t num)
Find the number used to produce the factorial
Definition at line 1048 of file mathfunc.c.
ullint unsigned_pow (const unsigned int base, const unsigned int exponent)
Return the power of base^exponent for positive numbers
Definition at line 575 of file mathfunc.c.
References lib.electronics::power(), and ullint.
double vercos (const double radians)
Return the Versed Cosine (vercos(x) == 1 - sin(x))
Definition at line 1591 of file mathfunc.c.
float vercosf (const float radians)
Return the Versed Cosine (vercos(x) == 1 - sin(x))
Definition at line 1945 of file mathfunc.c.
double vercosh (const double radians)
Return the Hyperbolic Versed Cosine (vercosh(x) == 1 - sinh(x))
Definition at line 1585 of file mathfunc.c.
float vercoshf (const float radians)
Return the Hyperbolic Versed Cosine (vercosh(x) == 1 - sinh(x))
Definition at line 1939 of file mathfunc.c.
long double vercoshl (const long double radians)
Return the Hyperbolic Versed Cosine (vercosh(x) == 1 - sinh(x))
Definition at line 1762 of file mathfunc.c.
long double vercosl (const long double radians)
Return the Versed Cosine (vercos(x) == 1 - sin(x))
Definition at line 1768 of file mathfunc.c.
double versin (const double radians)
Return the Versed Sine (versin(x) == 1 - cos(x))
Definition at line 1567 of file mathfunc.c.
float versinf (const float radians)
Return the Versed Sine (versin(x) == 1 - cos(x))
Definition at line 1921 of file mathfunc.c.
double versinh (const double radians)
Return the Hyperbolic Versed Sine (versinh(x) == 1 - cosh(x))
Definition at line 1561 of file mathfunc.c.
float versinhf (const float radians)
Return the Hyperbolic Versed Sine (versinh(x) == 1 - cosh(x))
Definition at line 1915 of file mathfunc.c.
long double versinhl (const long double radians)
Return the Hyperbolic Versed Sine (versinh(x) == 1 - cosh(x))
Definition at line 1738 of file mathfunc.c.
long double versinl (const long double radians)
Return the Versed Sine (versin(x) == 1 - cos(x))
Definition at line 1744 of file mathfunc.c.
Variable Documentation
static const double LANCZOS_DEN_COEFFS__ static
Initial value:
= {
    0.0,
    39916800.0,
    120543840.0,
    150917976.0,
    105258076.0,
    45995730.0,
    13339535.0,
    2637558.0,
    357423.0,
    32670.0,
    1925.0,
    66.0,
    1.0
}
Private Constant
Definition at line 67 of file mathfunc.c.
Referenced by lanczos_sum().
static const double LANCZOS_NUM_COEFFS__ static
Initial value:
= {
    23531376880.410759688572007674451636754734846804940,
    42919803642.649098768957899047001988850926355848959,
    35711959237.355668049440185451547166705960488635843,
    17921034426.037209699919755754458931112671403265390,
    6039542586.3520280050642916443072979210699388420708,
    1439720407.3117216736632230727949123939715485786772,
    248874557.86205415651146038641322942321632125127801,
    31426415.585400194380614231628318205362874684987640,
    2876370.6289353724412254090516208496135991145378768,
    186056.26539522349504029498971604569928220784236328,
    8071.6720023658162106380029022722506138218516325024,
    210.82427775157934587250973392071336271166969580291,
    2.5066282746310002701649081771338373386264310793408
}
Private Constant
Definition at line 68 of file mathfunc.c.
Referenced by lanczos_sum().