PyBooster: pybooster.color Namespace Reference
pybooster.color Namespace Reference
Color Manipulations.
Functions
def cmy2cmyk
CMY -> CMYK.
def cmy2rgb
CMY -> RG.
def cmyk2cmy
CMYK -> CMY.
def cmyk2rgb
CMYK -> RG.
def cmyk2rgbbyte
CMYK -> RGB byte-array.
def getvalue
Get value from hue.
def hls2hsv
HLS -> HSV.
def hls2rgb
HLS -> RG.
def hsi2rgb
HSI -> RG.
def hsi2rgbbyte
HSI -> RGB byte array.
def hsv2hls
HSV -> HLS.
def hsv2rgb
HSV -> RG.
def html2hex
HTML notation -> hex notation.
def html2rgb
HTML notation (#f6a797) -> RGB (byte array - 0-255)
def huedegree2huefloat
Hue in degrees -> Hue as a float.
def huefloat2huedegree
Hue as a float -> Hue in degrees.
def hunterlab2xyz
Hunter Lab -> XYZ.
def rgb2cmy
RGB -> CMY.
def rgb2cmyk
RGB -> CMYK.
def rgb2hex
RGB (byte array - 0-255) -> hex notation.
def rgb2hls
RGB -> HLS.
def rgb2hsi
RGB -> HSI.
def rgb2hsv
RGB -> HSV.
def rgb2html
RGB -> HTML notation.
def rgb2rgba
RGB -> RGBA.
def rgb2rgbf
RGB Integer -> RGB Float.
def rgb2xyz
RGB -> XYZ.
def rgb2yiq
RGB -> YIQ.
def rgba2rgb
RGBA -> RG.
def rgbf2rgb
RGB Float -> RGB Intege.
def roundrgb
Round RGB float-points (like 245.649915) to integer (246)
def shorthand2sixdigit
Shorthand HTML notation (#789) -> 6-digit HTML notation (#778899)
def xyz2hunterlab
XYZ -> Hunter La.
def xyz2rgb
XYZ -> RG.
def xyz2rgb_int
XYZ -> RGB as an intege.
def yiq2rgb
YIQ -> RG.
Variables
list __all__
float ONE_SIXTH = 0.166666666666667
float ONE_THIRD = 0.333333333333333
float TWO_THIRD = 0.666666666666667
Detailed Description
Color Manipulations.
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.18
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
The PyBooster Library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Function Documentation
def pybooster.color.cmy2cmyk (_cyan)
CMY -> CMYK.
Definition at line 122 of file color.py.
def pybooster.color.cmy2rgb (_c)
CMY -> RG.
Definition at line 172 of file color.py.
def pybooster.color.cmyk2cmy (_cyan)
CMYK -> CMY.
Definition at line 195 of file color.py.
def pybooster.color.cmyk2rgb (_cyan)
CMYK -> RG.
Definition at line 212 of file color.py.
def pybooster.color.cmyk2rgbbyte (_cyan)
CMYK -> RGB byte-array.
Definition at line 229 of file color.py.
def pybooster.color.getvalue (m1)
Get value from hue.
Definition at line 107 of file color.py.
Referenced by pybooster.color.hls2rgb().
def pybooster.color.hls2hsv (hue)
HLS -> HSV.
Definition at line 600 of file color.py.
def pybooster.color.hls2rgb (h)
HLS -> RG.
Definition at line 615 of file color.py.
References pybooster.color.getvalue().
def pybooster.color.hsi2rgb (_hue)
HSI -> RG.
Definition at line 249 of file color.py.
def pybooster.color.hsi2rgbbyte (_hue)
HSI -> RGB byte array.
Definition at line 423 of file color.py.
def pybooster.color.hsv2hls (_hue)
HSV -> HLS.
Definition at line 630 of file color.py.
def pybooster.color.hsv2rgb (h)
HSV -> RG.
Definition at line 649 of file color.py.
def pybooster.color.html2hex (_html)
HTML notation -> hex notation.
Definition at line 689 of file color.py.
def pybooster.color.html2rgb (_html)
HTML notation (#f6a797) -> RGB (byte array - 0-255)
Definition at line 706 of file color.py.
def pybooster.color.huedegree2huefloat (_hue)
Hue in degrees -> Hue as a float.
Definition at line 676 of file color.py.
def pybooster.color.huefloat2huedegree (_hue)
Hue as a float -> Hue in degrees.
Definition at line 681 of file color.py.
def pybooster.color.hunterlab2xyz (_hl)
Hunter Lab -> XYZ.
Definition at line 757 of file color.py.
def pybooster.color.rgb2cmy (_red, _green, _blue, _float)
RGB -> CMY.
Definition at line 789 of file color.py.
def pybooster.color.rgb2cmyk (r)
RGB -> CMYK.
Definition at line 823 of file color.py.
References max().
def pybooster.color.rgb2hex (r)
RGB (byte array - 0-255) -> hex notation.
Definition at line 844 of file color.py.
def pybooster.color.rgb2hls (r)
RGB -> HLS.
Definition at line 858 of file color.py.
References max(), and min().
def pybooster.color.rgb2hsi (_red)
RGB -> HSI.
Definition at line 880 of file color.py.
References min().
def pybooster.color.rgb2hsv (_red)
RGB -> HSV.
Definition at line 986 of file color.py.
References max(), and min().
def pybooster.color.rgb2html (_red)
RGB -> HTML notation.
Definition at line 1026 of file color.py.
def pybooster.color.rgb2rgba (_red)
RGB -> RGBA.
Definition at line 1139 of file color.py.
def pybooster.color.rgb2rgbf (_red)
RGB Integer -> RGB Float.
Definition at line 1155 of file color.py.
def pybooster.color.rgb2xyz (_red)
RGB -> XYZ.
Definition at line 1047 of file color.py.
def pybooster.color.rgb2yiq (_red)
RGB -> YIQ.
Definition at line 1119 of file color.py.
def pybooster.color.rgba2rgb (_red)
RGBA -> RG.
Definition at line 1147 of file color.py.
def pybooster.color.rgbf2rgb (_red)
RGB Float -> RGB Intege.
Definition at line 1160 of file color.py.
def pybooster.color.roundrgb (_r)
Round RGB float-points (like 245.649915) to integer (246)
Definition at line 1165 of file color.py.
def pybooster.color.shorthand2sixdigit (_shorthand)
Shorthand HTML notation (#789) -> 6-digit HTML notation (#778899)
Definition at line 723 of file color.py.
def pybooster.color.xyz2hunterlab (_x)
XYZ -> Hunter La.
Definition at line 1173 of file color.py.
def pybooster.color.xyz2rgb (_x)
XYZ -> RG.
Definition at line 1191 of file color.py.
def pybooster.color.xyz2rgb_int (_x)
XYZ -> RGB as an intege.
Definition at line 1250 of file color.py.
def pybooster.color.yiq2rgb (_y)
YIQ -> RG.
Definition at line 1312 of file color.py.
Variable Documentation
list __all__
Initial value:
 = [
     # CONSTANTS
     'ONE_THIRD',
     'ONE_SIXTH',
     'TWO_THIRD',
     # FUNCTIONS
     # CMY
     'cmy2cmyk',
     'cmy2rgb',
     # CMYK
     'cmyk2cmy',
     'cmyk2rgb',
     'cmyk2rgbbyte',
     # GETVALUE
     'getvalue',
     # HSI
     'hsi2rgb',
     'hsi2rgbbyte',
     # HLS
     'hls2hsv',
     'hls2rgb',
     # HSV
     'hsv2hls',
     'hsv2rgb',
     # HUE
     'huedegree2huefloat',
     'huefloat2huedegree',
     # HTML
     'html2hex',
     'html2rgb',
     'shorthand2sixdigit',
     # HUNTERLAB
     'hunterlab2xyz',
     # RGB
     'rgb2cmy',
     'rgb2cmyk',
     'rgb2hex',
     'rgb2hls',
     'rgb2hsi',
     'rgb2hsv',
     'rgb2html',
     'rgb2xyz',
     'rgb2yiq',
     'rgb2rgba',
     'rgba2rgb',
     'rgb2rgbf',
     'rgbf2rgb',
     # ROUND
     'roundrgb',
     # XYZ
     'xyz2hunterlab',
     'xyz2rgb',
     'xyz2rgb_int',
     # YIQ
     'yiq2rgb',
 ]
Definition at line 37 of file color.py.
float ONE_SIXTH = 0.166666666666667
Definition at line 99 of file color.py.
float ONE_THIRD = 0.333333333333333
Definition at line 98 of file color.py.
float TWO_THIRD = 0.666666666666667
Definition at line 100 of file color.py.