PyBooster: lib.color Namespace Reference
lib.color Namespace Reference
Functions
def cmy2cmyk
def cmy2rgb
def cmyk2cmy
def cmyk2rgb
def cmyk2rgbbyte
def getvalue
def hls2hsv
def hls2rgb
def hsi2rgb
def hsi2rgbbyte
def hsv2hls
def hsv2rgb
def html2hex
def html2rgb
def huedegree2huefloat
def huefloat2huedegree
def hunterlab2xyz
def rgb2cmy
def rgb2cmyk
def rgb2hex
def rgb2hls
def rgb2hsi
def rgb2hsv
def rgb2html
def rgb2rgba
def rgb2rgbf
def rgb2xyz
def rgb2yiq
def rgba2rgb
def rgbf2rgb
def roundrgb
def shorthand2sixdigit
def xyz2hunterlab
def xyz2rgb
def xyz2rgb_int
def yiq2rgb
Variables
list __all__
float ONE_SIXTH = 0.166666666666667
float ONE_THIRD = 0.333333333333333
float TWO_THIRD = 0.666666666666667
Function Documentation
def lib.color.cmy2cmyk (_cyan)
Definition at line 121 of file color.py.
def lib.color.cmy2rgb (_c)
Definition at line 141 of file color.py.
def lib.color.cmyk2cmy (_cyan)
Definition at line 155 of file color.py.
def lib.color.cmyk2rgb (_cyan)
Definition at line 163 of file color.py.
def lib.color.cmyk2rgbbyte (_cyan)
Definition at line 171 of file color.py.
def lib.color.getvalue (m1)
Definition at line 106 of file color.py.
Referenced by lib.color.hls2rgb().
def lib.color.hls2hsv (hue)
Definition at line 293 of file color.py.
def lib.color.hls2rgb (h)
Definition at line 302 of file color.py.
References lib.color.getvalue().
def lib.color.hsi2rgb (_hue)
Definition at line 182 of file color.py.
def lib.color.hsi2rgbbyte (_hue)
Definition at line 236 of file color.py.
def lib.color.hsv2hls (_hue)
Definition at line 317 of file color.py.
def lib.color.hsv2rgb (h)
Definition at line 327 of file color.py.
def lib.color.html2hex (_html)
Definition at line 367 of file color.py.
def lib.color.html2rgb (_html)
Definition at line 375 of file color.py.
def lib.color.huedegree2huefloat (_hue)
Definition at line 354 of file color.py.
def lib.color.huefloat2huedegree (_hue)
Definition at line 359 of file color.py.
def lib.color.hunterlab2xyz (_hl)
Definition at line 399 of file color.py.
def lib.color.rgb2cmy (_red, _green, _blue, _float)
Definition at line 413 of file color.py.
def lib.color.rgb2cmyk (r)
Definition at line 429 of file color.py.
References max().
def lib.color.rgb2hex (r)
Definition at line 438 of file color.py.
def lib.color.rgb2hls (r)
Definition at line 452 of file color.py.
References max(), and min().
def lib.color.rgb2hsi (_red)
Definition at line 474 of file color.py.
References min().
def lib.color.rgb2hsv (_red)
Definition at line 511 of file color.py.
References max(), and min().
def lib.color.rgb2html (_red)
Definition at line 533 of file color.py.
def lib.color.rgb2rgba (_red)
Definition at line 580 of file color.py.
def lib.color.rgb2rgbf (_red)
Definition at line 596 of file color.py.
def lib.color.rgb2xyz (_red)
Definition at line 542 of file color.py.
def lib.color.rgb2yiq (_red)
Definition at line 569 of file color.py.
def lib.color.rgba2rgb (_red)
Definition at line 588 of file color.py.
def lib.color.rgbf2rgb (_red)
Definition at line 601 of file color.py.
def lib.color.roundrgb (_r)
Definition at line 606 of file color.py.
def lib.color.shorthand2sixdigit (_shorthand)
Definition at line 383 of file color.py.
def lib.color.xyz2hunterlab (_x)
Definition at line 614 of file color.py.
def lib.color.xyz2rgb (_x)
Definition at line 623 of file color.py.
def lib.color.xyz2rgb_int (_x)
Definition at line 646 of file color.py.
def lib.color.yiq2rgb (_y)
Definition at line 672 of file color.py.
Variable Documentation
list __all__
Initial value:
 = [
     # CONSTANTS
     'ONE_THIRD',
     'ONE_SIXTH',
     'TWO_THIRD',
     # FUNCTIONS
     # CMY
     'cmy2cmyk',
     'cmy2rgb',
     # CMYK
     'cmyk2cmy',
     'cmyk2rgb',
     'cmyk2rgbbyte',
     # GETVALUE
     'getvalue',
     # HSI
     'hsi2rgb',
     'hsi2rgbbyte',
     # HLS
     'hls2hsv',
     'hls2rgb',
     # HSV
     'hsv2hls',
     'hsv2rgb',
     # HUE
     'huedegree2huefloat',
     'huefloat2huedegree',
     # HTML
     'html2hex',
     'html2rgb',
     'shorthand2sixdigit',
     # HUNTERLAB
     'hunterlab2xyz',
     # RGB
     'rgb2cmy',
     'rgb2cmyk',
     'rgb2hex',
     'rgb2hls',
     'rgb2hsi',
     'rgb2hsv',
     'rgb2html',
     'rgb2xyz',
     'rgb2yiq',
     'rgb2rgba',
     'rgba2rgb',
     'rgb2rgbf',
     'rgbf2rgb',
     # ROUND
     'roundrgb',
     # XYZ
     'xyz2hunterlab',
     'xyz2rgb',
     'xyz2rgb_int',
     # YIQ
     'yiq2rgb',
 ]
Definition at line 37 of file color.py.
float ONE_SIXTH = 0.166666666666667
Definition at line 99 of file color.py.
float ONE_THIRD = 0.333333333333333
Definition at line 98 of file color.py.
float TWO_THIRD = 0.666666666666667
Definition at line 100 of file color.py.