PyBooster: pybooster.pronouns Namespace Reference
pybooster.pronouns Namespace Reference
Pronoun-related functions and constants.
Functions
def pronoun
Swap first and third person pronouns.
def pronoun2
Swap first and second person pronouns.
def pronoun2f
Swap first and second person pronouns and replace spaces with %20.
def pronoun3
Swap second and third person pronouns.
def pronoun3f
Swap second and third person pronouns and replace spaces with %20.
def pronounf
Swap first and third person pronouns and replace spaces with %20.
def swap_genders
Swap gender pronouns.
def swap_pronouns
Swap pronouns.
Variables
list __all__
tuple FIRST_SECOND
tuple FIRST_THIRD
tuple GENDER_SWAP
tuple SECOND_THIRD
Detailed Description
Pronoun-related functions and constants.
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.18
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
The PyBooster Library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Function Documentation
def pybooster.pronouns.pronoun (_str)
Swap first and third person pronouns.
Definition at line 143 of file pronouns.py.
References pybooster.pronouns.swap_pronouns().
def pybooster.pronouns.pronoun2 (_str)
Swap first and second person pronouns.
Definition at line 148 of file pronouns.py.
References pybooster.pronouns.swap_pronouns().
def pybooster.pronouns.pronoun2f (_str)
Swap first and second person pronouns and replace spaces with %20.
Definition at line 163 of file pronouns.py.
References pybooster.pronouns.swap_pronouns().
def pybooster.pronouns.pronoun3 (_str)
Swap second and third person pronouns.
Definition at line 153 of file pronouns.py.
References pybooster.pronouns.swap_pronouns().
def pybooster.pronouns.pronoun3f (_str)
Swap second and third person pronouns and replace spaces with %20.
Definition at line 168 of file pronouns.py.
References pybooster.pronouns.swap_pronouns().
def pybooster.pronouns.pronounf (_str)
Swap first and third person pronouns and replace spaces with %20.
Definition at line 158 of file pronouns.py.
References pybooster.pronouns.swap_pronouns().
def pybooster.pronouns.swap_genders (_str)
Swap gender pronouns.
Definition at line 173 of file pronouns.py.
References pybooster.pronouns.swap_pronouns().
def pybooster.pronouns.swap_pronouns (_str)
Swap pronouns.
Definition at line 119 of file pronouns.py.
Referenced by pybooster.pronouns.pronoun(), pybooster.pronouns.pronoun2(), pybooster.pronouns.pronoun2f(), pybooster.pronouns.pronoun3(), pybooster.pronouns.pronoun3f(), pybooster.pronouns.pronounf(), and pybooster.pronouns.swap_genders().
Variable Documentation
list __all__
Initial value:
 = [
     # CONSTANTS
     'FIRST_THIRD',
     'FIRST_SECOND',
     'SECOND_THIRD',
     'GENDER_SWAP',
     # FUNCTIONS
     'swap_pronouns',
     'pronoun',
     'pronoun2',
     'pronoun3',
     'pronounf',
     'pronoun2f',
     'pronoun3f',
     'swap_genders',
 ]
Definition at line 34 of file pronouns.py.
tuple FIRST_SECOND
Initial value:
 = (
     ('me', 'you'),
     ('you', 'me'),
     ('I', 'you'),
     ('you are', 'I am'),
     ('are you', 'am I'),
     ('your', 'my'),
     ('my', 'your'),
     ('yours', 'mine'),
     ('mine', 'yours'),
     ('you were', 'I was'),
     ('yourself', 'myself'),
     ('myself', 'yourself'),
 )
Definition at line 72 of file pronouns.py.
tuple FIRST_THIRD
Initial value:
 = (
     ('I', 'he or she'),
     ('me', 'him or her'),
     ('mine', 'his or hers'),
     ('my', 'his or her'),
     ('myself', 'him or herself'),
     ('he', 'I'),
     ('she', 'I'),
     ('his', 'mine'),
     ('hers', 'mine'),
     ('himself', 'myself'),
     ('herself', 'myself'),
     ('they', 'we'),
     ('we', 'they'),
 )
Definition at line 55 of file pronouns.py.
tuple GENDER_SWAP
Initial value:
 = (
     (r'him', r'her'),
     (r'her', r'him'),
     (r'he', r'she'),
     (r'she', r'he'),
     (r'his', r'her'),
 )
Definition at line 106 of file pronouns.py.
tuple SECOND_THIRD
Initial value:
 = (
     ('you', 'them'),
     ('them', 'you'),
     ('yours', 'theirs'),
     ('theirs', 'yours'),
     ('yourself', 'themselves'),
     ('themselves', 'yourself'),
     ('you are', 'they are'),
     ('they are', 'you are'),
     ('you were', 'they were'),
     ('they were', 'you were'),
     ('you have', 'they have'),
     ('they have', 'you have'),
     ('you had', 'they had'),
     ('they had', 'you had'),
 )
Definition at line 88 of file pronouns.py.