PyBooster: lib.basic Namespace Reference
lib.basic Namespace Reference
Classes
class NullException
class ObjectError
class SameFileError
Functions
def cache
def char2bitlen
def clearscr ()
def csv2json
def doeskeymvalue
def eny
def evaliter
def execfile
def ezcompile
def finddictkey
def finddictkeys
def getlinenum ()
def getwebpage
def imported ()
def imports ()
def incde
def int2bitlen
def ipygrep
def isbetween
def isbin
def iscomplex (_obj)
def iscomplextype (_obj)
def isdefined
def isexe
def isfrozen ()
def ishex
def isinpath
def isiter
def ismodfrozen
def ismodloaded
def isoct
def isvalidcode
def listkeys
def lsmods ()
def mergestrdict
def modexist
def modpath
def playmusic
def pygrep
def rmdupkey
def rmdupkey_casein
def rmduplist
def rmduplist_frozenset
def rmduplist_set
def rmduplist_tuple
def rmdupval
def rmfalse
def rmmod
def sortlistlong2short
def sortlistshort2long
def wherecurmods ()
def wheremods ()
def wlong (_int32)
def words_in_str
def words_not_in_str
Variables
list __all__
Function Documentation
def lib.basic.cache (_action)
Definition at line 797 of file basic.py.
def lib.basic.char2bitlen (_char)
Definition at line 828 of file basic.py.
References bit_length().
def lib.basic.clearscr (None)
Clear Terminal
Definition at line 711 of file basic.py.
def lib.basic.csv2json (_filepath)
Definition at line 775 of file basic.py.
def lib.basic.doeskeymvalue (_dict)
Definition at line 564 of file basic.py.
def lib.basic.eny (_iter)
Definition at line 152 of file basic.py.
def lib.basic.evaliter (_iter)
Definition at line 147 of file basic.py.
def lib.basic.execfile (_filename)
Definition at line 692 of file basic.py.
def lib.basic.ezcompile (_code)
Definition at line 756 of file basic.py.
def lib.basic.finddictkey (_dict)
Definition at line 541 of file basic.py.
def lib.basic.finddictkeys (_dict)
Definition at line 552 of file basic.py.
def lib.basic.getlinenum (int)
Return the script's line number where this method executes
Definition at line 751 of file basic.py.
def lib.basic.getwebpage (_address)
Definition at line 780 of file basic.py.
def lib.basic.imported (list)
List imports that are in 'modules' and 'globals()'
Definition at line 481 of file basic.py.
def lib.basic.imports (list)
List all imports
Definition at line 472 of file basic.py.
def lib.basic.incde (i)
Definition at line 698 of file basic.py.
def lib.basic.int2bitlen (_int)
Definition at line 823 of file basic.py.
def lib.basic.ipygrep (_find)
Definition at line 717 of file basic.py.
def lib.basic.isbetween (_lo)
Definition at line 315 of file basic.py.
def lib.basic.isbin (_bin)
Definition at line 233 of file basic.py.
def lib.basic.iscomplex (_obj, bool)
Is the object a complex number (37+54j)
>>> iscomplex(37+54j)
True
>>> iscomplex(37-54j)
True
>>> iscomplex(27j)
True
>>> iscomplex("37+54j")
True
>>> iscomplex('37+54j')
True
>>> iscomplex('37-54j')
True
>>> iscomplex(37+0j)
True
>>> iscomplex('37-54J')
False
>>> iscomplex(37)
False
>>> iscomplex('37')
False
Definition at line 259 of file basic.py.
def lib.basic.iscomplextype (_obj, bool)
Is the object a complex type
>>> iscomplextype(37+54j)
True
>>> iscomplextype(37-54j)
True
>>> iscomplextype(27j)
True
>>> iscomplextype(-23j)
True
>>> iscomplextype('37+54j')
False
>>> iscomplextype("37+54j")
False
Definition at line 297 of file basic.py.
def lib.basic.isdefined (_var_name)
Definition at line 335 of file basic.py.
def lib.basic.isexe (fpath)
Definition at line 405 of file basic.py.
def lib.basic.isfrozen (bool)
Test if the modules are built into the interpreter
(As seen in py2exe and others)
Definition at line 349 of file basic.py.
def lib.basic.ishex (_hex)
Definition at line 183 of file basic.py.
def lib.basic.isinpath (program)
Definition at line 419 of file basic.py.
def lib.basic.isiter (_iter)
Definition at line 164 of file basic.py.
def lib.basic.ismodfrozen (module_name)
Definition at line 363 of file basic.py.
def lib.basic.ismodloaded (_module)
Definition at line 342 of file basic.py.
def lib.basic.isoct (_oct)
Definition at line 207 of file basic.py.
def lib.basic.isvalidcode (_code)
Definition at line 450 of file basic.py.
def lib.basic.listkeys (dict1)
Definition at line 624 of file basic.py.
Referenced by lib.basic.mergestrdict().
def lib.basic.lsmods (list)
List loaded modules
Definition at line 467 of file basic.py.
def lib.basic.mergestrdict (dict1)
Definition at line 632 of file basic.py.
References lib.basic.listkeys().
def lib.basic.modexist (_module)
Definition at line 505 of file basic.py.
def lib.basic.modpath (module)
Definition at line 497 of file basic.py.
def lib.basic.playmusic (_file)
Definition at line 737 of file basic.py.
def lib.basic.pygrep (_find)
Definition at line 727 of file basic.py.
def lib.basic.rmdupkey (_dict)
Definition at line 582 of file basic.py.
def lib.basic.rmdupkey_casein (_dict)
Definition at line 596 of file basic.py.
def lib.basic.rmduplist (_list)
Definition at line 657 of file basic.py.
def lib.basic.rmduplist_frozenset (_list)
Definition at line 681 of file basic.py.
def lib.basic.rmduplist_set (_list)
Definition at line 673 of file basic.py.
def lib.basic.rmduplist_tuple (_list)
Definition at line 665 of file basic.py.
def lib.basic.rmdupval (_dict)
Definition at line 612 of file basic.py.
def lib.basic.rmfalse (_iter)
Definition at line 142 of file basic.py.
def lib.basic.rmmod (_modname)
Definition at line 521 of file basic.py.
def lib.basic.sortlistlong2short (_list)
Definition at line 649 of file basic.py.
def lib.basic.sortlistshort2long (_list)
Definition at line 641 of file basic.py.
def lib.basic.wherecurmods (list)
List locations of current/present modules
Definition at line 492 of file basic.py.
def lib.basic.wheremods (list)
List locations of imported modules
Definition at line 486 of file basic.py.
def lib.basic.wlong (_int32, bytes)
Convert a 32-bit integer to little-endian
Definition at line 792 of file basic.py.
def lib.basic.words_in_str (_text)
Definition at line 375 of file basic.py.
def lib.basic.words_not_in_str (_text)
Definition at line 390 of file basic.py.
Variable Documentation
list __all__
Initial value:
 = [
     # CLASSES
     'SameFileError',
     'ObjectError',
     'NullException',
     # BOOLEAN-RELATED FUNCTIONS
     'rmfalse',
     'evaliter',
     'eny',
     'isiter',
     'ishex',
     'isoct',
     'isbin',
     'iscomplex',
     'iscomplextype',
     'isbetween',
     'isdefined',
     'ismodloaded',
     'isfrozen',
     'ismodfrozen',
     'words_in_str',
     'words_not_in_str',
     'isexe',
     'isinpath',
     'isvalidcode',
     # MODULES AND IMPORTS
     'lsmods',
     'imports',
     'imported',
     'wheremods',
     'wherecurmods',
     'modpath',
     'modexist',
     'rmmod',
     # DICTIONARY-RELATED FUNCTIONS
     'finddictkey',
     'finddictkeys',
     'doeskeymvalue',
     'rmdupkey',
     'rmdupkey_casein',
     'rmdupval',
     'listkeys',
     'mergestrdict',
     # LIST-RELATED FUNCTIONS
     'sortlistshort2long',
     'sortlistlong2short',
     'rmduplist',
     'rmduplist_tuple',
     'rmduplist_set',
     'rmduplist_frozenset',
     # MISCELLANEOUS
     'execfile',
     'incde',
     'clearscr',
     'pygrep',
     'ipygrep',
     'playmusic',
     'getlinenum',
     'ezcompile',
     'csv2json',
     'getwebpage',
     'wlong',
     'cache',
     'int2bitlen',
     'char2bitlen',
 ]
Definition at line 43 of file basic.py.