PyBooster: lib.pronouns Namespace Reference
lib.pronouns Namespace Reference
Functions
def pronoun
def pronoun2
def pronoun2f
def pronoun3
def pronoun3f
def pronounf
def swap_genders
def swap_pronouns
Variables
list __all__
tuple FIRST_SECOND
tuple FIRST_THIRD
tuple GENDER_SWAP
tuple SECOND_THIRD
Function Documentation
def lib.pronouns.pronoun (_str)
Definition at line 133 of file pronouns.py.
References lib.pronouns.swap_pronouns().
def lib.pronouns.pronoun2 (_str)
Definition at line 138 of file pronouns.py.
References lib.pronouns.swap_pronouns().
def lib.pronouns.pronoun2f (_str)
Definition at line 153 of file pronouns.py.
References lib.pronouns.swap_pronouns().
def lib.pronouns.pronoun3 (_str)
Definition at line 143 of file pronouns.py.
References lib.pronouns.swap_pronouns().
def lib.pronouns.pronoun3f (_str)
Definition at line 158 of file pronouns.py.
References lib.pronouns.swap_pronouns().
def lib.pronouns.pronounf (_str)
Definition at line 148 of file pronouns.py.
References lib.pronouns.swap_pronouns().
def lib.pronouns.swap_genders (_str)
Definition at line 163 of file pronouns.py.
References lib.pronouns.swap_pronouns().
def lib.pronouns.swap_pronouns (_str)
Definition at line 118 of file pronouns.py.
Referenced by lib.pronouns.pronoun(), lib.pronouns.pronoun2(), lib.pronouns.pronoun2f(), lib.pronouns.pronoun3(), lib.pronouns.pronoun3f(), lib.pronouns.pronounf(), and lib.pronouns.swap_genders().
Variable Documentation
list __all__
Initial value:
 = [
     # CONSTANTS
     'FIRST_THIRD',
     'FIRST_SECOND',
     'SECOND_THIRD',
     'GENDER_SWAP',
     # FUNCTIONS
     'swap_pronouns',
     'pronoun',
     'pronoun2',
     'pronoun3',
     'pronounf',
     'pronoun2f',
     'pronoun3f',
     'swap_genders',
 ]
Definition at line 34 of file pronouns.py.
tuple FIRST_SECOND
Initial value:
 = (
     ('me', 'you'),
     ('you', 'me'),
     ('I', 'you'),
     ('you are', 'I am'),
     ('are you', 'am I'),
     ('your', 'my'),
     ('my', 'your'),
     ('yours', 'mine'),
     ('mine', 'yours'),
     ('you were', 'I was'),
     ('yourself', 'myself'),
     ('myself', 'yourself'),
 )
Definition at line 72 of file pronouns.py.
tuple FIRST_THIRD
Initial value:
 = (
     ('I', 'he or she'),
     ('me', 'him or her'),
     ('mine', 'his or hers'),
     ('my', 'his or her'),
     ('myself', 'him or herself'),
     ('he', 'I'),
     ('she', 'I'),
     ('his', 'mine'),
     ('hers', 'mine'),
     ('himself', 'myself'),
     ('herself', 'myself'),
     ('they', 'we'),
     ('we', 'they'),
 )
Definition at line 55 of file pronouns.py.
tuple GENDER_SWAP
Initial value:
 = (
     (r'him', r'her'),
     (r'her', r'him'),
     (r'he', r'she'),
     (r'she', r'he'),
     (r'his', r'her'),
 )
Definition at line 106 of file pronouns.py.
tuple SECOND_THIRD
Initial value:
 = (
     ('you', 'them'),
     ('them', 'you'),
     ('yours', 'theirs'),
     ('theirs', 'yours'),
     ('yourself', 'themselves'),
     ('themselves', 'yourself'),
     ('you are', 'they are'),
     ('they are', 'you are'),
     ('you were', 'they were'),
     ('they were', 'you were'),
     ('you have', 'they have'),
     ('they have', 'you have'),
     ('you had', 'they had'),
     ('they had', 'you had'),
 )
Definition at line 88 of file pronouns.py.