PyBooster: pybooster.strtools Namespace Reference
pybooster.strtools Namespace Reference
Functions
def binint2char
Convert an binary integer to a character.
def binstr2char
Convert a binary number (as a string) to a character.
def bubble2text
Convert bubble text to a plain-text string.
def bytes2str
Convert bytes to strings.
def cap
Capitalize the beginning of each word.
def char2hexstr
Convert a character(s) to hex-numbers as a st.
def char2int
Convert a character to an intege.
def char2intstr
Convert a character(s) to decimal integers as a st.
def char2noeschex
Convert a character to a hex string lacking divisions or escapes.
def endletters
Keep the first and last letter of a single word.
def escape (_str)
Escape special characters that cause syntax errors.
def expandhexescape
Convert a 16-bit hex escape to a 32-bit hex escape (\uhhhh) => (\Uhhhhhhhh)
def explode
Insert a space between each character.
def findescapes
Find character hex escapes in a string.
def firstletters
Remove the last letter of a single word.
def formal
Change the capitalization to the format used in titles.
def fval
Search a dictionary by value and stop on first instance.
def fvalhtml
Search a dict by value to find the paired value; Stop on first instance.
def hasbraille
Does this string contain Braille characters.
def hasgreek
Does this string contain Greek letters.
def hashexescape
Test if the string contains a character hex escape.
def hex2cssnot
Convert hexadecimal to CSS Notation (\01D4C3)
def hex2unicodehex
Convert hexadecimal to Unicode+Hex Notation.
def hexint2char
Convert a hex integer to a character.
def hexncr2char
Wrapper for refnum2char()
def hexstr2bytearray
Convert a hex string to a bytearray.
def hexstr2char
Convert a hex number (as a string) to a character.
def htmlentities
Replace HTML Reference Entities with characters.
def htmlescape
Replace special characters "&", "<", and ">" to HTML-escapes.
def htmlunescape
Unescape &, ', ", <, and >
def implode
Remove a space from between each character.
def insert_character
Insert a character at the specified point of a string.
def int2char
Convert an integer (as a str or int type) to a character.
def int2hexbytes
Convert int to bytes represented as an escaped hex string If byteorder is "big", the most significant byte is at the beginning of the byte array.
def int2ncr
Wrapper for int2refnum()
def int2refnum
Convert an integer to Decimal-NCR/HTML-Entity (&#38;)
def int2utf16
Convert an integer to a characte.
def int2utf32
Convert an integer to a characte.
def isascii
Test if a character is within the Ascii limit.
def isbraille
Test if the character is a Braille character.
def isctrlascii
Test if a character is within the Control Ascii limit.
def isextascii
Test if a character is within the Extended Ascii limit.
def isgreek
Test if the character is a Greek letter.
def isprntascii
Test if a character is within the Printable Ascii limit.
def isstrascii
Test if a string is within the Ascii limit.
def isstrbraille
Is this a string of Braille characters.
def isstrctrlascii
Test if a string is within the Control Ascii limit.
def isstrextascii
Test if a string is within the Extended Ascii limit.
def isstrgreek
Is this a string of Greek letters.
def isstrprntascii
Test if a string is within the Printable Ascii limit.
def isunicode
Test if a string is within the Unicode limit.
def isutf16
Test if a string is within the UTF16 limit.
def isutf8
Test if a string is within the UTF8 limit.
def lastletters
Remove the first letter of a single word.
def lowercase
Turn a string in lowercase.
def middleletters
Remove the first and last letter of a single word.
def name2char
Convert a Unicode name to a character.
def ncr2char
Wrapper for refnum2char()
def ncr2int
Decorator for refnum2int()
def ncr2refname
Wrapper for refnum2refname()
def noescape
Remove escapes from a single character hex string (\U00000026, \u0026, \x26)
def noescutf8hex
Remove escapes from UTF-8 hex strings (\x26)
def num2ordinal
Convert numbers to ordinals.
def octint2char
Convert an octal integer to a character.
def octstr2char
Convert an octal number (as a string) to a character.
def ordinal2num
Convert ordinals to numbers.
def presentlist
Convert a list to a string without the brackets and quotes.
def refname2char
Convert HTML entity name (&) to character (&)
def refname2ncr
Alias for refname2refnum()
def refname2refnum
Convert HTML entity name (&) to Decimal-NCR/HTML-Entity (&#38;)
def refnum2char
Convert HTML entity number (&#38; or &#x26;) to character (&)
def refnum2int
Convert Decimal-NCR/HTML-Entity (&#38;) to an intege.
def refnum2refname
Convert Decimal-NCR/HTML-Entity (&#38;) to HTML entity name (&)
def replacecurlycommas
Replace curly commas with a regular comma ()
def replacecurlyquotes
Replace curly quotes with straight-quotes ()
def replacespecialwhitespace
Replace special white-space characters.
def rmbyteshexesc
Remove hex escapes (b'\x80abc' => abc) from byte strings; return str.
def rmcurlycommas
Remove curly commas ()
def rmcurlyquotes
Remove curly quotes ()
def rmpunct
Remove end-of-sentence punctuation.
def rmspecialwhitespace
Remove special white-space characters.
def rplbyteshexesc
Replace hex escapes (b'\x26abc' => &abc) in byte strings; return str.
def sentence
Capitalization the beginning of each sentence.
def shrink_esc_utf16to8
Shrink a 16-bit hex escape to a 8-bit hex escape (\uhhhh) => (\xhh)
def shrink_esc_utf32to16
Shrink a 32-bit hex escape to a 16-bit hex escape (\Uhhhhhhhh) => (\uhhhh)
def shrink_esc_utf32to8
Shrink a 32-bit hex escape to a 8-bit hex escape (\Uhhhhhhhh) => (\xhh)
def splitsentencesstr
Split a string by sentence.
def sqlstr
Convert an object to a string and format the string to protect against SQL-Injection Attacks.
def square2text
Convert square text to a plain-text string.
def str2bytes
Convert strings to bytes.
def str2hexcolon
Convert a string to a hex string divided into pairs by colons.
def str2noeschex
Convert a string to a hex string lacking divisions or escapes.
def testref
Test if the string contains a character reference.
def text2bubble
Convert a plain-text string to bubble text.
def text2square
Convert a plain-text string to square text.
def togglecase
Convert uppercase to lowercase and vice versa.
def unescape (_str)
Unescape special characters that cause syntax errors.
def uppercase
Turn a string in all caps.
def utf16len
Get the UTF16 byte-size of a string.
def utf32len
Get the UTF32 byte-size of a string.
def utf7len
Get the UTF7 byte-size of a string.
def utf8convchar2hexescape
Convert a character to a UTF-8 hex string (\xc3\x9e)
def utf8convchar2hexstr
Convert a character to a hex string (0xc30x9e)
def utf8convchar2intstr
Convert a character to an integer string (& => 38)
def utf8convchar2uri
Convert a character to an URI escaped hex sequence (c3%9e)
def utf8len
Get the UTF8 byte-size of a string.
Variables
list __all__
string AIRPLANE = r''
tuple ARROWS
tuple ASTROLOGY = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
string BIOHAZARD = r''
tuple BRAILLE
string BUBBLE = '\u20dd'
string BUBBLE_TEXT = r' '
string CARD_REVERSE = r''
tuple CARDS = (r'', r'', r'', r'', r'', r'', r'', r'')
tuple CARDS_10 = (r'', r'', r'', r'')
tuple CARDS_2 = (r'', r'', r'', r'')
tuple CARDS_3 = (r'', r'', r'', r'')
tuple CARDS_4 = (r'', r'', r'', r'')
tuple CARDS_5 = (r'', r'', r'', r'')
tuple CARDS_6 = (r'', r'', r'', r'')
tuple CARDS_7 = (r'', r'', r'', r'')
tuple CARDS_8 = (r'', r'', r'', r'')
tuple CARDS_9 = (r'', r'', r'', r'')
tuple CARDS_ACE = (r'', r'', r'', r'')
tuple CARDS_CHEVALIER = (r'', r'', r'', r'')
tuple CARDS_JACK = (r'', r'', r'', r'')
tuple CARDS_JOKER = (r'', r'')
tuple CARDS_KING = (r'', r'', r'', r'')
tuple CARDS_QUEEN = (r'', r'', r'', r'')
tuple CHAR_REF = re.compile('&#(?:[0-9]+|[Xx][0-9A-Fa-f]+);')
tuple CHAR_REF2
tuple CHESS = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
tuple CHESS_BLACK = (r'', r'', r'', r'', r'', r'')
tuple CHESS_WHITE = (r'', r'', r'', r'', r'', r'')
dictionary CODES
tuple CONTROL_SYM
dictionary CONTROL_SYM_NAME
tuple CURRENCY
tuple CYRILLIC_ALPHABET
tuple DICE = (r'', r'', r'', r'', r'', r'')
string DOWN = r''
string EJECT = r''
tuple END_PUNCT = (r'', r'', r'', r'', r'')
tuple ENTITY_REF = re.compile('&[0-9A-Za-z]+;')
dictionary ESCTAB
tuple FACES
string FUEL_PUMP = r''
tuple GREEK
tuple GREEK_ACCENT
tuple GREEK_ACCENT_LOWER
tuple GREEK_ACCENT_UPPER
tuple GREEK_ALL
tuple GREEK_ARCHAIC = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
tuple GREEK_ARCHAIC_LOWER = (r'', r'', r'', r'', r'', r'', r'', r'')
tuple GREEK_ARCHAIC_UPPER = (r'', r'', r'', r'', r'')
tuple GREEK_EXTENDED
tuple GREEK_LOWER
tuple GREEK_UPPER
dictionary HTML5_REF
tuple INCOMPLETE_REF = re.compile('&[#]?[0-9A-Za-z]+')
tuple INTELLECTUAL_PROPERTY = (r'', r'', r'', r'', r'')
dictionary INVALID_CHARREFS
string KEYBOARD = r''
tuple LEADING_SURROGATE = re.compile(r'[\ud800-\udbff]')
string LEFT = r''
string LOADING = r''
tuple LOGIC = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
int LOWER_LIMIT_ASCII_CTRL = 0
int LOWER_LIMIT_ASCII_EXT = 128
int LOWER_LIMIT_ASCII_PRNT = 32
int LOWER_LIMIT_MS_LATIN1 = 129
tuple MATH
string MEDICINE = r''
tuple MUSIC
dictionary NAME2INT
dictionary NUMBER_LIST
string OHMS = r''
dictionary ORDINAL_LIST
tuple PARENTHESIS_CHAR
string PLAIN_TEXT = r'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz 0123456789'
dictionary PLANETS
tuple PLAYING_CARDS
tuple PLAYING_CARDS_52
tuple PLAYING_CARDS_56
dictionary PRINTABLE
string RADIATION = r''
tuple RECYCLE = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
string RIGHT = r''
tuple SCIENCE = (r'', r'', r'', r'', r'', r'', r'', r'', r'')
string SQUARE = '\u20de'
tuple SUPERSCRIPT_NUM = (r'', r'', r'', r'', r'', r'', r'', r'', r'')
string TELEPHONE = r''
string TOXIC = r''
tuple TRAILING_SURROGATE = re.compile(r'[\udc00-\udfff]')
tuple TRANS_TAB_BUBBLE2TEST = str.maketrans(BUBBLE_TEXT, PLAIN_TEXT)
tuple TRANS_TAB_TEXT2BUBBLE = str.maketrans(PLAIN_TEXT, BUBBLE_TEXT)
string UP = r''
int UPPER_LIMIT_ASCII_CTRL = 31
int UPPER_LIMIT_ASCII_EXT = 255
int UPPER_LIMIT_ASCII_PRNT = 127
int UPPER_LIMIT_MS_LATIN1 = 159
int UPPER_LIMIT_UNICODE = 1114111
int UPPER_LIMIT_UTF8 = 65535
string WARNING = r''
tuple ZODIAC = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
dictionary ZODIAC_SIGNS
Detailed Description
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.20
DESCRIPTION
This library contains
Constants for various characters and character ranges
Functions for various string and character manipulations
Ascii, Hex (\x*), UTF-8 (\u*), UTF-16BE/UTF-32 (\U*), HTML-Entities (&#*;)
C-escapes = JS-escapes = HTML-named-ref = decimal ncr = hex ncr
'\U0001d4c3' = '\ud835\udcc3' = = &#120003; = &#x1D4C3;
'\U0001d4a9' = '\ud835\udca9' = = &#119977; = &#x1D4A9;
unicode+hex = 0x notation = css = utf16 = utf8 = uri%
U+1D4C3 = 0x1D4C3 = \01D4C3 = D835 DCC3 = F0 9D 93 83 = F0%9D%93%83
U+1D4A9 = 0x1D4A9 = \01D4A9 = D835 DCA9 = F0 9D 92 A9 = F0%9D%92A9
VARIABLES
_refnum: stores an HTML reference number as a string (&#38;)
_refname: stores an HTML name entity as a string (&)
_name: stores an unicode character name
_char: stores a single character or an escape sequence (\x26)
_str: stores a string/text
_int: stores an integer
_hex: stores a hex sequence as an integer, str, or escape sequence
_oct: stores an octal sequence as an integer, str, or escape sequence
_bin: stores a binary sequence as an integer, str, or escape sequence
_bytes: stores a bytes-type object
_dict: specify a dictionary
_search: a value to find
_assert: indicate that some condition be met
_numbase: specify the base of the number ('2'=binary; '16'=hex; etc.)
_escape: boolean; "True" (the default) makes a function escape the output
_endian: specify endian (little/big); default is the native value
_encoding: specify encoding; the default value is "utf8"
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
The PyBooster Library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Function Documentation
def pybooster.strtools.binint2char (_bin)
Convert an binary integer to a character.
binint2char(0b100110) => \U00000026 binint2char(0b100110, False) => &
Definition at line 6583 of file strtools.py.
References pybooster.strtools.int2char().
def pybooster.strtools.binstr2char (_bin)
Convert a binary number (as a string) to a character.
binstr2char('0b100110') => \U00000026 binstr2char(0b100110) => \U00000026 binstr2char('100110', False) => &
Definition at line 6574 of file strtools.py.
References pybooster.strtools.int2char().
def pybooster.strtools.bubble2text (_str)
Convert bubble text to a plain-text string.
>>> bubble2text(' .') 'This is a test.' >>> bubble2text(' () . ') 'This is a second (2nd) test.' >>> bubble2text(' : , * , , , . ') 'Testing various characters: , *, , , and .'
Definition at line 6982 of file strtools.py.
def pybooster.strtools.bytes2str (_bytes)
Convert bytes to strings.
Definition at line 6931 of file strtools.py.
def pybooster.strtools.cap (_str)
Capitalize the beginning of each word.
>>> cap('this is a test.') 'This Is A Test.'
Definition at line 5318 of file strtools.py.
def pybooster.strtools.char2hexstr (_char)
Convert a character(s) to hex-numbers as a st.
Definition at line 6746 of file strtools.py.
def pybooster.strtools.char2int (_char)
Convert a character to an intege.
Definition at line 6644 of file strtools.py.
def pybooster.strtools.char2intstr (_char)
Convert a character(s) to decimal integers as a st.
Definition at line 6911 of file strtools.py.
def pybooster.strtools.char2noeschex (_char)
Convert a character to a hex string lacking divisions or escapes.
>>> char2noeschex('&') '26'
Definition at line 6448 of file strtools.py.
def pybooster.strtools.endletters (_str)
Keep the first and last letter of a single word.
>>> endletters('Test') 'Tt'
Definition at line 5247 of file strtools.py.
def pybooster.strtools.escape (_str)
Escape special characters that cause syntax errors.
>>> escape('String with "special" characters') 'String with &#34;special&#34; characters'
Definition at line 6212 of file strtools.py.
def pybooster.strtools.expandhexescape (_hex)
Convert a 16-bit hex escape to a 32-bit hex escape (\uhhhh) => (\Uhhhhhhhh)
>>> expandhexescape('\u202f') '\U0000202f'
Definition at line 6437 of file strtools.py.
def pybooster.strtools.explode (_str)
Insert a space between each character.
>>> explode('this is a test.') ' t h i s i s a t e s t . '
Definition at line 5372 of file strtools.py.
def pybooster.strtools.findescapes (_str)
Find character hex escapes in a string.
Return a list of the escapes Return an empty list if none are found
>>> findescapes('This is a \u202f test.') ['\u202f', [...]]
Definition at line 6237 of file strtools.py.
def pybooster.strtools.firstletters (_str)
Remove the last letter of a single word.
>>> firstletters('Test') 'Tes'
Definition at line 5256 of file strtools.py.
def pybooster.strtools.formal (_str)
Change the capitalization to the format used in titles.
>>> formal('this is a test.') 'This Is A Test.'
Definition at line 5327 of file strtools.py.
def pybooster.strtools.fval (_dict)
Search a dictionary by value and stop on first instance.
This searches key values that are tuples, lists, or strings. Returns the key (if found); else returns empty string
Definition at line 5521 of file strtools.py.
Referenced by pybooster.strtools.refname2char().
def pybooster.strtools.fvalhtml (_search)
Search a dict by value to find the paired value; Stop on first instance.
For example, this finds '&#38;' or '&' and returns the other value Returns HTML entity if found; else return empty string
Definition at line 5535 of file strtools.py.
Referenced by pybooster.strtools.refname2refnum(), and pybooster.strtools.refnum2refname().
def pybooster.strtools.hasbraille (_str)
Does this string contain Braille characters.
>>> hasbraille('') True >>> hasbraille('qwerty') True >>> hasbraille('0123') True >>> hasbraille('qwerty') False >>> hasbraille('0123') False
Definition at line 5880 of file strtools.py.
def pybooster.strtools.hasgreek (_str)
Does this string contain Greek letters.
>>> hasgreek('') True >>> hasgreek('qwerty') False >>> hasgreek('0123') False >>> hasgreek('qwerty') True >>> hasgreek('0123') True
Definition at line 5827 of file strtools.py.
def pybooster.strtools.hashexescape (_str)
Test if the string contains a character hex escape.
Definition at line 5960 of file strtools.py.
def pybooster.strtools.hex2cssnot (_hex)
Convert hexadecimal to CSS Notation (\01D4C3)
Definition at line 6815 of file strtools.py.
def pybooster.strtools.hex2unicodehex (_hex)
Convert hexadecimal to Unicode+Hex Notation.
Definition at line 6764 of file strtools.py.
def pybooster.strtools.hexint2char (_hex)
Convert a hex integer to a character.
hexint2char(0x26) => \U00000026 hexint2char(0x26, False) => &
Definition at line 6545 of file strtools.py.
References pybooster.strtools.int2char().
def pybooster.strtools.hexncr2char (_refname)
Wrapper for refnum2char()
Definition at line 6621 of file strtools.py.
References pybooster.strtools.refnum2char().
def pybooster.strtools.hexstr2bytearray (_hex)
Convert a hex string to a bytearray.
Definition at line 6944 of file strtools.py.
def pybooster.strtools.hexstr2char (_hex)
Convert a hex number (as a string) to a character.
hexstr2char('0x26') => \U00000026 hexstr2char(0x26) => \U00000026 hexstr2char('26', False) => &
Definition at line 6536 of file strtools.py.
References pybooster.strtools.int2char().
def pybooster.strtools.htmlentities (_data)
Replace HTML Reference Entities with characters.
>>> htmlentities('This 'is' a test (π, , &#98;).') "This 'is' a test (, $, b)."
Definition at line 6306 of file strtools.py.
References pybooster.strtools.refname2char(), and pybooster.strtools.refnum2char().
def pybooster.strtools.htmlescape (_str)
Replace special characters "&", "<", and ">" to HTML-escapes.
If the optional flag quote is true (default), double quote (") and single quote (') characters are also escaped.
>>> htmlescape('This is a "test" (&).') 'This <b>is</b> a "test" (&).' >>> htmlescape('This is a "test" (&).', False) 'This <b>is</b> a "test" (&).'
Definition at line 6330 of file strtools.py.
def pybooster.strtools.htmlunescape (_str)
Unescape &, ', ", <, and >
>>> htmlunescape('This &#x3c;b&#62;is</b> a &#34;test" (&).') 'This is a "test" (&).' >>> htmlunescape('This <b>is</b> a "test" (&).') 'This is a "test" (&).'
Definition at line 6350 of file strtools.py.
def pybooster.strtools.implode (_str)
Remove a space from between each character.
>>> implode('this is a test.') 'thisisatest.' >>> implode(' t h i s i s a t e s t . ') 'this is a test.'
Definition at line 5383 of file strtools.py.
def pybooster.strtools.insert_character (_str)
Insert a character at the specified point of a string.
Definition at line 5279 of file strtools.py.
def pybooster.strtools.int2char (_int, _numbase)
Convert an integer (as a str or int type) to a character.
The integer may be decimal, hex, octal, or binary By default, the returned value is escaped unicode (\U0000000) int2char(_int, _numbase, _escape) => str _int number to convert to a character _numbase Specify the int's base (2, 8, 10, 16) _escape False = No escapes; True = Escapes int2char(38) => \U00000026 int2char('38') => \U00000026 int2char('0x26') => \U00000026 int2char(0x26) => \U00000026 int2char('26', '16') => \U00000026 int2char('26', '16', False) => &
Definition at line 6488 of file strtools.py.
Referenced by pybooster.strtools.binint2char(), pybooster.strtools.binstr2char(), pybooster.strtools.hexint2char(), pybooster.strtools.hexstr2char(), pybooster.strtools.octint2char(), and pybooster.strtools.octstr2char().
def pybooster.strtools.int2hexbytes (_int)
Convert int to bytes represented as an escaped hex string If byteorder is "big", the most significant byte is at the beginning of the byte array.
If byteorder is "little", the most significant byte is at the end of the byte array.
Definition at line 6939 of file strtools.py.
def pybooster.strtools.int2ncr (_int)
Wrapper for int2refnum()
Definition at line 6888 of file strtools.py.
References pybooster.strtools.int2refnum().
def pybooster.strtools.int2refnum (_int)
Convert an integer to Decimal-NCR/HTML-Entity (&#38;)
Definition at line 6881 of file strtools.py.
Referenced by pybooster.strtools.int2ncr().
def pybooster.strtools.int2utf16 (_int)
Convert an integer to a characte.
Definition at line 6724 of file strtools.py.
def pybooster.strtools.int2utf32 (_int)
Convert an integer to a characte.
Definition at line 6736 of file strtools.py.
def pybooster.strtools.isascii (_str)
Test if a character is within the Ascii limit.
>>> isascii('B') True >>> isascii('b') True >>> isascii('1') True >>> isascii('') False >>> isascii('') False >>> isascii('') False
Definition at line 5653 of file strtools.py.
Referenced by pybooster.strtools.isstrascii().
def pybooster.strtools.isbraille (_str)
Test if the character is a Braille character.
>>> isbraille('') True >>> isbraille('') True >>> isbraille('q') False >>> isbraille('0') False
Definition at line 5842 of file strtools.py.
def pybooster.strtools.isctrlascii (_str)
Test if a character is within the Control Ascii limit.
>>> isctrlascii('\r') True >>> isctrlascii('\n') True >>> isctrlascii('\a') True >>> isctrlascii('\0') True >>> isctrlascii('') False >>> isctrlascii('') False
Definition at line 5696 of file strtools.py.
Referenced by pybooster.strtools.isstrctrlascii().
def pybooster.strtools.isextascii (_str)
Test if a character is within the Extended Ascii limit.
Definition at line 5758 of file strtools.py.
Referenced by pybooster.strtools.isstrextascii().
def pybooster.strtools.isgreek (_str)
Test if the character is a Greek letter.
>>> isgreek('') True >>> isgreek('') True >>> isgreek('') True >>> isgreek('') True >>> isgreek('q') False >>> isgreek('0') False
Definition at line 5785 of file strtools.py.
def pybooster.strtools.isprntascii (_str)
Test if a character is within the Printable Ascii limit.
>>> isprntascii('1') True >>> isprntascii('q') True >>> isprntascii('') False
Definition at line 5733 of file strtools.py.
Referenced by pybooster.strtools.isstrprntascii().
def pybooster.strtools.isstrascii (_str)
Test if a string is within the Ascii limit.
>>> isstrascii('B') True >>> isstrascii('b') True >>> isstrascii('123') True >>> isstrascii('qwerty') True >>> isstrascii('') False >>> isstrascii('') False >>> isstrascii('123qwerty') False
Definition at line 5677 of file strtools.py.
References pybooster.strtools.isascii().
def pybooster.strtools.isstrbraille (_str)
Is this a string of Braille characters.
>>> isstrbraille('') True >>> isstrbraille('') True >>> isstrbraille('qwerty') False >>> isstrbraille('0123') False >>> isstrbraille('qwerty') False >>> isstrbraille('0123') False
Definition at line 5863 of file strtools.py.
def pybooster.strtools.isstrctrlascii (_str)
Test if a string is within the Control Ascii limit.
>>> isstrctrlascii('\r') True >>> isstrctrlascii('\a') True >>> isstrctrlascii('\a\0') True >>> isstrctrlascii('qwerty\n') False >>> isstrctrlascii('') False >>> isstrctrlascii('qwerty') False >>> isstrctrlascii('') False
Definition at line 5720 of file strtools.py.
References pybooster.strtools.isctrlascii().
def pybooster.strtools.isstrextascii (_str)
Test if a string is within the Extended Ascii limit.
Definition at line 5766 of file strtools.py.
References pybooster.strtools.isextascii().
def pybooster.strtools.isstrgreek (_str)
Is this a string of Greek letters.
>>> isstrgreek('') True >>> isstrgreek('') True >>> isstrgreek('') True >>> isstrgreek('') True >>> isstrgreek('qwerty') False >>> isstrgreek('0123') False >>> isstrgreek('qwerty') False >>> isstrgreek('0123') False
Definition at line 5810 of file strtools.py.
def pybooster.strtools.isstrprntascii (_str)
Test if a string is within the Printable Ascii limit.
>>> isstrprntascii('1') True >>> isstrprntascii('123') True >>> isstrprntascii('qwerty') True >>> isstrprntascii('') False >>> isstrprntascii('qwerty') False
Definition at line 5753 of file strtools.py.
References pybooster.strtools.isprntascii().
def pybooster.strtools.isunicode (_str)
Test if a string is within the Unicode limit.
Definition at line 5909 of file strtools.py.
def pybooster.strtools.isutf16 (_str)
Test if a string is within the UTF16 limit.
Definition at line 5900 of file strtools.py.
def pybooster.strtools.isutf8 (_str)
Test if a string is within the UTF8 limit.
>>> isutf8('a') True >>> isutf8('') True
Definition at line 5891 of file strtools.py.
def pybooster.strtools.lastletters (_str)
Remove the first letter of a single word.
>>> lastletters('Test') 'est'
Definition at line 5265 of file strtools.py.
def pybooster.strtools.lowercase (_str)
Turn a string in lowercase.
>>> lowercase('THIS IS A TEST.') 'this is a test.'
Definition at line 5336 of file strtools.py.
def pybooster.strtools.middleletters (_str)
Remove the first and last letter of a single word.
>>> middleletters('Test') 'es'
Definition at line 5274 of file strtools.py.
def pybooster.strtools.name2char (_name)
Convert a Unicode name to a character.
If the name is invalid, an empty string is returned
Definition at line 6629 of file strtools.py.
def pybooster.strtools.ncr2char (_refname)
Wrapper for refnum2char()
Definition at line 6616 of file strtools.py.
References pybooster.strtools.refnum2char().
def pybooster.strtools.ncr2int (_refnum)
Decorator for refnum2int()
Definition at line 6660 of file strtools.py.
References pybooster.strtools.refnum2int().
def pybooster.strtools.ncr2refname (_refnum)
Wrapper for refnum2refname()
Definition at line 6903 of file strtools.py.
References pybooster.strtools.refnum2refname().
def pybooster.strtools.noescape (_hex)
Remove escapes from a single character hex string (\U00000026, \u0026, \x26)
Definition at line 5561 of file strtools.py.
Referenced by pybooster.strtools.refname2char().
def pybooster.strtools.noescutf8hex (_hex)
Remove escapes from UTF-8 hex strings (\x26)
>>> noescutf8hex('\x26') '&'
Definition at line 6381 of file strtools.py.
def pybooster.strtools.num2ordinal (_str)
Convert numbers to ordinals.
>>> num2ordinal('21') 'twenty-first'
Definition at line 5288 of file strtools.py.
def pybooster.strtools.octint2char (_oct)
Convert an octal integer to a character.
octint2char(0o46) => \U00000026 octint2char(0o46, False) => &
Definition at line 6564 of file strtools.py.
References pybooster.strtools.int2char().
def pybooster.strtools.octstr2char (_oct)
Convert an octal number (as a string) to a character.
octstr2char('0o46') => \U00000026 octstr2char(0o46) => \U00000026 octstr2char('46', False) => &
Definition at line 6555 of file strtools.py.
References pybooster.strtools.int2char().
def pybooster.strtools.ordinal2num (_str)
Convert ordinals to numbers.
>>> ordinal2num('twenty-first') '21'
Definition at line 5303 of file strtools.py.
def pybooster.strtools.presentlist (_list)
Convert a list to a string without the brackets and quotes.
Definition at line 5509 of file strtools.py.
def pybooster.strtools.refname2char (_refname)
Convert HTML entity name (&) to character (&)
Definition at line 6588 of file strtools.py.
References pybooster.strtools.fval(), and pybooster.strtools.noescape().
Referenced by pybooster.strtools.htmlentities().
def pybooster.strtools.refname2ncr (_refname)
Alias for refname2refnum()
Definition at line 6876 of file strtools.py.
References pybooster.strtools.refname2refnum().
def pybooster.strtools.refname2refnum (_refname)
Convert HTML entity name (&) to Decimal-NCR/HTML-Entity (&#38;)
Definition at line 6869 of file strtools.py.
References pybooster.strtools.fvalhtml().
Referenced by pybooster.strtools.refname2ncr().
def pybooster.strtools.refnum2char (_refnum)
Convert HTML entity number (&#38; or &#x26;) to character (&)
Definition at line 6598 of file strtools.py.
Referenced by pybooster.strtools.hexncr2char(), pybooster.strtools.htmlentities(), and pybooster.strtools.ncr2char().
def pybooster.strtools.refnum2int (_refnum)
Convert Decimal-NCR/HTML-Entity (&#38;) to an intege.
Definition at line 6649 of file strtools.py.
Referenced by pybooster.strtools.ncr2int().
def pybooster.strtools.refnum2refname (_refnum)
Convert Decimal-NCR/HTML-Entity (&#38;) to HTML entity name (&)
Definition at line 6896 of file strtools.py.
References pybooster.strtools.fvalhtml().
Referenced by pybooster.strtools.ncr2refname().
def pybooster.strtools.replacecurlycommas (_str)
Replace curly commas with a regular comma ()
>>> replacecurlycommas('This is a test.') 'This is, a test.'
Definition at line 5401 of file strtools.py.
def pybooster.strtools.replacecurlyquotes (_str)
Replace curly quotes with straight-quotes ()
>>> replacecurlyquotes('This is a test.') 'This is a "test".'
Definition at line 5419 of file strtools.py.
def pybooster.strtools.replacespecialwhitespace (_str)
Replace special white-space characters.
>>> replacespecialwhitespace('This a test.') 'This is a test.'
Definition at line 5437 of file strtools.py.
def pybooster.strtools.rmbyteshexesc (_str)
Remove hex escapes (b'\x80abc' => abc) from byte strings; return str.
>>> rmbyteshexesc(b'\x80abc') 'abc'
Definition at line 6194 of file strtools.py.
def pybooster.strtools.rmcurlycommas (_str)
Remove curly commas ()
>>> rmcurlycommas('This is a test.') 'This is a test.'
Definition at line 5392 of file strtools.py.
def pybooster.strtools.rmcurlyquotes (_str)
Remove curly quotes ()
>>> rmcurlyquotes('This is a test.') 'This is a test.'
Definition at line 5410 of file strtools.py.
def pybooster.strtools.rmpunct (_str)
Remove end-of-sentence punctuation.
>>> rmpunct('this is a test.') 'this is a test' >>> rmpunct('word text.') 'word text'
Definition at line 5448 of file strtools.py.
def pybooster.strtools.rmspecialwhitespace (_str)
Remove special white-space characters.
>>> rmspecialwhitespace('This is a test.') 'This is a test.'
Definition at line 5428 of file strtools.py.
def pybooster.strtools.rplbyteshexesc (_str)
Replace hex escapes (b'\x26abc' => &abc) in byte strings; return str.
>>> rplbyteshexesc(b'\x26abc') '&abc'
Definition at line 6203 of file strtools.py.
def pybooster.strtools.sentence (_str)
Capitalization the beginning of each sentence.
>>> sentence('this IS A TEST.') 'This is a test.'
Definition at line 5345 of file strtools.py.
def pybooster.strtools.shrink_esc_utf16to8 (_hex)
Shrink a 16-bit hex escape to a 8-bit hex escape (\uhhhh) => (\xhh)
>>> shrink_esc_utf16to8('\u002f') '\x2f'
Definition at line 6161 of file strtools.py.
def pybooster.strtools.shrink_esc_utf32to16 (_hex)
Shrink a 32-bit hex escape to a 16-bit hex escape (\Uhhhhhhhh) => (\uhhhh)
>>> shrink_esc_utf32to16('\U0000002f') '\u002f'
Definition at line 6183 of file strtools.py.
def pybooster.strtools.shrink_esc_utf32to8 (_hex)
Shrink a 32-bit hex escape to a 8-bit hex escape (\Uhhhhhhhh) => (\xhh)
>>> shrink_esc_utf32to8('\U0000002f') '\x2f'
Definition at line 6172 of file strtools.py.
def pybooster.strtools.splitsentencesstr (_str_of_sentences)
Split a string by sentence.
Definition at line 5453 of file strtools.py.
def pybooster.strtools.sqlstr (_obj, _strength)
Convert an object to a string and format the string to protect against SQL-Injection Attacks.
_strength indicates what characters should be removed or escaped 0 = (Default) Remove curly quotes, commas, and brackets; escape quotes, slashes, and dashes 1 = Same as 0, but removes characters instead of escaping 2 = Same as 1, but remove additional characters such as .?!#;&%^: 3 = Only keep ASCII letters and space
Definition at line 5474 of file strtools.py.
def pybooster.strtools.square2text (_str)
Convert square text to a plain-text string.
>>> square2text('T h i s (s t r) i s a s a m p l e t e s t . ') 'This (str) is a sample test.' >>> square2text('T h i s (s t r) i s a s a m p l e t e s t . ') 'This (str) is a sample test.' >>> square2text('T e s t i n g v a r i o u s c h a r a c t e r s : , * , , , a n d . ') 'Testing various characters: , *, , , and .'
Definition at line 7026 of file strtools.py.
def pybooster.strtools.str2bytes (_str)
Convert strings to bytes.
Definition at line 6926 of file strtools.py.
def pybooster.strtools.str2hexcolon (_str)
Convert a string to a hex string divided into pairs by colons.
>>> str2hexcolon('This is a test.') '54:68:69:73:20:69:73:20:61:20:74:65:73:74:2e'
Definition at line 6466 of file strtools.py.
def pybooster.strtools.str2noeschex (_char)
Convert a string to a hex string lacking divisions or escapes.
>>> str2noeschex('This is a test.') '54686973206973206120746573742e'
Definition at line 6457 of file strtools.py.
def pybooster.strtools.testref (_data)
Test if the string contains a character reference.
Definition at line 6113 of file strtools.py.
def pybooster.strtools.text2bubble (_str)
Convert a plain-text string to bubble text.
>>> text2bubble('This (str) is a sample test.') ' () . ' >>> text2bubble('Testing various characters: , *, , , and .') ' : , * , , , . '
Definition at line 6958 of file strtools.py.
def pybooster.strtools.text2square (_str)
Convert a plain-text string to square text.
>>> text2square('This (str) is a sample test.', True) 'T h i s (s t r) i s a s a m p l e t e s t . ' >>> text2square('This (str) is a sample test.') 'T h i s (s t r) i s a s a m p l e t e s t . ' >>> text2square('Testing various characters: , *, , , and .') 'T e s t i n g v a r i o u s c h a r a c t e r s : , * , , , a n d . '
Definition at line 7002 of file strtools.py.
def pybooster.strtools.togglecase (_str)
Convert uppercase to lowercase and vice versa.
>>> togglecase('this IS A TEST.') 'THIS is a test.'
Definition at line 5354 of file strtools.py.
def pybooster.strtools.unescape (_str)
Unescape special characters that cause syntax errors.
>>> unescape('String with &#34;special&#34; characters') 'String with "special" characters'
Definition at line 6221 of file strtools.py.
def pybooster.strtools.uppercase (_str)
Turn a string in all caps.
>>> uppercase('this is a test.') 'THIS IS A TEST.'
Definition at line 5363 of file strtools.py.
def pybooster.strtools.utf16len (_str)
Get the UTF16 byte-size of a string.
Definition at line 6144 of file strtools.py.
def pybooster.strtools.utf32len (_str)
Get the UTF32 byte-size of a string.
Definition at line 6149 of file strtools.py.
def pybooster.strtools.utf7len (_str)
Get the UTF7 byte-size of a string.
Definition at line 6134 of file strtools.py.
def pybooster.strtools.utf8convchar2hexescape (_char)
Convert a character to a UTF-8 hex string (\xc3\x9e)
Definition at line 6668 of file strtools.py.
def pybooster.strtools.utf8convchar2hexstr (_char)
Convert a character to a hex string (0xc30x9e)
Definition at line 6681 of file strtools.py.
def pybooster.strtools.utf8convchar2intstr (_char)
Convert a character to an integer string (& => 38)
Definition at line 6707 of file strtools.py.
def pybooster.strtools.utf8convchar2uri (_char)
Convert a character to an URI escaped hex sequence (c3%9e)
Definition at line 6694 of file strtools.py.
def pybooster.strtools.utf8len (_str)
Get the UTF8 byte-size of a string.
Definition at line 6139 of file strtools.py.
Variable Documentation
list __all__
Initial value:
 = [
     # CONSTANTS
     'ORDINAL_LIST',
     'NUMBER_LIST',
     'INCOMPLETE_REF',
     'ENTITY_REF',
     'CHAR_REF',
     'CHAR_REF2',
     'LEADING_SURROGATE',
     'TRAILING_SURROGATE',
     'LOWER_LIMIT_ASCII_CTRL',
     'UPPER_LIMIT_ASCII_CTRL',
     'LOWER_LIMIT_ASCII_PRNT',
     'UPPER_LIMIT_ASCII_PRNT',
     'LOWER_LIMIT_ASCII_EXT',
     'UPPER_LIMIT_ASCII_EXT',
     'LOWER_LIMIT_MS_LATIN1',
     'UPPER_LIMIT_MS_LATIN1',
     'UPPER_LIMIT_UTF8',
     'UPPER_LIMIT_UNICODE',
     'PRINTABLE',
     'ESCTAB',
     'UNESCTAB',
     # CHARACTER SHAPES
     'BUBBLE',
     'SQUARE',
     # TRANSLATION CONSTANTS
     'BUBBLE_TEXT',
     'PLAIN_TEXT',
     # TRANSLATION TABLES
     'TRANS_TAB_BUBBLE2TEST',
     'TRANS_TAB_TEXT2BUBBLE',
     # HTML UNICODE
     'CODES',
     'HTML5_REF',
     'NAME2INT',
     'INVALID_CHARREFS',
     # CHARACTER LISTS
     'ARROWS',
     'ASTROLOGY',
     'BRAILLE',
     'CARDS',
     'CHESS',
     'CHESS_BLACK',
     'CHESS_WHITE',
     'CONTROL_SYM',
     'CONTROL_SYM_NAME',
     'CURRENCY',
     'CYRILLIC_ALPHABET',
     'DICE',
     'END_PUNCT',
     'FACES',
     'INTELLECTUAL_PROPERTY',
     'LOGIC',
     'MATH',
     'MUSIC',
     'PARENTHESIS_CHAR',
     'PLANETS',
     'PLAYING_CARDS',
     'PLAYING_CARDS_52',
     'PLAYING_CARDS_56',
     'CARDS_ACE',
     'CARDS_2',
     'CARDS_3',
     'CARDS_4',
     'CARDS_5',
     'CARDS_6',
     'CARDS_7',
     'CARDS_8',
     'CARDS_9',
     'CARDS_10',
     'CARDS_JACK',
     'CARDS_QUEEN',
     'CARDS_KING',
     'CARDS_JOKER',
     'CARDS_CHEVALIER',
     'RECYCLE',
     'SCIENCE',
     'SUPERSCRIPT_NUM',
     'ZODIAC',
     'ZODIAC_SIGNS',
     # GREEK CHARACTERS
     'GREEK_UPPER',
     'GREEK_LOWER',
     'GREEK_ARCHAIC_UPPER',
     'GREEK_ARCHAIC_LOWER',
     'GREEK_ACCENT_UPPER',
     'GREEK_ACCENT_LOWER',
     'GREEK',
     'GREEK_ARCHAIC',
     'GREEK_ACCENT',
     'GREEK_EXTENDED',
     'GREEK_ALL',
     # MISCELLANEOUS SYMBOLS
     'AIRPLANE',
     'BIOHAZARD',
     'CARD_REVERSE',
     'DOWN',
     'EJECT',
     'FUEL_PUMP',
     'KEYBOARD',
     'LEFT',
     'LOADING',
     'MEDICINE',
     'OHMS',
     'RADIATION',
     'RIGHT',
     'TELEPHONE',
     'TOXIC',
     'UP',
     'WARNING',
     # STRING MANIPULATIONS
     'endletters',
     'firstletters',
     'lastletters',
     'middleletters',
     'insert_character',
     'num2ordinal',
     'ordinal2num',
     'cap',
     'formal',
     'lowercase',
     'sentence',
     'togglecase',
     'uppercase',
     'explode',
     'implode',
     'rmcurlycommas',
     'replacecurlycommas',
     'rmcurlyquotes',
     'replacecurlyquotes',
     'rmpunct',
     'splitsentencesstr',
     'sqlstr',
     'presentlist',
     # MISCELLANEOUS FUNCTIONS
     'fval',
     'fvalhtml',
     'noescape',
     # BOOLEAN TESTS
     'isascii',
     'isstrascii',
     'isctrlascii',
     'isstrctrlascii',
     'isprntascii',
     'isstrprntascii',
     'isextascii',
     'isstrextascii',
     'isgreek',
     'isstrgreek',
     'hasgreek',
     'isbraille',
     'isstrbraille',
     'hasbraille',
     'isutf8',
     'isutf16',
     'isunicode',
     'hashexescape',
     'testref',
     # LENGTHS
     'utf7len',
     'utf8len',
     'utf16len',
     'utf32len',
     # ESCAPE MANIPULATIONS
     'shrink_esc_utf16to8',
     'shrink_esc_utf32to8',
     'shrink_esc_utf32to16',
     'escape',
     'unescape',
     'htmlentities',
     'findescapes',
     'htmlescape',
     'htmlunescape',
     'noescutf8hex',
     'expandhexescape',
     'char2noeschex',
     'str2noeschex',
     'str2hexcolon',
     'rmbyteshexesc',
     'rplbyteshexesc',
     # X 2 CHARACTER
     'int2char',
     'hexstr2char',
     'hexint2char',
     'octstr2char',
     'octint2char',
     'binstr2char',
     'binint2char',
     'refname2char',
     'refnum2char',
     'ncr2char',
     'hexncr2char',
     'name2char',
     # X 2 INTEGER
     'char2int',
     'refnum2int',
     'ncr2int',
     # X 2 UTF*
     'utf8convchar2hexescape',
     'utf8convchar2hexstr',
     'utf8convchar2uri',
     'utf8convchar2intstr',
     'int2utf16',
     'int2utf32',
     # X 2 HEX
     'char2hexstr',
     'hex2unicodehex',
     'hex2cssnot',
     # X 2 HTML REFERENCE NUMBER (NCR)
     'refname2refnum',
     'refname2ncr',
     'int2refnum',
     'int2ncr',
     # X 2 HTML ENTITY NAME
     'refnum2refname',
     'ncr2refname',
     # X 2 MISC
     'char2intstr',
     'str2bytes',
     'bytes2str',
     'int2hexbytes',
     'hexstr2bytearray',
     # BUBBLE TEXT
     'text2bubble',
     'bubble2text',
     # SQUARE TEXT
     'text2square',
     'square2text',
 ]
Definition at line 74 of file strtools.py.
string AIRPLANE = r''
Definition at line 5220 of file strtools.py.
tuple ARROWS
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 4744 of file strtools.py.
tuple ASTROLOGY = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
Definition at line 4769 of file strtools.py.
string BIOHAZARD = r''
Definition at line 5221 of file strtools.py.
tuple BRAILLE
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r''
 )
Definition at line 4772 of file strtools.py.
string BUBBLE = '\u20dd'
Definition at line 517 of file strtools.py.
string BUBBLE_TEXT = r' '
Definition at line 524 of file strtools.py.
string CARD_REVERSE = r''
Definition at line 5222 of file strtools.py.
tuple CARDS = (r'', r'', r'', r'', r'', r'', r'', r'')
Definition at line 4794 of file strtools.py.
tuple CARDS_10 = (r'', r'', r'', r'')
Definition at line 5018 of file strtools.py.
tuple CARDS_2 = (r'', r'', r'', r'')
Definition at line 4994 of file strtools.py.
tuple CARDS_3 = (r'', r'', r'', r'')
Definition at line 4997 of file strtools.py.
tuple CARDS_4 = (r'', r'', r'', r'')
Definition at line 5000 of file strtools.py.
tuple CARDS_5 = (r'', r'', r'', r'')
Definition at line 5003 of file strtools.py.
tuple CARDS_6 = (r'', r'', r'', r'')
Definition at line 5006 of file strtools.py.
tuple CARDS_7 = (r'', r'', r'', r'')
Definition at line 5009 of file strtools.py.
tuple CARDS_8 = (r'', r'', r'', r'')
Definition at line 5012 of file strtools.py.
tuple CARDS_9 = (r'', r'', r'', r'')
Definition at line 5015 of file strtools.py.
tuple CARDS_ACE = (r'', r'', r'', r'')
Definition at line 4991 of file strtools.py.
tuple CARDS_CHEVALIER = (r'', r'', r'', r'')
Definition at line 5033 of file strtools.py.
tuple CARDS_JACK = (r'', r'', r'', r'')
Definition at line 5021 of file strtools.py.
tuple CARDS_JOKER = (r'', r'')
Definition at line 5030 of file strtools.py.
tuple CARDS_KING = (r'', r'', r'', r'')
Definition at line 5027 of file strtools.py.
tuple CARDS_QUEEN = (r'', r'', r'', r'')
Definition at line 5024 of file strtools.py.
tuple CHAR_REF = re.compile('&#(?:[0-9]+|[Xx][0-9A-Fa-f]+);')
Definition at line 367 of file strtools.py.
tuple CHAR_REF2
Initial value:
 = re.compile(
     r'&(#[0-9]+;?'
     r'|#[xX][0-9a-fA-F]+;?'
     r'|[^\t\n\f <&#;]{1,32};?)'
 )
Definition at line 368 of file strtools.py.
tuple CHESS = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
Definition at line 4797 of file strtools.py.
tuple CHESS_BLACK = (r'', r'', r'', r'', r'', r'')
Definition at line 4800 of file strtools.py.
tuple CHESS_WHITE = (r'', r'', r'', r'', r'', r'')
Definition at line 4803 of file strtools.py.
dictionary CODES
Definition at line 548 of file strtools.py.
tuple CONTROL_SYM
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r''
 )
Definition at line 4806 of file strtools.py.
dictionary CONTROL_SYM_NAME
Initial value:
 = {
     'NUL': '',
     'SOH': '',
     'STX': '',
     'ETX': '',
     'EOT': '',
     'ENQ': '',
     'ACK': '',
     'BEL': '',
     'BS': '',
     'HT': '',
     'LF': '',
     'VT': '',
     'FF': '',
     'CR': '',
     'SO': '',
     'SI': '',
     'DLE': '',
     'DC1': '',
     'DC2': '',
     'DC3': '',
     'DC4': '',
     'NAK': '',
     'SYN': '',
     'ETB': '',
     'CAN': '',
     'EM': '',
     'SUB': '',
     'ESC': '',
     'GS': '',
     'FS': '',
     'RS': '',
     'US': '',
     'SP': '',
     'DEL': ''
 }
Definition at line 4813 of file strtools.py.
tuple CURRENCY
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'$', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 4851 of file strtools.py.
tuple CYRILLIC_ALPHABET
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 4858 of file strtools.py.
tuple DICE = (r'', r'', r'', r'', r'', r'')
Definition at line 4866 of file strtools.py.
string DOWN = r''
Definition at line 5223 of file strtools.py.
string EJECT = r''
Definition at line 5224 of file strtools.py.
tuple END_PUNCT = (r'', r'', r'', r'', r'')
Definition at line 4869 of file strtools.py.
tuple ENTITY_REF = re.compile('&[0-9A-Za-z]+;')
Definition at line 366 of file strtools.py.
dictionary ESCTAB
Initial value:
 = {
     '"': '&#34;',    '\'': '&#39;',    '(': '&#40;',    ')': '&#41;',    '[': '&#91;',    ']': '&#93;',    '{': '&#123;',    '}': '&#125;',    '\\': '&#92;'}UNESCTAB = {    '&#34;': r'"',
     '&#39;': r'\'',
     '&#40;': r'(',
     '&#41;': r')',
     '&#91;': r'[',
     '&#93;': r']',
     '&#123;': r'{',
     '&#125;': r'}',
     '&#92;': r'\\'
 }
Definition at line 488 of file strtools.py.
tuple FACES
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 4872 of file strtools.py.
string FUEL_PUMP = r''
Definition at line 5225 of file strtools.py.
tuple GREEK
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 5117 of file strtools.py.
tuple GREEK_ACCENT
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 5128 of file strtools.py.
tuple GREEK_ACCENT_LOWER
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 5100 of file strtools.py.
tuple GREEK_ACCENT_UPPER
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
 )
Definition at line 5085 of file strtools.py.
tuple GREEK_ALL
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 5184 of file strtools.py.
tuple GREEK_ARCHAIC = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
Definition at line 5125 of file strtools.py.
tuple GREEK_ARCHAIC_LOWER = (r'', r'', r'', r'', r'', r'', r'', r'')
Definition at line 5082 of file strtools.py.
tuple GREEK_ARCHAIC_UPPER = (r'', r'', r'', r'', r'')
Definition at line 5079 of file strtools.py.
tuple GREEK_EXTENDED
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 5156 of file strtools.py.
tuple GREEK_LOWER
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 5073 of file strtools.py.
tuple GREEK_UPPER
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 5067 of file strtools.py.
dictionary HTML5_REF
Definition at line 2212 of file strtools.py.
tuple INCOMPLETE_REF = re.compile('&[#]?[0-9A-Za-z]+')
Definition at line 365 of file strtools.py.
tuple INTELLECTUAL_PROPERTY = (r'', r'', r'', r'', r'')
Definition at line 4883 of file strtools.py.
dictionary INVALID_CHARREFS
Initial value:
 = {
     0x00: '\ufffd',  # REPLACEMENT CHARACTER
     0x0d: '\r',      # CARRIAGE RETURN
     0x80: '\u20ac',  # EURO SIGN
     0x81: '\x81',    # <control>
     0x82: '\u201a',  # SINGLE LOW-9 QUOTATION MARK
     0x83: '\u0192',  # LATIN SMALL LETTER F WITH HOOK
     0x84: '\u201e',  # DOUBLE LOW-9 QUOTATION MARK
     0x85: '\u2026',  # HORIZONTAL ELLIPSIS
     0x86: '\u2020',  # DAGGER
     0x87: '\u2021',  # DOUBLE DAGGER
     0x88: '\u02c6',  # MODIFIER LETTER CIRCUMFLEX ACCENT
     0x89: '\u2030',  # PER MILLE SIGN
     0x8a: '\u0160',  # LATIN CAPITAL LETTER S WITH CARON
     0x8b: '\u2039',  # SINGLE LEFT-POINTING ANGLE QUOTATION MARK
     0x8c: '\u0152',  # LATIN CAPITAL LIGATURE OE
     0x8d: '\x8d',    # <control>
     0x8e: '\u017d',  # LATIN CAPITAL LETTER Z WITH CARON
     0x8f: '\x8f',    # <control>
     0x90: '\x90',    # <control>
     0x91: '\u2018',  # LEFT SINGLE QUOTATION MARK
     0x92: '\u2019',  # RIGHT SINGLE QUOTATION MARK
     0x93: '\u201c',  # LEFT DOUBLE QUOTATION MARK
     0x94: '\u201d',  # RIGHT DOUBLE QUOTATION MARK
     0x95: '\u2022',  # BULLET
     0x96: '\u2013',  # EN DASH
     0x97: '\u2014',  # EM DASH
     0x98: '\u02dc',  # SMALL TILDE
     0x99: '\u2122',  # TRADE MARK SIGN
     0x9a: '\u0161',  # LATIN SMALL LETTER S WITH CARON
     0x9b: '\u203a',  # SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
     0x9c: '\u0153',  # LATIN SMALL LIGATURE OE
     0x9d: '\x9d',    # <control>
     0x9e: '\u017e',  # LATIN SMALL LETTER Z WITH CARON
     0x9f: '\u0178',  # LATIN CAPITAL LETTER Y WITH DIAERESIS
 }
Definition at line 4703 of file strtools.py.
string KEYBOARD = r''
Definition at line 5226 of file strtools.py.
tuple LEADING_SURROGATE = re.compile(r'[\ud800-\udbff]')
Definition at line 373 of file strtools.py.
string LEFT = r''
Definition at line 5227 of file strtools.py.
string LOADING = r''
Definition at line 5228 of file strtools.py.
tuple LOGIC = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
Definition at line 4886 of file strtools.py.
int LOWER_LIMIT_ASCII_CTRL = 0
Definition at line 376 of file strtools.py.
int LOWER_LIMIT_ASCII_EXT = 128
Definition at line 380 of file strtools.py.
int LOWER_LIMIT_ASCII_PRNT = 32
Definition at line 378 of file strtools.py.
int LOWER_LIMIT_MS_LATIN1 = 129
Definition at line 382 of file strtools.py.
tuple MATH
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 4889 of file strtools.py.
string MEDICINE = r''
Definition at line 5229 of file strtools.py.
tuple MUSIC
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 4895 of file strtools.py.
dictionary NAME2INT
Initial value:
 = {
     'AElig': 0x00c6,  # latin capital letter AE = latin capital ligature AE, U+00C6 ISOlat1
     'Aacute': 0x00c1,  # latin capital letter A with acute, U+00C1 ISOlat1
     'Acirc': 0x00c2,  # latin capital letter A with circumflex, U+00C2 ISOlat1
     'Agrave': 0x00c0,  # latin capital letter A with grave = latin capital letter A grave, U+00C0 ISOlat1
     'Alpha': 0x0391,  # greek capital letter alpha, U+0391
     'Aring': 0x00c5,  # latin capital letter A with ring above = latin capital letter A ring, U+00C5 ISOlat1
     'Atilde': 0x00c3,  # latin capital letter A with tilde, U+00C3 ISOlat1
     'Auml': 0x00c4,  # latin capital letter A with diaeresis, U+00C4 ISOlat1
     'Beta': 0x0392,  # greek capital letter beta, U+0392
     'Ccedil': 0x00c7,  # latin capital letter C with cedilla, U+00C7 ISOlat1
     'Chi': 0x03a7,  # greek capital letter chi, U+03A7
     'Dagger': 0x2021,  # double dagger, U+2021 ISOpub
     'Delta': 0x0394,  # greek capital letter delta, U+0394 ISOgrk3
     'ETH': 0x00d0,  # latin capital letter ETH, U+00D0 ISOlat1
     'Eacute': 0x00c9,  # latin capital letter E with acute, U+00C9 ISOlat1
     'Ecirc': 0x00ca,  # latin capital letter E with circumflex, U+00CA ISOlat1
     'Egrave': 0x00c8,  # latin capital letter E with grave, U+00C8 ISOlat1
     'Epsilon': 0x0395,  # greek capital letter epsilon, U+0395
     'Eta': 0x0397,  # greek capital letter eta, U+0397
     'Euml': 0x00cb,  # latin capital letter E with diaeresis, U+00CB ISOlat1
     'Gamma': 0x0393,  # greek capital letter gamma, U+0393 ISOgrk3
     'Iacute': 0x00cd,  # latin capital letter I with acute, U+00CD ISOlat1
     'Icirc': 0x00ce,  # latin capital letter I with circumflex, U+00CE ISOlat1
     'Igrave': 0x00cc,  # latin capital letter I with grave, U+00CC ISOlat1
     'Iota': 0x0399,  # greek capital letter iota, U+0399
     'Iuml': 0x00cf,  # latin capital letter I with diaeresis, U+00CF ISOlat1
     'Kappa': 0x039a,  # greek capital letter kappa, U+039A
     'Lambda': 0x039b,  # greek capital letter lambda, U+039B ISOgrk3
     'Mu': 0x039c,  # greek capital letter mu, U+039C
     'Ntilde': 0x00d1,  # latin capital letter N with tilde, U+00D1 ISOlat1
     'Nu': 0x039d,  # greek capital letter nu, U+039D
     'OElig': 0x0152,  # latin capital ligature OE, U+0152 ISOlat2
     'Oacute': 0x00d3,  # latin capital letter O with acute, U+00D3 ISOlat1
     'Ocirc': 0x00d4,  # latin capital letter O with circumflex, U+00D4 ISOlat1
     'Ograve': 0x00d2,  # latin capital letter O with grave, U+00D2 ISOlat1
     'Omega': 0x03a9,  # greek capital letter omega, U+03A9 ISOgrk3
     'Omicron': 0x039f,  # greek capital letter omicron, U+039F
     'Oslash': 0x00d8,  # latin capital letter O with stroke = latin capital letter O slash, U+00D8 ISOlat1
     'Otilde': 0x00d5,  # latin capital letter O with tilde, U+00D5 ISOlat1
     'Ouml': 0x00d6,  # latin capital letter O with diaeresis, U+00D6 ISOlat1
     'Phi': 0x03a6,  # greek capital letter phi, U+03A6 ISOgrk3
     'Pi': 0x03a0,  # greek capital letter pi, U+03A0 ISOgrk3
     'Prime': 0x2033,  # double prime = seconds = inches, U+2033 ISOtech
     'Psi': 0x03a8,  # greek capital letter psi, U+03A8 ISOgrk3
     'Rho': 0x03a1,  # greek capital letter rho, U+03A1
     'Scaron': 0x0160,  # latin capital letter S with caron, U+0160 ISOlat2
     'Sigma': 0x03a3,  # greek capital letter sigma, U+03A3 ISOgrk3
     'THORN': 0x00de,  # latin capital letter THORN, U+00DE ISOlat1
     'Tau': 0x03a4,  # greek capital letter tau, U+03A4
     'Theta': 0x0398,  # greek capital letter theta, U+0398 ISOgrk3
     'Uacute': 0x00da,  # latin capital letter U with acute, U+00DA ISOlat1
     'Ucirc': 0x00db,  # latin capital letter U with circumflex, U+00DB ISOlat1
     'Ugrave': 0x00d9,  # latin capital letter U with grave, U+00D9 ISOlat1
     'Upsilon': 0x03a5,  # greek capital letter upsilon, U+03A5 ISOgrk3
     'Uuml': 0x00dc,  # latin capital letter U with diaeresis, U+00DC ISOlat1
     'Xi': 0x039e,  # greek capital letter xi, U+039E ISOgrk3
     'Yacute': 0x00dd,  # latin capital letter Y with acute, U+00DD ISOlat1
     'Yuml': 0x0178,  # latin capital letter Y with diaeresis, U+0178 ISOlat2
     'Zeta': 0x0396,  # greek capital letter zeta, U+0396
     'aacute': 0x00e1,  # latin small letter a with acute, U+00E1 ISOlat1
     'acirc': 0x00e2,  # latin small letter a with circumflex, U+00E2 ISOlat1
     'acute': 0x00b4,  # acute accent = spacing acute, U+00B4 ISOdia
     'aelig': 0x00e6,  # latin small letter ae = latin small ligature ae, U+00E6 ISOlat1
     'agrave': 0x00e0,  # latin small letter a with grave = latin small letter a grave, U+00E0 ISOlat1
     'alefsym': 0x2135,  # alef symbol = first transfinite cardinal, U+2135 NEW
     'alpha': 0x03b1,  # greek small letter alpha, U+03B1 ISOgrk3
     'amp': 0x0026,  # ampersand, U+0026 ISOnum
     'and': 0x2227,  # logical and = wedge, U+2227 ISOtech
     'ang': 0x2220,  # angle, U+2220 ISOamso
     'aring': 0x00e5,  # latin small letter a with ring above = latin small letter a ring, U+00E5 ISOlat1
     'asymp': 0x2248,  # almost equal to = asymptotic to, U+2248 ISOamsr
     'atilde': 0x00e3,  # latin small letter a with tilde, U+00E3 ISOlat1
     'auml': 0x00e4,  # latin small letter a with diaeresis, U+00E4 ISOlat1
     'bdquo': 0x201e,  # double low-9 quotation mark, U+201E NEW
     'beta': 0x03b2,  # greek small letter beta, U+03B2 ISOgrk3
     'brvbar': 0x00a6,  # broken bar = broken vertical bar, U+00A6 ISOnum
     'bull': 0x2022,  # bullet = black small circle, U+2022 ISOpub
     'cap': 0x2229,  # intersection = cap, U+2229 ISOtech
     'ccedil': 0x00e7,  # latin small letter c with cedilla, U+00E7 ISOlat1
     'cedil': 0x00b8,  # cedilla = spacing cedilla, U+00B8 ISOdia
     'cent': 0x00a2,  # cent sign, U+00A2 ISOnum
     'chi': 0x03c7,  # greek small letter chi, U+03C7 ISOgrk3
     'circ': 0x02c6,  # modifier letter circumflex accent, U+02C6 ISOpub
     'clubs': 0x2663,  # black club suit = shamrock, U+2663 ISOpub
     'cong': 0x2245,  # approximately equal to, U+2245 ISOtech
     'copy': 0x00a9,  # copyright sign, U+00A9 ISOnum
     'crarr': 0x21b5,  # downwards arrow with corner leftwards = carriage return, U+21B5 NEW
     'cup': 0x222a,  # union = cup, U+222A ISOtech
     'curren': 0x00a4,  # currency sign, U+00A4 ISOnum
     'dArr': 0x21d3,  # downwards double arrow, U+21D3 ISOamsa
     'dagger': 0x2020,  # dagger, U+2020 ISOpub
     'darr': 0x2193,  # downwards arrow, U+2193 ISOnum
     'deg': 0x00b0,  # degree sign, U+00B0 ISOnum
     'delta': 0x03b4,  # greek small letter delta, U+03B4 ISOgrk3
     'diams': 0x2666,  # black diamond suit, U+2666 ISOpub
     'divide': 0x00f7,  # division sign, U+00F7 ISOnum
     'eacute': 0x00e9,  # latin small letter e with acute, U+00E9 ISOlat1
     'ecirc': 0x00ea,  # latin small letter e with circumflex, U+00EA ISOlat1
     'egrave': 0x00e8,  # latin small letter e with grave, U+00E8 ISOlat1
     'empty': 0x2205,  # empty set = null set = diameter, U+2205 ISOamso
     'emsp': 0x2003,  # em space, U+2003 ISOpub
     'ensp': 0x2002,  # en space, U+2002 ISOpub
     'epsilon': 0x03b5,  # greek small letter epsilon, U+03B5 ISOgrk3
     'equiv': 0x2261,  # identical to, U+2261 ISOtech
     'eta': 0x03b7,  # greek small letter eta, U+03B7 ISOgrk3
     'eth': 0x00f0,  # latin small letter eth, U+00F0 ISOlat1
     'euml': 0x00eb,  # latin small letter e with diaeresis, U+00EB ISOlat1
     'euro': 0x20ac,  # euro sign, U+20AC NEW
     'exist': 0x2203,  # there exists, U+2203 ISOtech
     'fnof': 0x0192,  # latin small f with hook = function = florin, U+0192 ISOtech
     'forall': 0x2200,  # for all, U+2200 ISOtech
     'frac12': 0x00bd,  # vulgar fraction one half = fraction one half, U+00BD ISOnum
     'frac14': 0x00bc,  # vulgar fraction one quarter = fraction one quarter, U+00BC ISOnum
     'frac34': 0x00be,  # vulgar fraction three quarters = fraction three quarters, U+00BE ISOnum
     'frasl': 0x2044,  # fraction slash, U+2044 NEW
     'gamma': 0x03b3,  # greek small letter gamma, U+03B3 ISOgrk3
     'ge': 0x2265,  # greater-than or equal to, U+2265 ISOtech
     'gt': 0x003e,  # greater-than sign, U+003E ISOnum
     'hArr': 0x21d4,  # left right double arrow, U+21D4 ISOamsa
     'harr': 0x2194,  # left right arrow, U+2194 ISOamsa
     'hearts': 0x2665,  # black heart suit = valentine, U+2665 ISOpub
     'hellip': 0x2026,  # horizontal ellipsis = three dot leader, U+2026 ISOpub
     'iacute': 0x00ed,  # latin small letter i with acute, U+00ED ISOlat1
     'icirc': 0x00ee,  # latin small letter i with circumflex, U+00EE ISOlat1
     'iexcl': 0x00a1,  # inverted exclamation mark, U+00A1 ISOnum
     'igrave': 0x00ec,  # latin small letter i with grave, U+00EC ISOlat1
     'image': 0x2111,  # blackletter capital I = imaginary part, U+2111 ISOamso
     'infin': 0x221e,  # infinity, U+221E ISOtech
     'int': 0x222b,  # integral, U+222B ISOtech
     'iota': 0x03b9,  # greek small letter iota, U+03B9 ISOgrk3
     'iquest': 0x00bf,  # inverted question mark = turned question mark, U+00BF ISOnum
     'isin': 0x2208,  # element of, U+2208 ISOtech
     'iuml': 0x00ef,  # latin small letter i with diaeresis, U+00EF ISOlat1
     'kappa': 0x03ba,  # greek small letter kappa, U+03BA ISOgrk3
     'lArr': 0x21d0,  # leftwards double arrow, U+21D0 ISOtech
     'lambda': 0x03bb,  # greek small letter lambda, U+03BB ISOgrk3
     'lang': 0x2329,  # left-pointing angle bracket = bra, U+2329 ISOtech
     'laquo': 0x00ab,  # left-pointing double angle quotation mark = left pointing guillemet, U+00AB ISOnum
     'larr': 0x2190,  # leftwards arrow, U+2190 ISOnum
     'lceil': 0x2308,  # left ceiling = apl upstile, U+2308 ISOamsc
     'ldquo': 0x201c,  # left double quotation mark, U+201C ISOnum
     'le': 0x2264,  # less-than or equal to, U+2264 ISOtech
     'lfloor': 0x230a,  # left floor = apl downstile, U+230A ISOamsc
     'lowast': 0x2217,  # asterisk operator, U+2217 ISOtech
     'loz': 0x25ca,  # lozenge, U+25CA ISOpub
     'lrm': 0x200e,  # left-to-right mark, U+200E NEW RFC 2070
     'lsaquo': 0x2039,  # single left-pointing angle quotation mark, U+2039 ISO proposed
     'lsquo': 0x2018,  # left single quotation mark, U+2018 ISOnum
     'lt': 0x003c,  # less-than sign, U+003C ISOnum
     'macr': 0x00af,  # macron = spacing macron = overline = APL overbar, U+00AF ISOdia
     'mdash': 0x2014,  # em dash, U+2014 ISOpub
     'micro': 0x00b5,  # micro sign, U+00B5 ISOnum
     'middot': 0x00b7,  # middle dot = Georgian comma = Greek middle dot, U+00B7 ISOnum
     'minus': 0x2212,  # minus sign, U+2212 ISOtech
     'mu': 0x03bc,  # greek small letter mu, U+03BC ISOgrk3
     'nabla': 0x2207,  # nabla = backward difference, U+2207 ISOtech
     'nbsp': 0x00a0,  # no-break space = non-breaking space, U+00A0 ISOnum
     'ndash': 0x2013,  # en dash, U+2013 ISOpub
     'ne': 0x2260,  # not equal to, U+2260 ISOtech
     'ni': 0x220b,  # contains as member, U+220B ISOtech
     'not': 0x00ac,  # not sign, U+00AC ISOnum
     'notin': 0x2209,  # not an element of, U+2209 ISOtech
     'nsub': 0x2284,  # not a subset of, U+2284 ISOamsn
     'ntilde': 0x00f1,  # latin small letter n with tilde, U+00F1 ISOlat1
     'nu': 0x03bd,  # greek small letter nu, U+03BD ISOgrk3
     'oacute': 0x00f3,  # latin small letter o with acute, U+00F3 ISOlat1
     'ocirc': 0x00f4,  # latin small letter o with circumflex, U+00F4 ISOlat1
     'oelig': 0x0153,  # latin small ligature oe, U+0153 ISOlat2
     'ograve': 0x00f2,  # latin small letter o with grave, U+00F2 ISOlat1
     'oline': 0x203e,  # overline = spacing overscore, U+203E NEW
     'omega': 0x03c9,  # greek small letter omega, U+03C9 ISOgrk3
     'omicron': 0x03bf,  # greek small letter omicron, U+03BF NEW
     'oplus': 0x2295,  # circled plus = direct sum, U+2295 ISOamsb
     'or': 0x2228,  # logical or = vee, U+2228 ISOtech
     'ordf': 0x00aa,  # feminine ordinal indicator, U+00AA ISOnum
     'ordm': 0x00ba,  # masculine ordinal indicator, U+00BA ISOnum
     'oslash': 0x00f8,  # latin small letter o with stroke, = latin small letter o slash, U+00F8 ISOlat1
     'otilde': 0x00f5,  # latin small letter o with tilde, U+00F5 ISOlat1
     'otimes': 0x2297,  # circled times = vector product, U+2297 ISOamsb
     'ouml': 0x00f6,  # latin small letter o with diaeresis, U+00F6 ISOlat1
     'para': 0x00b6,  # pilcrow sign = paragraph sign, U+00B6 ISOnum
     'part': 0x2202,  # partial differential, U+2202 ISOtech
     'permil': 0x2030,  # per mille sign, U+2030 ISOtech
     'perp': 0x22a5,  # up tack = orthogonal to = perpendicular, U+22A5 ISOtech
     'phi': 0x03c6,  # greek small letter phi, U+03C6 ISOgrk3
     'pi': 0x03c0,  # greek small letter pi, U+03C0 ISOgrk3
     'piv': 0x03d6,  # greek pi symbol, U+03D6 ISOgrk3
     'plusmn': 0x00b1,  # plus-minus sign = plus-or-minus sign, U+00B1 ISOnum
     'pound': 0x00a3,  # pound sign, U+00A3 ISOnum
     'prime': 0x2032,  # prime = minutes = feet, U+2032 ISOtech
     'prod': 0x220f,  # n-ary product = product sign, U+220F ISOamsb
     'prop': 0x221d,  # proportional to, U+221D ISOtech
     'psi': 0x03c8,  # greek small letter psi, U+03C8 ISOgrk3
     'quot': 0x0022,  # quotation mark = APL quote, U+0022 ISOnum
     'rArr': 0x21d2,  # rightwards double arrow, U+21D2 ISOtech
     'radic': 0x221a,  # square root = radical sign, U+221A ISOtech
     'rang': 0x232a,  # right-pointing angle bracket = ket, U+232A ISOtech
     'raquo': 0x00bb,  # right-pointing double angle quotation mark = right pointing guillemet, U+00BB ISOnum
     'rarr': 0x2192,  # rightwards arrow, U+2192 ISOnum
     'rceil': 0x2309,  # right ceiling, U+2309 ISOamsc
     'rdquo': 0x201d,  # right double quotation mark, U+201D ISOnum
     'real': 0x211c,  # blackletter capital R = real part symbol, U+211C ISOamso
     'reg': 0x00ae,  # registered sign = registered trade mark sign, U+00AE ISOnum
     'rfloor': 0x230b,  # right floor, U+230B ISOamsc
     'rho': 0x03c1,  # greek small letter rho, U+03C1 ISOgrk3
     'rlm': 0x200f,  # right-to-left mark, U+200F NEW RFC 2070
     'rsaquo': 0x203a,  # single right-pointing angle quotation mark, U+203A ISO proposed
     'rsquo': 0x2019,  # right single quotation mark, U+2019 ISOnum
     'sbquo': 0x201a,  # single low-9 quotation mark, U+201A NEW
     'scaron': 0x0161,  # latin small letter s with caron, U+0161 ISOlat2
     'sdot': 0x22c5,  # dot operator, U+22C5 ISOamsb
     'sect': 0x00a7,  # section sign, U+00A7 ISOnum
     'shy': 0x00ad,  # soft hyphen = discretionary hyphen, U+00AD ISOnum
     'sigma': 0x03c3,  # greek small letter sigma, U+03C3 ISOgrk3
     'sigmaf': 0x03c2,  # greek small letter final sigma, U+03C2 ISOgrk3
     'sim': 0x223c,  # tilde operator = varies with = similar to, U+223C ISOtech
     'spades': 0x2660,  # black spade suit, U+2660 ISOpub
     'sub': 0x2282,  # subset of, U+2282 ISOtech
     'sube': 0x2286,  # subset of or equal to, U+2286 ISOtech
     'sum': 0x2211,  # n-ary sumation, U+2211 ISOamsb
     'sup': 0x2283,  # superset of, U+2283 ISOtech
     'sup1': 0x00b9,  # superscript one = superscript digit one, U+00B9 ISOnum
     'sup2': 0x00b2,  # superscript two = superscript digit two = squared, U+00B2 ISOnum
     'sup3': 0x00b3,  # superscript three = superscript digit three = cubed, U+00B3 ISOnum
     'supe': 0x2287,  # superset of or equal to, U+2287 ISOtech
     'szlig': 0x00df,  # latin small letter sharp s = ess-zed, U+00DF ISOlat1
     'tau': 0x03c4,  # greek small letter tau, U+03C4 ISOgrk3
     'there4': 0x2234,  # therefore, U+2234 ISOtech
     'theta': 0x03b8,  # greek small letter theta, U+03B8 ISOgrk3
     'thetasym': 0x03d1,  # greek small letter theta symbol, U+03D1 NEW
     'thinsp': 0x2009,  # thin space, U+2009 ISOpub
     'thorn': 0x00fe,  # latin small letter thorn with, U+00FE ISOlat1
     'tilde': 0x02dc,  # small tilde, U+02DC ISOdia
     'times': 0x00d7,  # multiplication sign, U+00D7 ISOnum
     'trade': 0x2122,  # trade mark sign, U+2122 ISOnum
     'uArr': 0x21d1,  # upwards double arrow, U+21D1 ISOamsa
     'uacute': 0x00fa,  # latin small letter u with acute, U+00FA ISOlat1
     'uarr': 0x2191,  # upwards arrow, U+2191 ISOnum
     'ucirc': 0x00fb,  # latin small letter u with circumflex, U+00FB ISOlat1
     'ugrave': 0x00f9,  # latin small letter u with grave, U+00F9 ISOlat1
     'uml': 0x00a8,  # diaeresis = spacing diaeresis, U+00A8 ISOdia
     'upsih': 0x03d2,  # greek upsilon with hook symbol, U+03D2 NEW
     'upsilon': 0x03c5,  # greek small letter upsilon, U+03C5 ISOgrk3
     'uuml': 0x00fc,  # latin small letter u with diaeresis, U+00FC ISOlat1
     'weierp': 0x2118,  # script capital P = power set = Weierstrass p, U+2118 ISOamso
     'xi': 0x03be,  # greek small letter xi, U+03BE ISOgrk3
     'yacute': 0x00fd,  # latin small letter y with acute, U+00FD ISOlat1
     'yen': 0x00a5,  # yen sign = yuan sign, U+00A5 ISOnum
     'yuml': 0x00ff,  # latin small letter y with diaeresis, U+00FF ISOlat1
     'zeta': 0x03b6,  # greek small letter zeta, U+03B6 ISOgrk3
     'zwj': 0x200d,  # zero width joiner, U+200D NEW RFC 2070
     'zwnj': 0x200c,  # zero width non-joiner, U+200C NEW RFC 2070
 }
Definition at line 4447 of file strtools.py.
dictionary NUMBER_LIST
Initial value:
 = {
     r'10': r'tenth',
     r'11': r'eleventh',
     r'12': r'twelfth',
     r'13': r'thirteenth',
     r'14': r'fourteenth',
     r'15': r'fifteenth',
     r'16': r'sixteenth',
     r'17': r'seventeenth',
     r'18': r'eighteenth',
     r'19': r'ninteenth',
     r'20': r'twentieth',
     r'21': r'twenty-first',
     r'22': r'twenty-second',
     r'23': r'twenty-third',
     r'24': r'twenty-fourth',
     r'1': r'first',
     r'2': r'second',
     r'3': r'third',
     r'4': r'fourth',
     r'5': r'fifth',
     r'6': r'sixth',
     r'7': r'seventh',
     r'8': r'eighth',
     r'9': r'ninth',
 }
Definition at line 337 of file strtools.py.
string OHMS = r''
Definition at line 5230 of file strtools.py.
dictionary ORDINAL_LIST
Initial value:
 = {
     r'tenth': r'10',
     r'eleventh': r'11',
     r'twelfth': r'12',
     r'thirteenth': r'13',
     r'fourteenth': r'14',
     r'fifteenth': r'15',
     r'sixteenth': r'16',
     r'seventeenth': r'17',
     r'eighteenth': r'18',
     r'ninteenth': r'19',
     r'twentieth': r'20',
     r'twenty-first': r'21',
     r'twenty-second': r'22',
     r'twenty-third': r'23',
     r'twenty-fourth': r'24',
     r'first': r'1',
     r'second': r'2',
     r'third': r'3',
     r'fourth': r'4',
     r'fifth': r'5',
     r'sixth': r'6',
     r'seventh': r'7',
     r'eighth': r'8',
     r'ninth': r'9',
 }
Definition at line 309 of file strtools.py.
tuple PARENTHESIS_CHAR
Initial value:
 = (
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'',
     r'', r'', r'', r'', r'', r'', r''
 )
Definition at line 4913 of file strtools.py.
string PLAIN_TEXT = r'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz 0123456789'
Definition at line 525 of file strtools.py.
dictionary PLANETS
Initial value:
 = {
     'SUN': '',
     'MOON': '',
     'MERCURY': '',
     'VENUS': '',
     'EARTH': '',
     'MARS': '',
     'CERES': '',
     'JUPITER': '',
     'SATURN': '',
     'URANUS': '',
     'NEPTUNE': '',
     'PLUTO': ''
 }
Definition at line 4921 of file strtools.py.
tuple PLAYING_CARDS
Initial value:
 = (
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r''
 )
Definition at line 4937 of file strtools.py.
tuple PLAYING_CARDS_52
Initial value:
 = (
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r''
 )
Definition at line 4954 of file strtools.py.
tuple PLAYING_CARDS_56
Initial value:
 = (
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'', r'', r'',
     r'', r'',
     r'', r'', r'', r''  # Chevalier/Knight
 )
Definition at line 4972 of file strtools.py.
dictionary PRINTABLE
Initial value:
 = {
     # dec: ('hex', 'oct', 'char'),
     32: ('20', '040', r' '),
     33: ('21', '041', r'!'),
     34: ('22', '042', '\x22'),
     35: ('23', '043', r'#'),
     36: ('24', '044', r'$'),
     37: ('25', '045', r'%'),
     38: ('26', '046', r'&'),
     39: ('27', '047', '\x27'),
     40: ('28', '050', '\x28'),
     41: ('29', '051', '\x29'),
     42: ('2A', '052', r'*'),
     43: ('2B', '053', r'+'),
     44: ('2C', '054', '\x2C'),
     45: ('2D', '055', r'-'),
     46: ('2E', '056', r'.'),
     47: ('2F', '057', '\x2F'),
     48: ('30', '060', '0'),
     49: ('31', '061', '1'),
     50: ('32', '062', '2'),
     51: ('33', '063', '3'),
     52: ('34', '064', '4'),
     53: ('35', '065', '5'),
     54: ('36', '066', '6'),
     55: ('37', '067', '7'),
     56: ('38', '070', '8'),
     57: ('39', '071', '9'),
     58: ('3A', '072', r':'),
     59: ('3B', '073', r';'),
     60: ('3C', '074', '\x3C'),
     61: ('3D', '075', r'='),
     62: ('3E', '076', '\x3E'),
     63: ('3F', '077', r'?'),
     64: ('40', '100', r'@'),
     65: ('41', '101', 'A'),
     66: ('42', '102', 'B'),
     67: ('43', '103', 'C'),
     68: ('44', '104', 'D'),
     69: ('45', '105', 'E'),
     70: ('46', '106', 'F'),
     71: ('47', '107', 'G'),
     72: ('48', '110', 'H'),
     73: ('49', '111', 'I'),
     74: ('4A', '112', 'J'),
     75: ('4B', '113', 'K'),
     76: ('4C', '114', 'L'),
     77: ('4D', '115', 'M'),
     78: ('4E', '116', 'N'),
     79: ('4F', '117', 'O'),
     80: ('50', '120', 'P'),
     81: ('51', '121', 'Q'),
     82: ('52', '122', 'R'),
     83: ('53', '123', 'S'),
     84: ('54', '124', 'T'),
     85: ('55', '125', 'U'),
     86: ('56', '126', 'V'),
     87: ('57', '127', 'W'),
     88: ('58', '130', 'X'),
     89: ('59', '131', 'Y'),
     90: ('5A', '132', 'Z'),
     91: ('5B', '133', '\x5B'),
     92: ('5C', '134', '\x5C'),
     93: ('5D', '135', '\x5D'),
     94: ('5E', '136', r'^'),
     95: ('5F', '137', r'_'),
     96: ('60', '140', '\x60'),
     97: ('61', '141', 'a'),
     98: ('62', '142', 'b'),
     99: ('63', '143', 'c'),
     100: ('64', '144', 'd'),
     101: ('65', '145', 'e'),
     102: ('66', '146', 'f'),
     103: ('67', '147', 'g'),
     104: ('68', '150', 'h'),
     105: ('69', '151', 'I'),
     106: ('6A', '152', 'j'),
     107: ('6B', '153', 'k'),
     108: ('6C', '154', 'l'),
     109: ('6D', '155', 'm'),
     110: ('6E', '156', 'n'),
     111: ('6F', '157', 'o'),
     112: ('70', '160', 'p'),
     113: ('71', '161', 'q'),
     114: ('72', '162', 'r'),
     115: ('73', '163', 's'),
     116: ('74', '164', 't'),
     117: ('75', '165', 'u'),
     118: ('76', '166', 'v'),
     119: ('77', '167', 'w'),
     120: ('78', '170', 'x'),
     121: ('79', '171', 'y'),
     122: ('7A', '172', 'z'),
     123: ('7B', '173', '\x7B'),
     124: ('7C', '174', r'|'),
     125: ('7D', '175', '\x7D'),
     126: ('7E', '176', r'~')
 }
Definition at line 388 of file strtools.py.
string RADIATION = r''
Definition at line 5231 of file strtools.py.
tuple RECYCLE = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
Definition at line 5036 of file strtools.py.
string RIGHT = r''
Definition at line 5232 of file strtools.py.
tuple SCIENCE = (r'', r'', r'', r'', r'', r'', r'', r'', r'')
Definition at line 5039 of file strtools.py.
string SQUARE = '\u20de'
Definition at line 518 of file strtools.py.
tuple SUPERSCRIPT_NUM = (r'', r'', r'', r'', r'', r'', r'', r'', r'')
Definition at line 5042 of file strtools.py.
string TELEPHONE = r''
Definition at line 5233 of file strtools.py.
string TOXIC = r''
Definition at line 5234 of file strtools.py.
tuple TRAILING_SURROGATE = re.compile(r'[\udc00-\udfff]')
Definition at line 374 of file strtools.py.
tuple TRANS_TAB_BUBBLE2TEST = str.maketrans(BUBBLE_TEXT, PLAIN_TEXT)
Definition at line 531 of file strtools.py.
tuple TRANS_TAB_TEXT2BUBBLE = str.maketrans(PLAIN_TEXT, BUBBLE_TEXT)
Definition at line 532 of file strtools.py.
string UP = r''
Definition at line 5235 of file strtools.py.
int UPPER_LIMIT_ASCII_CTRL = 31
Definition at line 377 of file strtools.py.
int UPPER_LIMIT_ASCII_EXT = 255
Definition at line 381 of file strtools.py.
int UPPER_LIMIT_ASCII_PRNT = 127
Definition at line 379 of file strtools.py.
int UPPER_LIMIT_MS_LATIN1 = 159
Definition at line 383 of file strtools.py.
int UPPER_LIMIT_UNICODE = 1114111
Definition at line 385 of file strtools.py.
int UPPER_LIMIT_UTF8 = 65535
Definition at line 384 of file strtools.py.
string WARNING = r''
Definition at line 5236 of file strtools.py.
tuple ZODIAC = (r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'', r'')
Definition at line 5045 of file strtools.py.
dictionary ZODIAC_SIGNS
Initial value:
 = {
     'Aries': '',
     'Taurus': '',
     'Gemini': '',
     'Cancer': '',
     'Leo': '',
     'Virgo': '',
     'Libra': '',
     'Scorpio': '',
     'Sagittarius': '',
     'Capricorn': '',
     'Aquarius': '',
     'Pisces': ''
 }
Definition at line 5048 of file strtools.py.