PyBooster: lib.electronics Namespace Reference
lib.electronics Namespace Reference
Functions
def current
def power
def resistance
def voltage
Variables
list __all__
string OHMS = 'Ω'
Function Documentation
def lib.electronics.current (_voltage)
Definition at line 51 of file electronics.py.
Referenced by display_linked_stack().
def lib.electronics.power (_current)
Definition at line 66 of file electronics.py.
Referenced by mod_pow(), mod_pow_longlong(), pow_ten(), pow_ten_int(), pow_ten_neg(), pow_ten_negf(), pow_ten_negl(), pow_ten_pos(), pow_ten_posf(), pow_ten_posl(), pow_tenl(), signed_pow(), signed_powl(), and unsigned_pow().
def lib.electronics.resistance (_voltage)
Definition at line 56 of file electronics.py.
def lib.electronics.voltage (_current)
Definition at line 61 of file electronics.py.
Variable Documentation
list __all__
Initial value:
 = [
     # CONSTANTS
     'OHMS',
     # FUNCTIONS
     'current',
     'resistance',
     'voltage',
     'power',
 ]
Definition at line 31 of file electronics.py.
string OHMS = 'Ω'
Definition at line 45 of file electronics.py.