PyBooster: lib.timeutil Namespace Reference
lib.timeutil Namespace Reference
Functions
def clock ()
def currentseason
def date ()
def date_time ()
def dateandtime ()
def day ()
def fulltime ()
def hour ()
def istoday
def istodayfriday ()
def istodaymonday ()
def istodaysaturday ()
def istodaysunday ()
def istodaythursday ()
def istodaytuesday ()
def istodaywednesday ()
def isyear
def month ()
def sysuptime ()
def weekday ()
def year ()
Variables
list __all__
tuple SEASONS
tuple YEAR = int(pytime.strftime('%Y'))
Function Documentation
def lib.timeutil.clock (str)
Return the time
Definition at line 178 of file timeutil.py.
Referenced by rand16384str(), randalphanumstr(), randalphastr(), randomint(), randomlong(), randstr(), and randstrx().
def lib.timeutil.currentseason (_hemisphere)
Definition at line 134 of file timeutil.py.
def lib.timeutil.date (str)
Return the date
Definition at line 173 of file timeutil.py.
def lib.timeutil.date_time (str)
Return the date and time
Definition at line 183 of file timeutil.py.
def lib.timeutil.dateandtime (str)
Return the date and time
Definition at line 188 of file timeutil.py.
def lib.timeutil.day (str)
Return the day
Definition at line 193 of file timeutil.py.
def lib.timeutil.fulltime (str)
Return the time, month, year, etc.
Definition at line 203 of file timeutil.py.
def lib.timeutil.hour (str)
Return the hour
Definition at line 198 of file timeutil.py.
def lib.timeutil.istoday (_weekday)
Definition at line 84 of file timeutil.py.
def lib.timeutil.istodayfriday (bool)
Test if today is Friday
Definition at line 114 of file timeutil.py.
def lib.timeutil.istodaymonday (bool)
Test if today is Monday
Definition at line 94 of file timeutil.py.
def lib.timeutil.istodaysaturday (bool)
Test if today is Saturday
Definition at line 119 of file timeutil.py.
def lib.timeutil.istodaysunday (bool)
Test if today is Sunday
Definition at line 89 of file timeutil.py.
def lib.timeutil.istodaythursday (bool)
Test if today is Thursday
Definition at line 109 of file timeutil.py.
def lib.timeutil.istodaytuesday (bool)
Test if today is Tuesday
Definition at line 99 of file timeutil.py.
def lib.timeutil.istodaywednesday (bool)
Test if today is Wednesday
Definition at line 104 of file timeutil.py.
def lib.timeutil.isyear (_year)
Definition at line 124 of file timeutil.py.
def lib.timeutil.month (str)
Return the name of the month
Definition at line 163 of file timeutil.py.
def lib.timeutil.sysuptime (str)
Return the system's uptime
Definition at line 208 of file timeutil.py.
def lib.timeutil.weekday (str)
Return the name of the weekday
Definition at line 158 of file timeutil.py.
def lib.timeutil.year (str)
Return the year
Definition at line 168 of file timeutil.py.
Variable Documentation
list __all__
Initial value:
 = [
     # CONSTANTS
     'SEASONS',
     'YEAR',
     # BOOLEAN FUNCTIONS
     'istoday',
     'istodaysunday',
     'istodaymonday',
     'istodaytuesday',
     'istodaywednesday',
     'istodaythursday',
     'istodayfriday',
     'istodaysaturday',
     'isyear',
     # FUNCTIONS
     'currentseason',
     'weekday',
     'month',
     'year',
     'date',
     'clock',
     'date_time',
     'dateandtime',
     'day',
     'hour',
     'fulltime',
     'sysuptime',
 ]
Definition at line 37 of file timeutil.py.
tuple SEASONS
Initial value:
 = (
     r'spring',
     r'summer',
     r'autumn',
     r'winter'
 )
Definition at line 70 of file timeutil.py.
tuple YEAR = int(pytime.strftime('%Y'))
Definition at line 78 of file timeutil.py.