PyBooster: pybooster.timeutil Namespace Reference
pybooster.timeutil Namespace Reference
Functions
def clock ()
Return the time.
def currentseason
Return the current season.
def date ()
Return the date.
def date_time ()
Return the date and time.
def dateandtime ()
Return the date and time.
def day ()
Return the day.
def fulltime ()
Return the time, month, year, etc.
def hour ()
Return the ho.
def istoday
Test if today is a particular weekday.
def istodayfriday ()
Test if today is Friday.
def istodaymonday ()
Test if today is Monday.
def istodaysaturday ()
Test if today is Saturday.
def istodaysunday ()
Test if today is Sunday.
def istodaythursday ()
Test if today is Thursday.
def istodaytuesday ()
Test if today is Tuesday.
def istodaywednesday ()
Test if today is Wednesday.
def isyear
Test if today is a particular yea.
def month ()
Return the name of the month.
def sysuptime ()
Return the system's uptime.
def weekday ()
Return the name of the weekday.
def year ()
Return the yea.
Variables
list __all__
tuple SEASONS
tuple YEAR = int(pytime.strftime('%Y'))
Detailed Description
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.20
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
The PyBooster Library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Function Documentation
def pybooster.timeutil.clock (str)
Return the time.
Definition at line 187 of file timeutil.py.
Referenced by rand16384str(), randalphanumstr(), randalphastr(), randomint(), randomlong(), randstr(), and randstrx().
def pybooster.timeutil.currentseason (_hemisphere)
Return the current season.
Definition at line 137 of file timeutil.py.
def pybooster.timeutil.date (str)
Return the date.
Definition at line 182 of file timeutil.py.
def pybooster.timeutil.date_time (str)
Return the date and time.
Definition at line 192 of file timeutil.py.
def pybooster.timeutil.dateandtime (str)
Return the date and time.
Definition at line 197 of file timeutil.py.
def pybooster.timeutil.day (str)
Return the day.
Definition at line 202 of file timeutil.py.
def pybooster.timeutil.fulltime (str)
Return the time, month, year, etc.
Definition at line 212 of file timeutil.py.
def pybooster.timeutil.hour (str)
Return the ho.
Definition at line 207 of file timeutil.py.
def pybooster.timeutil.istoday (_weekday)
Test if today is a particular weekday.
Definition at line 84 of file timeutil.py.
def pybooster.timeutil.istodayfriday (bool)
Test if today is Friday.
Definition at line 114 of file timeutil.py.
def pybooster.timeutil.istodaymonday (bool)
Test if today is Monday.
Definition at line 94 of file timeutil.py.
def pybooster.timeutil.istodaysaturday (bool)
Test if today is Saturday.
Definition at line 119 of file timeutil.py.
def pybooster.timeutil.istodaysunday (bool)
Test if today is Sunday.
Definition at line 89 of file timeutil.py.
def pybooster.timeutil.istodaythursday (bool)
Test if today is Thursday.
Definition at line 109 of file timeutil.py.
def pybooster.timeutil.istodaytuesday (bool)
Test if today is Tuesday.
Definition at line 99 of file timeutil.py.
def pybooster.timeutil.istodaywednesday (bool)
Test if today is Wednesday.
Definition at line 104 of file timeutil.py.
def pybooster.timeutil.isyear (_year)
Test if today is a particular yea.
Definition at line 124 of file timeutil.py.
def pybooster.timeutil.month (str)
Return the name of the month.
Definition at line 172 of file timeutil.py.
def pybooster.timeutil.sysuptime (str)
Return the system's uptime.
Definition at line 217 of file timeutil.py.
def pybooster.timeutil.weekday (str)
Return the name of the weekday.
Definition at line 167 of file timeutil.py.
def pybooster.timeutil.year (str)
Return the yea.
Definition at line 177 of file timeutil.py.
Variable Documentation
list __all__
Initial value:
 = [
     # CONSTANTS
     'SEASONS',
     'YEAR',
     # BOOLEAN FUNCTIONS
     'istoday',
     'istodaysunday',
     'istodaymonday',
     'istodaytuesday',
     'istodaywednesday',
     'istodaythursday',
     'istodayfriday',
     'istodaysaturday',
     'isyear',
     # FUNCTIONS
     'currentseason',
     'weekday',
     'month',
     'year',
     'date',
     'clock',
     'date_time',
     'dateandtime',
     'day',
     'hour',
     'fulltime',
     'sysuptime',
 ]
Definition at line 36 of file timeutil.py.
tuple SEASONS
Initial value:
 = (
     r'spring',
     r'summer',
     r'autumn',
     r'winter'
 )
Definition at line 69 of file timeutil.py.
tuple YEAR = int(pytime.strftime('%Y'))
Definition at line 77 of file timeutil.py.