PyBooster: physics.c File Reference
physics.c File Reference
Physics Functions.
#include "physics.h"
Functions
double acceleration_given_force (const double force, const double mass)
double acceleration_given_velocity (const double velocity_change, const double time)
double density (const double mass, const double volume)
double distance (const double speed, const double time)
double force (const double mass, const double acceleration)
double freefall_distance (const double time_sec)
double freefall_velocity (const double time_sec)
double gravitational_intensity (const double distance)
double impulse (const double force, const double time)
double impulse_given_mass_velocity (const double mass, const double velocity)
double instantaneous_speed (const double acceleration, const double time)
double kinetic_energy (const double mass, const double velocity)
double momentum (const double mass, const double velocity)
double potential_energy (const double mass_kg, const double height_meters)
double power (const double force, const double distance, const double time)
double power_given_work_time (const double work, const double time)
double pressure (const double force, const double area)
double speed (const double distance, const double time)
double work (const double force, const double distance)
Variables
const double ATMOSPHERIC_PRESSURE = 101.0
const long double ATMOSPHERIC_PRESSUREl = 101.0L
const double ESCAPE_VELOCITY = 8000000.0
const long double ESCAPE_VELOCITYl = 8000000.0L
const double G = 9.8
const long double Gl = 9.8L
Detailed Description
Physics Functions.
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.18
DESCRIPTION
Functions related to physics calculations
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file physics.c.
Function Documentation
double acceleration_given_force (const double force, const double mass)
Return the acceleration given force and mass
Parameters
[in] force
[in] mass
Returns
Acceleration
Definition at line 123 of file physics.c.
double acceleration_given_velocity (const double velocity_change, const double time)
Return the acceleration given time and change in velocity
Parameters
[in] velocity_change
[in] time
Returns
Acceleration
Definition at line 111 of file physics.c.
double density (const double mass, const double volume)
Return density given mass and volume
Parameters
[in] mass
[in] volume
Returns
Density
Definition at line 63 of file physics.c.
double distance (const double speed, const double time)
Return distance given speed and time
Parameters
[in] speed
[in] time
Returns
Distance
Definition at line 87 of file physics.c.
double force (const double mass, const double acceleration)
Return the force given mass and acceleration
Parameters
[in] mass
[in] acceleration Amount of acceleration of the mass
Returns
Force
Definition at line 147 of file physics.c.
Referenced by physics_impulse(), and physics_pressure().
double freefall_distance (const double time_sec)
Return distance fallen during freefall given time (seconds)
Parameters
[in] time_sec Time since falling
Returns
Distance fallen at the given time
Definition at line 277 of file physics.c.
References G.
double freefall_velocity (const double time_sec)
Return the freefall velocity given time (seconds)
Parameters
[in] time_sec Time since falling
Returns
Free-fall velocity at the given time
Definition at line 266 of file physics.c.
References G.
double gravitational_intensity (const double distance)
Return gravitational intensity given distance
Parameters
[in] distance Distance between two objects
Returns
Gravitational intensity at the given distance
Definition at line 243 of file physics.c.
double impulse (const double force, const double time)
Return impulse given force and time
Parameters
[in] force
[in] time Amount of time the force was exerted
Returns
Impulse
Definition at line 159 of file physics.c.
double impulse_given_mass_velocity (const double mass, const double velocity)
Return impulse given velocity and a change in mass
Parameters
[in] mass
[in] velocity
Returns
Impulse
Definition at line 171 of file physics.c.
double instantaneous_speed (const double acceleration, const double time)
Return instantaneous speed given acceleration and time
Parameters
[in] acceleration Acceleration at the given time
[in] time Time of the given instance
Returns
Speed at the given time and acceleration
Definition at line 255 of file physics.c.
double kinetic_energy (const double mass, const double velocity)
Return the kinetic-energy given mass and velocity
Parameters
[in] mass Mass of some object
[in] velocity Velocity of the object
Returns
Kinetic energy of an object at a given velocity and mass
Definition at line 220 of file physics.c.
double momentum (const double mass, const double velocity)
Return momentum given mass and velocity
Parameters
[in] mass
[in] velocity Amount of directional speed of the mass
Returns
Momentum
Definition at line 135 of file physics.c.
double potential_energy (const double mass_kg, const double height_meters)
Return potential-energy given mass (kg) and height (meters) of an object on Earth
Parameters
[in] mass_kg Mass of some object
[in] height_meters height from some surface
Returns
Potential energy of an object on Earth at a given height and mass
Definition at line 232 of file physics.c.
References G.
double power (const double force, const double distance, const double time)
Return power given force, distance, and time
Parameters
[in] force
[in] distance Amount of distance the force was exerted
[in] time Amount of time the force was exerted
Returns
Power (Watts)
Definition at line 196 of file physics.c.
Referenced by mod_pow(), mod_pow_longlong(), pow_ten(), pow_ten_int(), pow_ten_neg(), pow_ten_negf(), pow_ten_negl(), pow_ten_pos(), pow_ten_posf(), pow_ten_posl(), pow_tenl(), signed_pow(), signed_powl(), and unsigned_pow().
double power_given_work_time (const double work, const double time)
Return power given work and time
Parameters
[in] work Work (Newtons)
[in] time Amount of time the work was exerted
Returns
Power (Watts)
Definition at line 208 of file physics.c.
double pressure (const double force, const double area)
Return pressure given force and area
Parameters
[in] force
[in] area Area of the acting force
Returns
Pressure
Definition at line 75 of file physics.c.
double speed (const double distance, const double time)
Return speed/velocity given the distance and time
Parameters
[in] distance
[in] time
Returns
Speed
Definition at line 99 of file physics.c.
Referenced by physics_distance().
double work (const double force, const double distance)
Return work given force and distance
Parameters
[in] force
[in] distance Amount of distance the force was exerted
Returns
Work exerted
Definition at line 183 of file physics.c.
Variable Documentation
const double ATMOSPHERIC_PRESSURE = 101.0
Earth's Atmospheric Pressure
Definition at line 40 of file physics.c.
const long double ATMOSPHERIC_PRESSUREl = 101.0L
Earth's Atmospheric Pressure
Definition at line 42 of file physics.c.
const double ESCAPE_VELOCITY = 8000000.0
Earth's Escape Velocity
Definition at line 44 of file physics.c.
const long double ESCAPE_VELOCITYl = 8000000.0L
Earth's Escape Velocity
Definition at line 46 of file physics.c.
const double G = 9.8
Earth's Gravitational Constant
Definition at line 48 of file physics.c.
Referenced by freefall_distance(), freefall_velocity(), and potential_energy().
const long double Gl = 9.8L
Earth's Gravitational Constant
Definition at line 50 of file physics.c.