PyBooster: pychemistry.c File Reference
pychemistry.c File Reference
Chemistry-related Functions.
#include "PY_MACROS.h"
#include "chemistry.h"
Macros
#define MODINIT PyMODINIT_FUNC PyInit_chemistry(void)
#define MODNAME "chemistry"
Functions
MODINIT __attribute__ ((flatten, hot))
static PyObject * chemistry_iselement (FUNCARGS)
static PyObject * chemistry_pka (FUNCARGS)
static PyObject * chemistry_pkb (FUNCARGS)
if (return m==(PyObject *) NULL)
PyDoc_STRVAR (chemistry_pka_docstring,"pka(ka: float) -> float\nCalculate the pKa from Ka (Acid Dissociation Constant)")
PyDoc_STRVAR (chemistry_pkb_docstring,"pkb(kb: float) -> float\nCalculate the pKb from Kb (Base Dissociation Constant)")
PyDoc_STRVAR (chemistry_iselement_docstring,"iselement(name: str) -> bool\nCheck if the string is a name of a chemical element")
PyModule_AddStringConstant (m,"__author__", __author__)
PyModule_AddStringConstant (m,"__version__", __version__)
Variables
m = PyModule_Create(&module)
MODINIT
static struct PyModuleDef module
static char module_docstring [32]
static PyMethodDef module_methods [4]
Detailed Description
Chemistry-related Functions.
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.20
DESCRIPTION
This is a Python3 module that uses functions from chemistry.c Chemistry-specific functions that perform calculations or truth-tests
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file pychemistry.c.
Macro Definition Documentation
#define MODINIT PyMODINIT_FUNC PyInit_chemistry(void)
Definition at line 38 of file pychemistry.c.
#define MODNAME "chemistry"
Definition at line 37 of file pychemistry.c.
Function Documentation
MODINIT __attribute__ ((flatten, hot))
static PyObject * chemistry_iselement (FUNCARGS) static
Definition at line 124 of file pychemistry.c.
References ASSERT_STRING_ARG, and iselement().
static PyObject* chemistry_pka (FUNCARGS) static
static PyObject * chemistry_pkb (FUNCARGS) static
Definition at line 117 of file pychemistry.c.
References ASSERT_DOUBLE_ARG, double2float, and pkb().
if (return m = = (PyObject *)NULL)
Definition at line 102 of file pychemistry.c.
PyDoc_STRVAR (chemistry_pka_docstring , "pka(ka: float) -> float\nCalculate the pKa from Ka (Acid Dissociation Constant)")
PyDoc_STRVAR (chemistry_pkb_docstring , "pkb(kb: float) -> float\nCalculate the pKb from Kb (Base Dissociation Constant)")
PyDoc_STRVAR (chemistry_iselement_docstring , "iselement(name: str) -> bool\nCheck if the string is a name of a chemical element")
PyModule_AddStringConstant (m , "__author__" , __author__)
PyModule_AddStringConstant (m , "__version__" , __version__)
Variable Documentation
m = PyModule_Create(&module)
Definition at line 95 of file pychemistry.c.
Referenced by LOG2().
MODINIT
Initial value:
{
    PyObject *m
Definition at line 93 of file pychemistry.c.
struct PyModuleDef module static
Initial value:
= {
    PyModuleDef_HEAD_INIT,
    MODNAME,
    module_docstring,
    -1,
    module_methods,
    NULL,
    NULL,
    NULL,
    NULL
}
Definition at line 80 of file pychemistry.c.
char module_docstring[32] static
Initial value:
=
    "Chemistry-related Functions"
Definition at line 59 of file pychemistry.c.
PyMethodDef module_methods[4] static
Initial value:
= {
    {"pka", (PyCFunction)chemistry_pka, METH_VARARGS, chemistry_pka_docstring},
    {"pkb", (PyCFunction)chemistry_pkb, METH_VARARGS, chemistry_pkb_docstring},
    {"iselement", (PyCFunction)chemistry_iselement, METH_VARARGS, chemistry_iselement_docstring},
    {NULL, NULL, 0, NULL}
}
Definition at line 72 of file pychemistry.c.