PyBooster: pymathfunc.c File Reference
pymathfunc.c File Reference
Math Functions.
#include "PY_MACROS.h"
#include "mathfunc.h"
Macros
#define MODINIT PyMODINIT_FUNC PyInit_mathfunc(void)
#define MODNAME "mathfunc"
Functions
MODINIT __attribute__ ((flatten, hot))
if (return m==(PyObject *) NULL)
static PyObject * mathfunc_acot (FUNCARGS)
static PyObject * mathfunc_acoth (FUNCARGS)
static PyObject * mathfunc_acsc (FUNCARGS)
static PyObject * mathfunc_acsch (FUNCARGS)
static PyObject * mathfunc_arccot (FUNCARGS)
static PyObject * mathfunc_arccoth (FUNCARGS)
static PyObject * mathfunc_arccsc (FUNCARGS)
static PyObject * mathfunc_arccsch (FUNCARGS)
static PyObject * mathfunc_arcexcot (FUNCARGS)
static PyObject * mathfunc_arcexcoth (FUNCARGS)
static PyObject * mathfunc_arcexcsc (FUNCARGS)
static PyObject * mathfunc_arcexcsch (FUNCARGS)
static PyObject * mathfunc_arcexsec (FUNCARGS)
static PyObject * mathfunc_arcexsech (FUNCARGS)
static PyObject * mathfunc_arcsec (FUNCARGS)
static PyObject * mathfunc_arcsech (FUNCARGS)
static PyObject * mathfunc_arcvercos (FUNCARGS)
static PyObject * mathfunc_arcvercosh (FUNCARGS)
static PyObject * mathfunc_arcversin (FUNCARGS)
static PyObject * mathfunc_arcversinh (FUNCARGS)
static PyObject * mathfunc_asec (FUNCARGS)
static PyObject * mathfunc_asech (FUNCARGS)
static PyObject * mathfunc_bit_length (FUNCARGS)
static PyObject * mathfunc_cos_arcsin (FUNCARGS)
static PyObject * mathfunc_cos_arctan (FUNCARGS)
static PyObject * mathfunc_cot (FUNCARGS)
static PyObject * mathfunc_coth (FUNCARGS)
static PyObject * mathfunc_crd (FUNCARGS)
static PyObject * mathfunc_csc (FUNCARGS)
static PyObject * mathfunc_csch (FUNCARGS)
static PyObject * mathfunc_doublefactorial (FUNCARGS)
static PyObject * mathfunc_excot (FUNCARGS)
static PyObject * mathfunc_excoth (FUNCARGS)
static PyObject * mathfunc_excsc (FUNCARGS)
static PyObject * mathfunc_excsch (FUNCARGS)
static PyObject * mathfunc_exsec (FUNCARGS)
static PyObject * mathfunc_exsech (FUNCARGS)
static PyObject * mathfunc_factorial (FUNCARGS)
static PyObject * mathfunc_fib (FUNCARGS)
static PyObject * mathfunc_float_diff (FUNCARGS)
static PyObject * mathfunc_fma (FUNCARGS)
static PyObject * mathfunc_fpclassify (FUNCARGS)
static PyObject * mathfunc_hacoversin (FUNCARGS)
static PyObject * mathfunc_haversin (FUNCARGS)
static PyObject * mathfunc_heptagonal_num (FUNCARGS)
static PyObject * mathfunc_hexagonal_num (FUNCARGS)
static PyObject * mathfunc_iscomposite (FUNCARGS)
static PyObject * mathfunc_isfloatsquare (FUNCARGS)
static PyObject * mathfunc_isheptagonal (FUNCARGS)
static PyObject * mathfunc_ishexagonal (FUNCARGS)
static PyObject * mathfunc_ismersennenumber (FUNCARGS)
static PyObject * mathfunc_ismersenneprime (FUNCARGS)
static PyObject * mathfunc_ispoweroftwo (FUNCARGS)
static PyObject * mathfunc_isprime (FUNCARGS)
static PyObject * mathfunc_issquare (FUNCARGS)
static PyObject * mathfunc_istriangular (FUNCARGS)
static PyObject * mathfunc_mersenne_num (FUNCARGS)
static PyObject * mathfunc_pentatope_num (FUNCARGS)
static PyObject * mathfunc_pow2 (FUNCARGS)
static PyObject * mathfunc_pow_ten (FUNCARGS)
static PyObject * mathfunc_pow_ten_int (FUNCARGS)
static PyObject * mathfunc_pow_ten_int_fast (FUNCARGS)
static PyObject * mathfunc_pow_ten_neg (FUNCARGS)
static PyObject * mathfunc_pow_ten_pos (FUNCARGS)
static PyObject * mathfunc_pronic (FUNCARGS)
static PyObject * mathfunc_quadfactorial (FUNCARGS)
static PyObject * mathfunc_sec (FUNCARGS)
static PyObject * mathfunc_sech (FUNCARGS)
static PyObject * mathfunc_sin_arcsec (FUNCARGS)
static PyObject * mathfunc_sin_arctan (FUNCARGS)
static PyObject * mathfunc_sinpi (FUNCARGS)
static PyObject * mathfunc_squareroot (FUNCARGS)
static PyObject * mathfunc_superfactorial (FUNCARGS)
static PyObject * mathfunc_tetrahedral_num (FUNCARGS)
static PyObject * mathfunc_triangular_num (FUNCARGS)
static PyObject * mathfunc_vercos (FUNCARGS)
static PyObject * mathfunc_vercosh (FUNCARGS)
static PyObject * mathfunc_versin (FUNCARGS)
static PyObject * mathfunc_versinh (FUNCARGS)
PyDoc_STRVAR (mathfunc_pow2_docstring,"pow2(num: int) -> int\nReturn the power of 2^num, where \"num\" is a positive integer")
PyDoc_STRVAR (mathfunc_pow_ten_docstring,"pow_ten(num: int) -> float\nReturn the power of 10^num")
PyDoc_STRVAR (mathfunc_pow_ten_int_docstring,"pow_ten_int(num: int) -> int\nReturn the power of 10^num, where 'num' is a positive integer")
PyDoc_STRVAR (mathfunc_pow_ten_int_fast_docstring,"pow_ten_int_fast(num: int) -> int\nReturn the power of 10^num ('num' is a positive integer less than 18)")
PyDoc_STRVAR (mathfunc_pow_ten_pos_docstring,"pow_ten_pos(num: int) -> float\nReturn the power of 10^num for positive exponents")
PyDoc_STRVAR (mathfunc_pow_ten_neg_docstring,"pow_ten_neg(num: int) -> float\nReturn the power of 10^num for negative exponents")
PyDoc_STRVAR (mathfunc_squareroot_docstring,"squareroot(num: float) -> float\nReturn the Square-Root of a positive number")
PyDoc_STRVAR (mathfunc_factorial_docstring,"factorial(num: int) -> float\nFactorial (n!)")
PyDoc_STRVAR (mathfunc_doublefactorial_docstring,"doublefactorial(num: int) -> float\nDouble Factorial (n!!)")
PyDoc_STRVAR (mathfunc_quadfactorial_docstring,"quadfactorial(num: int) -> float\nQuadruple Factorial - (2n)!/n!")
PyDoc_STRVAR (mathfunc_superfactorial_docstring,"superfactorial(num: int) -> float\nSuper-Factorial")
PyDoc_STRVAR (mathfunc_pronic_docstring,"pronic(num: int) -> int\nReturn the Nth Pronic number")
PyDoc_STRVAR (mathfunc_fib_docstring,"fib(num: int) -> int\nFibonacci Number Generator\nReturn the specified Fibonacci Number")
PyDoc_STRVAR (mathfunc_triangular_num_docstring,"triangular_num(num: int) -> int\nReturn the Nth Triangular Number")
PyDoc_STRVAR (mathfunc_hexagonal_num_docstring,"hexagonal_num(num: int) -> int\nReturn the Nth Hexagonal Number")
PyDoc_STRVAR (mathfunc_heptagonal_num_docstring,"heptagonal_num(num: int) -> int\nReturn the Nth Heptagonal Number")
PyDoc_STRVAR (mathfunc_tetrahedral_num_docstring,"tetrahedral_num(num: int) -> int\nReturn the Nth Tetrahedral Number")
PyDoc_STRVAR (mathfunc_pentatope_num_docstring,"pentatope_num(num: int) -> int\nReturn the Nth Pentatope Number")
PyDoc_STRVAR (mathfunc_mersenne_num_docstring,"mersenne_num(num: int) -> int\nReturn the Nth Mersenne Number")
PyDoc_STRVAR (mathfunc_sinpi_docstring,"sinpi(num: float) -> float\nReturn the Pi Sine of the given number; return 0.0 on error")
PyDoc_STRVAR (mathfunc_crd_docstring,"crd(radians: float) -> float\nReturn the Chord")
PyDoc_STRVAR (mathfunc_acot_docstring,"acot(radians: float) -> float\nReturn the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))")
PyDoc_STRVAR (mathfunc_arccot_docstring,"arccot(radians: float) -> float\nReturn the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))")
PyDoc_STRVAR (mathfunc_acoth_docstring,"acoth(radians: float) -> float\nReturn the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))")
PyDoc_STRVAR (mathfunc_arccoth_docstring,"arccoth(radians: float) -> float\nReturn the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))")
PyDoc_STRVAR (mathfunc_coth_docstring,"coth(radians: float) -> float\nReturn the Hyperbolic Cotangent (coth(x) == 1/tanh(x))")
PyDoc_STRVAR (mathfunc_cot_docstring,"cot(radians: float) -> float\nReturn the Cotangent (cot(x) == 1/tan(x))")
PyDoc_STRVAR (mathfunc_acsc_docstring,"acsc(radians: float) -> float\nReturn the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))")
PyDoc_STRVAR (mathfunc_arccsc_docstring,"arccsc(radians: float) -> float\nReturn the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))")
PyDoc_STRVAR (mathfunc_acsch_docstring,"acsch(radians: float) -> float\nReturn the Hyperbolic Arc-Cosecant (acsch(x)||arccsch(x) == asinh(1/x))")
PyDoc_STRVAR (mathfunc_arccsch_docstring,"arccsch(radians: float) -> float\nReturn the Hyperbolic Arc-Cosecant (acsc(x)||arccsch(x) == asinh(1/x))")
PyDoc_STRVAR (mathfunc_csch_docstring,"csch(radians: float) -> float\nReturn the Hyperbolic Cosecant (csch(x) == 1/sinh(x))")
PyDoc_STRVAR (mathfunc_csc_docstring,"csc(radians: float) -> float\nReturn the Cosecant (csc(x) == 1/sin(x))")
PyDoc_STRVAR (mathfunc_asec_docstring,"asec(radians: float) -> float\nReturn the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))")
PyDoc_STRVAR (mathfunc_arcsec_docstring,"arcsec(radians: float) -> float\nReturn the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))")
PyDoc_STRVAR (mathfunc_asech_docstring,"asech(radians: float) -> float\nReturn the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))")
PyDoc_STRVAR (mathfunc_arcsech_docstring,"arcsech(radians: float) -> float\nReturn the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))")
PyDoc_STRVAR (mathfunc_sech_docstring,"sech(radians: float) -> float\nReturn the Hyperbolic Secant (sech(x) == 1/cosh(x))")
PyDoc_STRVAR (mathfunc_sec_docstring,"sec(radians: float) -> float\nReturn the Secant (sec(x) == 1/cos(x))")
PyDoc_STRVAR (mathfunc_arcversin_docstring,"arcversin(radians: float) -> float\nReturn the Arc-Versed Sine (arcversin(x) == 1 - acos(x))")
PyDoc_STRVAR (mathfunc_arcversinh_docstring,"arcversinh(radians: float) -> float\nReturn the Hyperbolic Arc-Versed Sine (arcversinh(x) == 1 - acosh(x))")
PyDoc_STRVAR (mathfunc_versinh_docstring,"versinh(radians: float) -> float\nReturn the Hyperbolic Versed Sine (versinh(x) == 1 - cosh(x))")
PyDoc_STRVAR (mathfunc_versin_docstring,"versin(radians: float) -> float\nReturn the Versed Sine (versin(x) == 1 - cos(x))")
PyDoc_STRVAR (mathfunc_arcvercos_docstring,"arcvercos(radians: float) -> float\nReturn the Arc-Versed Cosine (arcvercos(x) == 1 - asin(x))")
PyDoc_STRVAR (mathfunc_arcvercosh_docstring,"arcvercosh(radians: float) -> float\nReturn the Hyperbolic Arc-Versed Cosine (arcvercosh(x) == 1 - asinh(x))")
PyDoc_STRVAR (mathfunc_vercosh_docstring,"vercosh(radians: float) -> float\nReturn the Hyperbolic Versed Cosine (vercosh(x) == 1 - sinh(x))")
PyDoc_STRVAR (mathfunc_vercos_docstring,"vercos(radians: float) -> float\nReturn the Versed Cosine (vercos(x) == 1 - sin(x))")
PyDoc_STRVAR (mathfunc_haversin_docstring,"haversin(radians: float) -> float\nReturn the Haversine (haversin(x) == 0.5*(1 - cos(x)))")
PyDoc_STRVAR (mathfunc_hacoversin_docstring,"hacoversin(radians: float) -> float\nReturn the Hacoversine (hacoversin(x) == 0.5*(1 - sin(x)))")
PyDoc_STRVAR (mathfunc_arcexcot_docstring,"arcexcot(radians: float) -> float\nReturn the Arc-External Cotangent (arcexcot(x) == atan(1/(x+1)))")
PyDoc_STRVAR (mathfunc_arcexcoth_docstring,"arcexcoth(radians: float) -> float\nReturn the Hyperbolic Arc-External Cotangent [arcexcoth(x) == (1/atanh(x)-1)]")
PyDoc_STRVAR (mathfunc_excoth_docstring,"excoth(radians: float) -> float\nReturn the External Hyperbolic Cotangent [excoth(x) == (1/tanh(x)-1)]")
PyDoc_STRVAR (mathfunc_excot_docstring,"excot(radians: float) -> float\nReturn the External Cotangent [excot(x) == (1/tan(x))-1 == cot(x)-1]")
PyDoc_STRVAR (mathfunc_arcexcsc_docstring,"arcexcsc(radians: float) -> float\nReturn the Arc-External Cosecant (arcexcsc(x) == asin(1/(x+1)))")
PyDoc_STRVAR (mathfunc_arcexcsch_docstring,"arcexcsch(radians: float) -> float\nReturn the Hyperbolic Arc-External Cosecant [arcexcsch(x) == (1/asinh(x)-1)]")
PyDoc_STRVAR (mathfunc_excsch_docstring,"excsch(radians: float) -> float\nReturn the External Hyperbolic Cosecant [excsch(x) == (1/sinh(x)-1)]")
PyDoc_STRVAR (mathfunc_excsc_docstring,"excsc(radians: float) -> float\nReturn the External Cosecant [excsc(x) == (1/sin(x))-1 == csc(x)-1]")
PyDoc_STRVAR (mathfunc_arcexsec_docstring,"arcexsec(radians: float) -> float\nReturn the Arc-External Secant (arcexsec(x) == acos(1/(x+1)))")
PyDoc_STRVAR (mathfunc_arcexsech_docstring,"arcexsech(radians: float) -> float\nReturn the Hyperbolic Arc-External Secant [arcexsech(x) == (1/acosh(x)-1)]")
PyDoc_STRVAR (mathfunc_exsech_docstring,"exsech(radians: float) -> float\nReturn the External Hyperbolic Secant [exsech(x) == (1/cosh(x)-1)]")
PyDoc_STRVAR (mathfunc_exsec_docstring,"exsec(radians: float) -> float\nReturn the External Secant [exsec(x) == (1/cos(x))-1 == sec(x)-1]")
PyDoc_STRVAR (mathfunc_cos_arcsin_docstring,"cos_arcsin(radians: float) -> float\nReturn the Cosine of an Arc-Sine [sqrt(1-(x*x))]")
PyDoc_STRVAR (mathfunc_cos_arctan_docstring,"cos_arctan(radians: float) -> float\nReturn the Cosine of an Arc-Tangent [1 / sqrt(1+(x*x))]")
PyDoc_STRVAR (mathfunc_sin_arcsec_docstring,"sin_arcsec(radians: float) -> float\nReturn the Sine of an Arc-Tangent [sqrt((x*x)-1)/x]")
PyDoc_STRVAR (mathfunc_sin_arctan_docstring,"sin_arctan(radians: float) -> float\nReturn the Sine of an Arc-Tangent [x / sqrt(1+(x*x))]")
PyDoc_STRVAR (mathfunc_issquare_docstring,"issquare(num: int) -> bool\nTest if a number is a perfect square")
PyDoc_STRVAR (mathfunc_isfloatsquare_docstring,"isfloatsquare(num: float) -> bool\nTest if a double is a perfect square")
PyDoc_STRVAR (mathfunc_istriangular_docstring,"istriangular(num: int) -> bool\nTest if the given number is a Triangular Number")
PyDoc_STRVAR (mathfunc_ishexagonal_docstring,"ishexagonal(num: int) -> bool\nTest if the given number is a Hexagonal Number")
PyDoc_STRVAR (mathfunc_isheptagonal_docstring,"isheptagonal(num: int) -> bool\nTest if the given number is a Heptagonal Number")
PyDoc_STRVAR (mathfunc_ispoweroftwo_docstring,"ispoweroftwo(num: int) -> bool\nTest if the given number is a Power-of-Two")
PyDoc_STRVAR (mathfunc_ismersennenumber_docstring,"ismersennenumber(num: int) -> bool\nTest if the given number is a Mersenne Number")
PyDoc_STRVAR (mathfunc_ismersenneprime_docstring,"ismersenneprime(num: int) -> bool\nTest if the given number is a Mersenne Prime")
PyDoc_STRVAR (mathfunc_isprime_docstring,"isprime(num: int) -> bool\nTest if a signed int is prime")
PyDoc_STRVAR (mathfunc_iscomposite_docstring,"iscomposite(num: int) -> bool\nTest if an int is composite")
PyDoc_STRVAR (mathfunc_fma_docstring,"fma(num1: float, num2: float, num3: float) -> float\nFused Multiply-Add (num1*num2+num3)")
PyDoc_STRVAR (mathfunc_fpclassify_docstring,"fpclassify(num: float) -> int\nReturn an integer that indicates the type of float\n-1: Error\n0: NaN\n1: Infinity\n2: Zero\n3: Subnormal\n4: Normal")
PyDoc_STRVAR (mathfunc_float_diff_docstring,"float_diff(num1: float, num2: float) -> float\nReturn the difference between the two floats")
PyDoc_STRVAR (mathfunc_bit_length_docstring,"bit_length(num: int) -> int\nReturn the number of bits used to represent the given number")
PyModule_AddStringConstant (m,"__author__", __author__)
PyModule_AddStringConstant (m,"__version__", __version__)
Variables
m = PyModule_Create(&module)
MODINIT
static struct PyModuleDef module
static char module_docstring [16]
static PyMethodDef module_methods [128]
Detailed Description
Math Functions.
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.20
DESCRIPTION
This is a Python3 module that uses functions from mathfunc.c Numerous mathematical and trigonometric functions. This extends the standard math library by providing by offering faster alternatives. Such functions include squareroot, fractorial, fib, haversin, isprime, ishexagonal, etc.
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file pymathfunc.c.
Macro Definition Documentation
#define MODINIT PyMODINIT_FUNC PyInit_mathfunc(void)
Definition at line 40 of file pymathfunc.c.
#define MODNAME "mathfunc"
Definition at line 39 of file pymathfunc.c.
Function Documentation
MODINIT __attribute__ ((flatten, hot))
if (return m = = (PyObject *)NULL)
Definition at line 533 of file pymathfunc.c.
static PyObject * mathfunc_acot (FUNCARGS) static
Definition at line 745 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_acoth (FUNCARGS) static
Definition at line 759 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_acsc (FUNCARGS) static
Definition at line 787 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_acsch (FUNCARGS) static
Definition at line 801 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arccot (FUNCARGS) static
Definition at line 752 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arccoth (FUNCARGS) static
Definition at line 766 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arccsc (FUNCARGS) static
Definition at line 794 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arccsch (FUNCARGS) static
Definition at line 808 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcexcot (FUNCARGS) static
Definition at line 944 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcexcoth (FUNCARGS) static
Definition at line 951 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcexcsc (FUNCARGS) static
Definition at line 972 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcexcsch (FUNCARGS) static
Definition at line 979 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcexsec (FUNCARGS) static
Definition at line 1000 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcexsech (FUNCARGS) static
Definition at line 1007 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcsec (FUNCARGS) static
Definition at line 836 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcsech (FUNCARGS) static
Definition at line 850 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcvercos (FUNCARGS) static
Definition at line 899 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcvercosh (FUNCARGS) static
Definition at line 906 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcversin (FUNCARGS) static
Definition at line 871 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_arcversinh (FUNCARGS) static
Definition at line 878 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_asec (FUNCARGS) static
Definition at line 829 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_asech (FUNCARGS) static
Definition at line 843 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_bit_length (FUNCARGS) static
Definition at line 1177 of file pymathfunc.c.
References ASSERT_ULONGLONG_ARG, bit_length(), ull2int, and ullint.
static PyObject * mathfunc_cos_arcsin (FUNCARGS) static
Definition at line 1031 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and squareroot().
static PyObject * mathfunc_cos_arctan (FUNCARGS) static
Definition at line 1038 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and squareroot().
static PyObject * mathfunc_cot (FUNCARGS) static
Definition at line 780 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_coth (FUNCARGS) static
Definition at line 773 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_crd (FUNCARGS) static
Definition at line 738 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_csc (FUNCARGS) static
Definition at line 822 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_csch (FUNCARGS) static
Definition at line 815 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_doublefactorial (FUNCARGS) static
Definition at line 606 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, doublefactoriallonglong(), ll2int, and sllint.
static PyObject * mathfunc_excot (FUNCARGS) static
Definition at line 965 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_excoth (FUNCARGS) static
Definition at line 958 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_excsc (FUNCARGS) static
Definition at line 993 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_excsch (FUNCARGS) static
Definition at line 986 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_exsec (FUNCARGS) static
Definition at line 1021 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_exsech (FUNCARGS) static
Definition at line 1014 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_factorial (FUNCARGS) static
Definition at line 599 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, factoriallonglong(), ll2int, and sllint.
static PyObject * mathfunc_fib (FUNCARGS) static
Definition at line 637 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, and sllint.
static PyObject * mathfunc_float_diff (FUNCARGS) static
Definition at line 1170 of file pymathfunc.c.
References ASSERT_2DOUBLE_ARG, and double2float.
static PyObject * mathfunc_fma (FUNCARGS) static
Definition at line 1144 of file pymathfunc.c.
References ASSERT_3DOUBLE_ARG, and double2float.
static PyObject * mathfunc_fpclassify (FUNCARGS) static
Definition at line 1155 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and int2int.
static PyObject * mathfunc_hacoversin (FUNCARGS) static
Definition at line 934 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_haversin (FUNCARGS) static
Definition at line 927 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_heptagonal_num (FUNCARGS) static
Definition at line 700 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, heptagonal_numlonglong(), ll2int, and sllint.
static PyObject * mathfunc_hexagonal_num (FUNCARGS) static
Definition at line 693 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, hexagonal_numlonglong(), ll2int, and sllint.
static PyObject * mathfunc_iscomposite (FUNCARGS) static
Definition at line 1133 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongcomposite(), returnbool, and sllint.
static PyObject * mathfunc_isfloatsquare (FUNCARGS) static
Definition at line 1070 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, isdoublesquare(), and returnbool.
static PyObject * mathfunc_isheptagonal (FUNCARGS) static
Definition at line 1093 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongheptagonal(), returnbool, and sllint.
static PyObject * mathfunc_ishexagonal (FUNCARGS) static
Definition at line 1085 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglonghexagonal(), returnbool, and sllint.
static PyObject * mathfunc_ismersennenumber (FUNCARGS) static
Definition at line 1109 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongmersennenumber(), returnbool, and sllint.
static PyObject * mathfunc_ismersenneprime (FUNCARGS) static
Definition at line 1117 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongmersenneprime(), returnbool, and sllint.
static PyObject * mathfunc_ispoweroftwo (FUNCARGS) static
Definition at line 1101 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongpoweroftwo(), returnbool, and sllint.
static PyObject * mathfunc_isprime (FUNCARGS) static
Definition at line 1125 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongprime(), returnbool, and sllint.
static PyObject * mathfunc_issquare (FUNCARGS) static
Definition at line 1062 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongsquare(), returnbool, and sllint.
static PyObject * mathfunc_istriangular (FUNCARGS) static
Definition at line 1077 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongtriangular(), returnbool, and sllint.
static PyObject * mathfunc_mersenne_num (FUNCARGS) static
Definition at line 721 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, mersenne_numlonglong(), and sllint.
static PyObject * mathfunc_pentatope_num (FUNCARGS) static
Definition at line 714 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, pentatope_numlonglong(), and sllint.
static PyObject* mathfunc_pow2 (FUNCARGS) static
static PyObject * mathfunc_pow_ten (FUNCARGS) static
Definition at line 551 of file pymathfunc.c.
References ASSERT_INT_ARG, double2float, and pow_ten().
static PyObject * mathfunc_pow_ten_int (FUNCARGS) static
Definition at line 558 of file pymathfunc.c.
References ASSERT_UINT_ARG, pow_ten_int(), and ull2int.
static PyObject * mathfunc_pow_ten_int_fast (FUNCARGS) static
Definition at line 565 of file pymathfunc.c.
References ASSERT_UINT_ARG, pow_ten_int_fast(), and ull2int.
static PyObject * mathfunc_pow_ten_neg (FUNCARGS) static
Definition at line 579 of file pymathfunc.c.
References ASSERT_INT_ARG, double2float, and pow_ten_neg().
static PyObject * mathfunc_pow_ten_pos (FUNCARGS) static
Definition at line 572 of file pymathfunc.c.
References ASSERT_UINT_ARG, double2float, and pow_ten_pos().
static PyObject * mathfunc_pronic (FUNCARGS) static
Definition at line 630 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, proniclonglong(), and sllint.
static PyObject * mathfunc_quadfactorial (FUNCARGS) static
Definition at line 613 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, quadfactoriallonglong(), and sllint.
static PyObject * mathfunc_sec (FUNCARGS) static
Definition at line 864 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_sech (FUNCARGS) static
Definition at line 857 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_sin_arcsec (FUNCARGS) static
Definition at line 1045 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and squareroot().
static PyObject * mathfunc_sin_arctan (FUNCARGS) static
Definition at line 1052 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and squareroot().
static PyObject * mathfunc_sinpi (FUNCARGS) static
Definition at line 731 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and sinpi().
static PyObject * mathfunc_squareroot (FUNCARGS) static
Definition at line 589 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and squareroot().
static PyObject * mathfunc_superfactorial (FUNCARGS) static
Definition at line 620 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, sllint, and superfactoriallonglong().
static PyObject * mathfunc_tetrahedral_num (FUNCARGS) static
Definition at line 707 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, sllint, and tetrahedral_numlonglong().
static PyObject * mathfunc_triangular_num (FUNCARGS) static
Definition at line 686 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, sllint, and triangular_numlonglong().
static PyObject * mathfunc_vercos (FUNCARGS) static
Definition at line 920 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_vercosh (FUNCARGS) static
Definition at line 913 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_versin (FUNCARGS) static
Definition at line 892 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject * mathfunc_versinh (FUNCARGS) static
Definition at line 885 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
PyDoc_STRVAR (mathfunc_pow2_docstring , "pow2(num: int) -> int\nReturn the power of 2^ num, where\"num\" is a positive integer")
PyDoc_STRVAR (mathfunc_pow_ten_docstring , "pow_ten(num: int) -> float\nReturn the power of 10^num")
PyDoc_STRVAR (mathfunc_pow_ten_int_docstring , "pow_ten_int(num: int) -> int\nReturn the power of 10^ num, where 'num'is a positive integer")
PyDoc_STRVAR (mathfunc_pow_ten_int_fast_docstring , "pow_ten_int_fast(num: int) -> int\nReturn the power of 10^num ('num' is a positive integer less than 18)")
PyDoc_STRVAR (mathfunc_pow_ten_pos_docstring , "pow_ten_pos(num: int) -> float\nReturn the power of 10^num for positive exponents")
PyDoc_STRVAR (mathfunc_pow_ten_neg_docstring , "pow_ten_neg(num: int) -> float\nReturn the power of 10^num for negative exponents")
PyDoc_STRVAR (mathfunc_squareroot_docstring , "squareroot(num: float) -> float\nReturn the Square-Root of a positive number")
PyDoc_STRVAR (mathfunc_factorial_docstring , "factorial(num: int) -> float\nFactorial (n!)")
PyDoc_STRVAR (mathfunc_doublefactorial_docstring , "doublefactorial(num: int) -> float\nDouble Factorial (n!!)")
PyDoc_STRVAR (mathfunc_quadfactorial_docstring , "quadfactorial(num: int) -> float\nQuadruple Factorial - (2n)!/n!")
PyDoc_STRVAR (mathfunc_superfactorial_docstring , "superfactorial(num: int) -> float\nSuper-Factorial")
PyDoc_STRVAR (mathfunc_pronic_docstring , "pronic(num: int) -> int\nReturn the Nth Pronic number")
PyDoc_STRVAR (mathfunc_fib_docstring , "fib(num: int) -> int\nFibonacci Number Generator\nReturn the specified Fibonacci Number")
PyDoc_STRVAR (mathfunc_triangular_num_docstring , "triangular_num(num: int) -> int\nReturn the Nth Triangular Number")
PyDoc_STRVAR (mathfunc_hexagonal_num_docstring , "hexagonal_num(num: int) -> int\nReturn the Nth Hexagonal Number")
PyDoc_STRVAR (mathfunc_heptagonal_num_docstring , "heptagonal_num(num: int) -> int\nReturn the Nth Heptagonal Number")
PyDoc_STRVAR (mathfunc_tetrahedral_num_docstring , "tetrahedral_num(num: int) -> int\nReturn the Nth Tetrahedral Number")
PyDoc_STRVAR (mathfunc_pentatope_num_docstring , "pentatope_num(num: int) -> int\nReturn the Nth Pentatope Number")
PyDoc_STRVAR (mathfunc_mersenne_num_docstring , "mersenne_num(num: int) -> int\nReturn the Nth Mersenne Number")
PyDoc_STRVAR (mathfunc_sinpi_docstring , "sinpi(num: float) -> float\nReturn the Pi Sine of the given number; return 0.0 on error")
PyDoc_STRVAR (mathfunc_crd_docstring , "crd(radians: float) -> float\nReturn the Chord")
PyDoc_STRVAR (mathfunc_acot_docstring , "acot(radians: float) -> float\nReturn the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))")
PyDoc_STRVAR (mathfunc_arccot_docstring , "arccot(radians: float) -> float\nReturn the Arc-Cotangent (acot(x)||arccot(x) == atan(1/x))")
PyDoc_STRVAR (mathfunc_acoth_docstring , "acoth(radians: float) -> float\nReturn the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))")
PyDoc_STRVAR (mathfunc_arccoth_docstring , "arccoth(radians: float) -> float\nReturn the Hyperbolic Arc-Cotangent (acoth(x)||arccoth(x) == atanh(1/x))")
PyDoc_STRVAR (mathfunc_coth_docstring , "coth(radians: float) -> float\nReturn the Hyperbolic Cotangent (coth(x) == 1/tanh(x))")
PyDoc_STRVAR (mathfunc_cot_docstring , "cot(radians: float) -> float\nReturn the Cotangent (cot(x) == 1/tan(x))")
PyDoc_STRVAR (mathfunc_acsc_docstring , "acsc(radians: float) -> float\nReturn the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))")
PyDoc_STRVAR (mathfunc_arccsc_docstring , "arccsc(radians: float) -> float\nReturn the Arc-Cosecant (acsc(x)||arccsc(x) == asin(1/x))")
PyDoc_STRVAR (mathfunc_acsch_docstring , "acsch(radians: float) -> float\nReturn the Hyperbolic Arc-Cosecant (acsch(x)||arccsch(x) == asinh(1/x))")
PyDoc_STRVAR (mathfunc_arccsch_docstring , "arccsch(radians: float) -> float\nReturn the Hyperbolic Arc-Cosecant (acsc(x)||arccsch(x) == asinh(1/x))")
PyDoc_STRVAR (mathfunc_csch_docstring , "csch(radians: float) -> float\nReturn the Hyperbolic Cosecant (csch(x) == 1/sinh(x))")
PyDoc_STRVAR (mathfunc_csc_docstring , "csc(radians: float) -> float\nReturn the Cosecant (csc(x) == 1/sin(x))")
PyDoc_STRVAR (mathfunc_asec_docstring , "asec(radians: float) -> float\nReturn the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))")
PyDoc_STRVAR (mathfunc_arcsec_docstring , "arcsec(radians: float) -> float\nReturn the Arc-Secant (asec(x)||arcsec(x) == acos(1/x))")
PyDoc_STRVAR (mathfunc_asech_docstring , "asech(radians: float) -> float\nReturn the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))")
PyDoc_STRVAR (mathfunc_arcsech_docstring , "arcsech(radians: float) -> float\nReturn the Hyperbolic Arc-Secant (asech(x)||arcsech(x) == acosh(1/x))")
PyDoc_STRVAR (mathfunc_sech_docstring , "sech(radians: float) -> float\nReturn the Hyperbolic Secant (sech(x) == 1/cosh(x))")
PyDoc_STRVAR (mathfunc_sec_docstring , "sec(radians: float) -> float\nReturn the Secant (sec(x) == 1/cos(x))")
PyDoc_STRVAR (mathfunc_arcversin_docstring , "arcversin(radians: float) -> float\nReturn the Arc-Versed Sine (arcversin(x) == 1 - acos(x))")
PyDoc_STRVAR (mathfunc_arcversinh_docstring , "arcversinh(radians: float) -> float\nReturn the Hyperbolic Arc-Versed Sine (arcversinh(x) == 1 - acosh(x))")
PyDoc_STRVAR (mathfunc_versinh_docstring , "versinh(radians: float) -> float\nReturn the Hyperbolic Versed Sine (versinh(x) == 1 - cosh(x))")
PyDoc_STRVAR (mathfunc_versin_docstring , "versin(radians: float) -> float\nReturn the Versed Sine (versin(x) == 1 - cos(x))")
PyDoc_STRVAR (mathfunc_arcvercos_docstring , "arcvercos(radians: float) -> float\nReturn the Arc-Versed Cosine (arcvercos(x) == 1 - asin(x))")
PyDoc_STRVAR (mathfunc_arcvercosh_docstring , "arcvercosh(radians: float) -> float\nReturn the Hyperbolic Arc-Versed Cosine (arcvercosh(x) == 1 - asinh(x))")
PyDoc_STRVAR (mathfunc_vercosh_docstring , "vercosh(radians: float) -> float\nReturn the Hyperbolic Versed Cosine (vercosh(x) == 1 - sinh(x))")
PyDoc_STRVAR (mathfunc_vercos_docstring , "vercos(radians: float) -> float\nReturn the Versed Cosine (vercos(x) == 1 - sin(x))")
PyDoc_STRVAR (mathfunc_haversin_docstring , "haversin(radians: float) -> float\nReturn the Haversine (haversin(x) == 0.5*(1 - cos(x)))")
PyDoc_STRVAR (mathfunc_hacoversin_docstring , "hacoversin(radians: float) -> float\nReturn the Hacoversine (hacoversin(x) == 0.5*(1 - sin(x)))")
PyDoc_STRVAR (mathfunc_arcexcot_docstring , "arcexcot(radians: float) -> float\nReturn the Arc-External Cotangent (arcexcot(x) == atan(1/(x+1)))")
PyDoc_STRVAR (mathfunc_arcexcoth_docstring , "arcexcoth(radians: float) -> float\nReturn the Hyperbolic Arc-External Cotangent " [arcexcoth(x)==(1/atanh(x)-1)])
PyDoc_STRVAR (mathfunc_excoth_docstring , "excoth(radians: float) -> float\nReturn the External Hyperbolic Cotangent " [excoth(x)==(1/tanh(x)-1)])
PyDoc_STRVAR (mathfunc_excot_docstring , "excot(radians: float) -> float\nReturn the External Cotangent " [excot(x)==(1/tan(x))-1==cot(x)-1])
PyDoc_STRVAR (mathfunc_arcexcsc_docstring , "arcexcsc(radians: float) -> float\nReturn the Arc-External Cosecant (arcexcsc(x) == asin(1/(x+1)))")
PyDoc_STRVAR (mathfunc_arcexcsch_docstring , "arcexcsch(radians: float) -> float\nReturn the Hyperbolic Arc-External Cosecant " [arcexcsch(x)==(1/asinh(x)-1)])
PyDoc_STRVAR (mathfunc_excsch_docstring , "excsch(radians: float) -> float\nReturn the External Hyperbolic Cosecant " [excsch(x)==(1/sinh(x)-1)])
PyDoc_STRVAR (mathfunc_excsc_docstring , "excsc(radians: float) -> float\nReturn the External Cosecant " [excsc(x)==(1/sin(x))-1==csc(x)-1])
PyDoc_STRVAR (mathfunc_arcexsec_docstring , "arcexsec(radians: float) -> float\nReturn the Arc-External Secant (arcexsec(x) == acos(1/(x+1)))")
PyDoc_STRVAR (mathfunc_arcexsech_docstring , "arcexsech(radians: float) -> float\nReturn the Hyperbolic Arc-External Secant " [arcexsech(x)==(1/acosh(x)-1)])
PyDoc_STRVAR (mathfunc_exsech_docstring , "exsech(radians: float) -> float\nReturn the External Hyperbolic Secant " [exsech(x)==(1/cosh(x)-1)])
PyDoc_STRVAR (mathfunc_exsec_docstring , "exsec(radians: float) -> float\nReturn the External Secant " [exsec(x)==(1/cos(x))-1==sec(x)-1])
PyDoc_STRVAR (mathfunc_cos_arcsin_docstring , "cos_arcsin(radians: float) -> float\nReturn the Cosine of an Arc-Sine " [sqrt(1-(x *x))])
PyDoc_STRVAR (mathfunc_cos_arctan_docstring , "cos_arctan(radians: float) -> float\nReturn the Cosine of an Arc-Tangent " [1/sqrt(1+(x *x))])
PyDoc_STRVAR (mathfunc_sin_arcsec_docstring , "sin_arcsec(radians: float) -> float\nReturn the Sine of an Arc-Tangent " [sqrt((x *x)-1)/x])
PyDoc_STRVAR (mathfunc_sin_arctan_docstring , "sin_arctan(radians: float) -> float\nReturn the Sine of an Arc-Tangent " [x/sqrt(1+(x *x))])
PyDoc_STRVAR (mathfunc_issquare_docstring , "issquare(num: int) -> bool\nTest if a number is a perfect square")
PyDoc_STRVAR (mathfunc_isfloatsquare_docstring , "isfloatsquare(num: float) -> bool\nTest if a double is a perfect square")
PyDoc_STRVAR (mathfunc_istriangular_docstring , "istriangular(num: int) -> bool\nTest if the given number is a Triangular Number")
PyDoc_STRVAR (mathfunc_ishexagonal_docstring , "ishexagonal(num: int) -> bool\nTest if the given number is a Hexagonal Number")
PyDoc_STRVAR (mathfunc_isheptagonal_docstring , "isheptagonal(num: int) -> bool\nTest if the given number is a Heptagonal Number")
PyDoc_STRVAR (mathfunc_ispoweroftwo_docstring , "ispoweroftwo(num: int) -> bool\nTest if the given number is a Power-of-Two")
PyDoc_STRVAR (mathfunc_ismersennenumber_docstring , "ismersennenumber(num: int) -> bool\nTest if the given number is a Mersenne Number")
PyDoc_STRVAR (mathfunc_ismersenneprime_docstring , "ismersenneprime(num: int) -> bool\nTest if the given number is a Mersenne Prime")
PyDoc_STRVAR (mathfunc_isprime_docstring , "isprime(num: int) -> bool\nTest if a signed int is prime")
PyDoc_STRVAR (mathfunc_iscomposite_docstring , "iscomposite(num: int) -> bool\nTest if an int is composite")
PyDoc_STRVAR (mathfunc_fma_docstring , "fma(num1: float, num2: float, num3: float) -> float\nFused Multiply-Add (num1*num2+num3)")
PyDoc_STRVAR (mathfunc_fpclassify_docstring , "fpclassify(num: float) -> int\nReturn an integer that indicates the type of float\n-1: Error\n0: NaN\n1: Infinity\n2: Zero\n3: Subnormal\n4: Normal")
PyDoc_STRVAR (mathfunc_float_diff_docstring , "float_diff(num1: float, num2: float) -> float\nReturn the difference between the two floats")
PyDoc_STRVAR (mathfunc_bit_length_docstring , "bit_length(num: int) -> int\nReturn the number of bits used to represent the given number")
PyModule_AddStringConstant (m , "__author__" , __author__)
PyModule_AddStringConstant (m , "__version__" , __version__)
Variable Documentation
m = PyModule_Create(&module)
Definition at line 526 of file pymathfunc.c.
MODINIT
Initial value:
{
    PyObject *m
Definition at line 524 of file pymathfunc.c.
struct PyModuleDef module static
Initial value:
= {
    PyModuleDef_HEAD_INIT,
    MODNAME,
    module_docstring,
    -1,
    module_methods,
    NULL,
    NULL,
    NULL,
    NULL
}
Definition at line 511 of file pymathfunc.c.
char module_docstring[16] static
Initial value:
=
    "Math Functions"
Definition at line 244 of file pymathfunc.c.
PyMethodDef module_methods[128] static
Initial value:
= {
    {"pow2", (PyCFunction)mathfunc_pow2, METH_VARARGS, mathfunc_pow2_docstring},
    {"pow_ten", (PyCFunction)mathfunc_pow_ten, METH_VARARGS, mathfunc_pow_ten_docstring},
    {"pow_ten_int", (PyCFunction)mathfunc_pow_ten_int, METH_VARARGS, mathfunc_pow_ten_int_docstring},
    {"pow_ten_int_fast", (PyCFunction)mathfunc_pow_ten_int_fast, METH_VARARGS, mathfunc_pow_ten_int_fast_docstring},
    {"pow_ten_pos", (PyCFunction)mathfunc_pow_ten_pos, METH_VARARGS, mathfunc_pow_ten_pos_docstring},
    {"pow_ten_neg", (PyCFunction)mathfunc_pow_ten_neg, METH_VARARGS, mathfunc_pow_ten_neg_docstring},
    {"squareroot", (PyCFunction)mathfunc_squareroot, METH_VARARGS, mathfunc_squareroot_docstring},
    {"factorial", (PyCFunction)mathfunc_factorial, METH_VARARGS, mathfunc_factorial_docstring},
    {"doublefactorial", (PyCFunction)mathfunc_doublefactorial, METH_VARARGS, mathfunc_doublefactorial_docstring},
    {"quadfactorial", (PyCFunction)mathfunc_quadfactorial, METH_VARARGS, mathfunc_quadfactorial_docstring},
    {"superfactorial", (PyCFunction)mathfunc_superfactorial, METH_VARARGS, mathfunc_superfactorial_docstring},
    {"fib", (PyCFunction)mathfunc_fib, METH_VARARGS, mathfunc_fib_docstring},
    {"pronic", (PyCFunction)mathfunc_pronic, METH_VARARGS, mathfunc_pronic_docstring},
    {"triangular_num", (PyCFunction)mathfunc_triangular_num, METH_VARARGS, mathfunc_triangular_num_docstring},
    {"hexagonal_num", (PyCFunction)mathfunc_hexagonal_num, METH_VARARGS, mathfunc_hexagonal_num_docstring},
    {"heptagonal_num", (PyCFunction)mathfunc_heptagonal_num, METH_VARARGS, mathfunc_heptagonal_num_docstring},
    {"tetrahedral_num", (PyCFunction)mathfunc_tetrahedral_num, METH_VARARGS, mathfunc_tetrahedral_num_docstring},
    {"pentatope_num", (PyCFunction)mathfunc_pentatope_num, METH_VARARGS, mathfunc_pentatope_num_docstring},
    {"mersenne_num", (PyCFunction)mathfunc_mersenne_num, METH_VARARGS, mathfunc_mersenne_num_docstring},
    {"sinpi", (PyCFunction)mathfunc_sinpi, METH_VARARGS, mathfunc_sinpi_docstring},
    {"crd", (PyCFunction)mathfunc_crd, METH_VARARGS, mathfunc_crd_docstring},
    {"acot", (PyCFunction)mathfunc_acot, METH_VARARGS, mathfunc_acot_docstring},
    {"arccot", (PyCFunction)mathfunc_arccot, METH_VARARGS, mathfunc_arccot_docstring},
    {"acoth", (PyCFunction)mathfunc_acoth, METH_VARARGS, mathfunc_acoth_docstring},
    {"arccoth", (PyCFunction)mathfunc_arccoth, METH_VARARGS, mathfunc_arccoth_docstring},
    {"coth", (PyCFunction)mathfunc_coth, METH_VARARGS, mathfunc_coth_docstring},
    {"cot", (PyCFunction)mathfunc_cot, METH_VARARGS, mathfunc_cot_docstring},
    {"acsc", (PyCFunction)mathfunc_acsc, METH_VARARGS, mathfunc_acsc_docstring},
    {"arccsc", (PyCFunction)mathfunc_arccsc, METH_VARARGS, mathfunc_arccsc_docstring},
    {"acsch", (PyCFunction)mathfunc_acsch, METH_VARARGS, mathfunc_acsch_docstring},
    {"arccsch", (PyCFunction)mathfunc_arccsch, METH_VARARGS, mathfunc_arccsch_docstring},
    {"csch", (PyCFunction)mathfunc_csch, METH_VARARGS, mathfunc_csch_docstring},
    {"csc", (PyCFunction)mathfunc_csc, METH_VARARGS, mathfunc_csc_docstring},
    {"asec", (PyCFunction)mathfunc_asec, METH_VARARGS, mathfunc_asec_docstring},
    {"arcsec", (PyCFunction)mathfunc_arcsec, METH_VARARGS, mathfunc_arcsec_docstring},
    {"asech", (PyCFunction)mathfunc_asech, METH_VARARGS, mathfunc_asech_docstring},
    {"arcsech", (PyCFunction)mathfunc_arcsech, METH_VARARGS, mathfunc_arcsech_docstring},
    {"sech", (PyCFunction)mathfunc_sech, METH_VARARGS, mathfunc_sech_docstring},
    {"sec", (PyCFunction)mathfunc_sec, METH_VARARGS, mathfunc_sec_docstring},
    {"arcversin", (PyCFunction)mathfunc_arcversin, METH_VARARGS, mathfunc_arcversin_docstring},
    {"arcversinh", (PyCFunction)mathfunc_arcversinh, METH_VARARGS, mathfunc_arcversinh_docstring},
    {"versinh", (PyCFunction)mathfunc_versinh, METH_VARARGS, mathfunc_versinh_docstring},
    {"versin", (PyCFunction)mathfunc_versin, METH_VARARGS, mathfunc_versin_docstring},
    {"arcvercos", (PyCFunction)mathfunc_arcvercos, METH_VARARGS, mathfunc_arcvercos_docstring},
    {"arcvercosh", (PyCFunction)mathfunc_arcvercosh, METH_VARARGS, mathfunc_arcvercosh_docstring},
    {"vercosh", (PyCFunction)mathfunc_vercosh, METH_VARARGS, mathfunc_vercosh_docstring},
    {"vercos", (PyCFunction)mathfunc_vercos, METH_VARARGS, mathfunc_vercos_docstring},
    {"haversin", (PyCFunction)mathfunc_haversin, METH_VARARGS, mathfunc_haversin_docstring},
    {"hacoversin", (PyCFunction)mathfunc_hacoversin, METH_VARARGS, mathfunc_hacoversin_docstring},
    {"arcexcot", (PyCFunction)mathfunc_arcexcot, METH_VARARGS, mathfunc_arcexcot_docstring},
    {"arcexcoth", (PyCFunction)mathfunc_arcexcoth, METH_VARARGS, mathfunc_arcexcoth_docstring},
    {"excoth", (PyCFunction)mathfunc_excoth, METH_VARARGS, mathfunc_excoth_docstring},
    {"excot", (PyCFunction)mathfunc_excot, METH_VARARGS, mathfunc_excot_docstring},
    {"arcexcsc", (PyCFunction)mathfunc_arcexcsc, METH_VARARGS, mathfunc_arcexcsc_docstring},
    {"arcexcsch", (PyCFunction)mathfunc_arcexcsch, METH_VARARGS, mathfunc_arcexcsch_docstring},
    {"excsch", (PyCFunction)mathfunc_excsch, METH_VARARGS, mathfunc_excsch_docstring},
    {"excsc", (PyCFunction)mathfunc_excsc, METH_VARARGS, mathfunc_excsc_docstring},
    {"arcexsec", (PyCFunction)mathfunc_arcexsec, METH_VARARGS, mathfunc_arcexsec_docstring},
    {"arcexsech", (PyCFunction)mathfunc_arcexsech, METH_VARARGS, mathfunc_arcexsech_docstring},
    {"exsech", (PyCFunction)mathfunc_exsech, METH_VARARGS, mathfunc_exsech_docstring},
    {"exsec", (PyCFunction)mathfunc_exsec, METH_VARARGS, mathfunc_exsec_docstring},
    {"cos_arcsin", (PyCFunction)mathfunc_cos_arcsin, METH_VARARGS, mathfunc_cos_arcsin_docstring},
    {"cos_arctan", (PyCFunction)mathfunc_cos_arctan, METH_VARARGS, mathfunc_cos_arctan_docstring},
    {"sin_arcsec", (PyCFunction)mathfunc_sin_arcsec, METH_VARARGS, mathfunc_sin_arcsec_docstring},
    {"sin_arctan", (PyCFunction)mathfunc_sin_arctan, METH_VARARGS, mathfunc_sin_arctan_docstring},
    {"issquare", (PyCFunction)mathfunc_issquare, METH_VARARGS, mathfunc_issquare_docstring},
    {"isfloatsquare", (PyCFunction)mathfunc_isfloatsquare, METH_VARARGS, mathfunc_isfloatsquare_docstring},
    {"istriangular", (PyCFunction)mathfunc_istriangular, METH_VARARGS, mathfunc_istriangular_docstring},
    {"ishexagonal", (PyCFunction)mathfunc_ishexagonal, METH_VARARGS, mathfunc_ishexagonal_docstring},
    {"isheptagonal", (PyCFunction)mathfunc_isheptagonal, METH_VARARGS, mathfunc_isheptagonal_docstring},
    {"ispoweroftwo", (PyCFunction)mathfunc_ispoweroftwo, METH_VARARGS, mathfunc_ispoweroftwo_docstring},
    {"ismersennenumber", (PyCFunction)mathfunc_ismersennenumber, METH_VARARGS, mathfunc_ismersennenumber_docstring},
    {"ismersenneprime", (PyCFunction)mathfunc_ismersenneprime, METH_VARARGS, mathfunc_ismersenneprime_docstring},
    {"isprime", (PyCFunction)mathfunc_isprime, METH_VARARGS, mathfunc_isprime_docstring},
    {"iscomposite", (PyCFunction)mathfunc_iscomposite, METH_VARARGS, mathfunc_iscomposite_docstring},
    {"fma", (PyCFunction)mathfunc_fma, METH_VARARGS, mathfunc_fma_docstring},
    {"fpclassify", (PyCFunction)mathfunc_fpclassify, METH_VARARGS, mathfunc_fpclassify_docstring},
    {"float_diff", (PyCFunction)mathfunc_float_diff, METH_VARARGS, mathfunc_float_diff_docstring},
    {"bit_length", (PyCFunction)mathfunc_bit_length, METH_VARARGS, mathfunc_bit_length_docstring},
    {NULL, NULL, 0, NULL}
}
Definition at line 418 of file pymathfunc.c.