PyBooster: pytools.c File Reference
pytools.c File Reference
Miscellaneous Functions (from tools.c and x86_64_asm_func.c)
#include "PY_MACROS.h"
#include "tools.h"
#include "x86_64_asm_func.h"
Macros
#define MODINIT PyMODINIT_FUNC PyInit_tools(void)
#define MODNAME "tools"
Functions
MODINIT __attribute__ ((flatten, hot))
if (return m==(PyObject *) NULL)
PyDoc_STRVAR (tools_lowercasestr_docstring,"lowercasestr(STR: str) -> str\nConvert a string to all lowercase letters")
PyDoc_STRVAR (tools_lowercasestr15_docstring,"lowercasestr15(STR: str) -> str\nConvert a string 15-character string to all lowercase letters")
PyDoc_STRVAR (tools_uppercasestr_docstring,"uppercasestr(STR: str) -> str\nConvert a string to all uppercase letters")
PyDoc_STRVAR (tools_isstrlowercase_docstring,"isstrlowercase(STR: str) -> bool\nCheck if the string only contains lowercase letters")
PyDoc_STRVAR (tools_isstruppercase_docstring,"isstruppercase(STR: str) -> bool\nCheck if the string only contains uppercase letters")
PyDoc_STRVAR (tools_isstralnum_docstring,"isstralnum(STR: str) -> bool\nCheck if the string only contains alphanumeric characters")
PyDoc_STRVAR (tools_isstralpha_docstring,"isstralpha(STR: str) -> bool\nCheck if the string only contains alphabetic characters")
PyDoc_STRVAR (tools_isstrnum_docstring,"isstrnum(STR: str) -> bool\nCheck if the string only contains numbers")
PyDoc_STRVAR (tools_isstrgraphical_docstring,"isstrgraphical(STR: str) -> bool\nCheck if the string only contains printable characters and not whitespace")
PyDoc_STRVAR (tools_isstrprintable_docstring,"isstrprintable(STR: str) -> bool\nCheck if the string only contains printable characters")
PyDoc_STRVAR (tools_isstrpunctuation_docstring,"isstrpunctuation(STR: str) -> bool\nCheck if the string only contains punctuation characters")
PyDoc_STRVAR (tools_isstrwhitespace_docstring,"isstrwhitespace(STR: str) -> bool\nCheck if the string only contains whitespace characters")
PyDoc_STRVAR (tools_isstrhex_docstring,"isstrhex(STR: str) -> bool\nCheck if the string only contains hexadecimal characters")
PyDoc_STRVAR (tools_strreplace_docstring,"strreplace(orig_string: str, find: str, replace_with: str) -> str\nFind and replace all occurrences of \"find\" with \"replace_with\"")
PyDoc_STRVAR (tools_strreplace_once_docstring,"strreplace_once(orig_string: str, find: str, replace_with: str) -> str\nReplace first occurrence of \"find\" with \"replace_with\"")
PyDoc_STRVAR (tools_rmgravequote_docstring,"rmgravequote(string: str) -> str\nFind and remove grave-quotes (`)")
PyDoc_STRVAR (tools_nop_docstring,"nop() -> None\nDo nothing (faster than Python's `pass` command)")
PyDoc_STRVAR (tools_endianness_docstring,"endianness() -> str\nReturn the system's endianness")
PyDoc_STRVAR (tools_isandroid_docstring,"isandroid() -> bool\nTest if this system is Android")
PyDoc_STRVAR (tools_CSTD_docstring,"CSTD() -> int\nReturn the value of the current C Standard")
PyDoc_STRVAR (tools_printline_docstring,"printline() -> None\nPrint a newline character")
PyModule_AddStringConstant (m,"__author__", __author__)
PyModule_AddStringConstant (m,"__version__", __version__)
static PyObject * tools_CSTD (void)
static PyObject * tools_endianness (void)
static PyObject * tools_isandroid (void)
static PyObject * tools_isstralnum (FUNCARGS)
static PyObject * tools_isstralpha (FUNCARGS)
static PyObject * tools_isstrgraphical (FUNCARGS)
static PyObject * tools_isstrhex (FUNCARGS)
static PyObject * tools_isstrlowercase (FUNCARGS)
static PyObject * tools_isstrnum (FUNCARGS)
static PyObject * tools_isstrprintable (FUNCARGS)
static PyObject * tools_isstrpunctuation (FUNCARGS)
static PyObject * tools_isstruppercase (FUNCARGS)
static PyObject * tools_isstrwhitespace (FUNCARGS)
static PyObject * tools_lowercasestr (FUNCARGS)
static PyObject * tools_lowercasestr15 (FUNCARGS)
static PyObject * tools_nop (void)
static PyObject * tools_printline (void)
static PyObject * tools_rmgravequote (FUNCARGS)
static PyObject * tools_strreplace (FUNCARGS)
static PyObject * tools_strreplace_once (FUNCARGS)
static PyObject * tools_uppercasestr (FUNCARGS)
Variables
m = PyModule_Create(&module)
MODINIT
static struct PyModuleDef module
static char module_docstring [32] = "Miscellaneous Functions"
static PyMethodDef module_methods [128]
Detailed Description
Miscellaneous Functions (from tools.c and x86_64_asm_func.c)
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.20
DESCRIPTION
This is a Python3 module that uses functions from tools.c Various functions that do not fit in other categories. Such functions include string manipulations, file I/O, boolean tests, etc.
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file pytools.c.
Macro Definition Documentation
#define MODINIT PyMODINIT_FUNC PyInit_tools(void)
Definition at line 40 of file pytools.c.
#define MODNAME "tools"
Definition at line 39 of file pytools.c.
Function Documentation
MODINIT __attribute__ ((flatten, hot))
if (return m = = (PyObject *)NULL)
Definition at line 618 of file pytools.c.
PyDoc_STRVAR (tools_lowercasestr_docstring , "lowercasestr(STR: str) -> str\nConvert a string to all lowercase letters")
PyDoc_STRVAR (tools_lowercasestr15_docstring , "lowercasestr15(STR: str) -> str\nConvert a string 15-character string to all lowercase letters")
PyDoc_STRVAR (tools_uppercasestr_docstring , "uppercasestr(STR: str) -> str\nConvert a string to all uppercase letters")
PyDoc_STRVAR (tools_isstrlowercase_docstring , "isstrlowercase(STR: str) -> bool\nCheck if the string only contains lowercase letters")
PyDoc_STRVAR (tools_isstruppercase_docstring , "isstruppercase(STR: str) -> bool\nCheck if the string only contains uppercase letters")
PyDoc_STRVAR (tools_isstralnum_docstring , "isstralnum(STR: str) -> bool\nCheck if the string only contains alphanumeric characters")
PyDoc_STRVAR (tools_isstralpha_docstring , "isstralpha(STR: str) -> bool\nCheck if the string only contains alphabetic characters")
PyDoc_STRVAR (tools_isstrnum_docstring , "isstrnum(STR: str) -> bool\nCheck if the string only contains numbers")
PyDoc_STRVAR (tools_isstrgraphical_docstring , "isstrgraphical(STR: str) -> bool\nCheck if the string only contains printable characters and not whitespace")
PyDoc_STRVAR (tools_isstrprintable_docstring , "isstrprintable(STR: str) -> bool\nCheck if the string only contains printable characters")
PyDoc_STRVAR (tools_isstrpunctuation_docstring , "isstrpunctuation(STR: str) -> bool\nCheck if the string only contains punctuation characters")
PyDoc_STRVAR (tools_isstrwhitespace_docstring , "isstrwhitespace(STR: str) -> bool\nCheck if the string only contains whitespace characters")
PyDoc_STRVAR (tools_isstrhex_docstring , "isstrhex(STR: str) -> bool\nCheck if the string only contains hexadecimal characters")
PyDoc_STRVAR (tools_strreplace_docstring , "strreplace(orig_string: str, find: str, replace_with: str) -> str\nFind and replace all occurrences of \"find\" with \"replace_with\"")
PyDoc_STRVAR (tools_strreplace_once_docstring , "strreplace_once(orig_string: str, find: str, replace_with: str) -> str\nReplace first occurrence of \"find\" with \"replace_with\"")
PyDoc_STRVAR (tools_rmgravequote_docstring , "rmgravequote(string: str) -> str\nFind and remove grave-quotes (`)")
PyDoc_STRVAR (tools_nop_docstring , "nop() -> None\nDo nothing (faster than Python's `pass` command)")
PyDoc_STRVAR (tools_endianness_docstring , "endianness() -> str\nReturn the system's endianness")
PyDoc_STRVAR (tools_isandroid_docstring , "isandroid() -> bool\nTest if this system is Android")
PyDoc_STRVAR (tools_CSTD_docstring , "CSTD() -> int\nReturn the value of the current C Standard")
PyDoc_STRVAR (tools_printline_docstring , "printline() -> None\nPrint a newline character")
PyModule_AddStringConstant (m , "__author__" , __author__)
PyModule_AddStringConstant (m , "__version__" , __version__)
static PyObject * tools_CSTD (void) static
Definition at line 1690 of file pytools.c.
References __STDC_VERSION__, and long2int.
static PyObject * tools_endianness (void) static
Definition at line 1556 of file pytools.c.
References endianness(), and STR.
static PyObject * tools_isandroid (void) static
Definition at line 1681 of file pytools.c.
static PyObject * tools_isstralnum (FUNCARGS) static
Definition at line 837 of file pytools.c.
References ASSERT_STRING_ARG, ISALNUM, and strlenx().
static PyObject * tools_isstralpha (FUNCARGS) static
Definition at line 846 of file pytools.c.
References ASSERT_STRING_ARG, ISALPHA, and strlenx().
static PyObject * tools_isstrgraphical (FUNCARGS) static
Definition at line 864 of file pytools.c.
References ASSERT_STRING_ARG, ISGRAPH, and strlenx().
static PyObject * tools_isstrhex (FUNCARGS) static
Definition at line 900 of file pytools.c.
References ASSERT_STRING_ARG, ISXDIGIT, and strlenx().
static PyObject * tools_isstrlowercase (FUNCARGS) static
Definition at line 819 of file pytools.c.
References ASSERT_STRING_ARG, ISLOWERASCII, and strlenx().
static PyObject * tools_isstrnum (FUNCARGS) static
Definition at line 855 of file pytools.c.
References ASSERT_STRING_ARG, ISDIGIT, and strlenx().
static PyObject * tools_isstrprintable (FUNCARGS) static
Definition at line 873 of file pytools.c.
References ASSERT_STRING_ARG, ISPRINT, and strlenx().
static PyObject * tools_isstrpunctuation (FUNCARGS) static
Definition at line 882 of file pytools.c.
References ASSERT_STRING_ARG, ISPUNCT, and strlenx().
static PyObject * tools_isstruppercase (FUNCARGS) static
Definition at line 828 of file pytools.c.
References ASSERT_STRING_ARG, ISUPPERASCII, and strlenx().
static PyObject * tools_isstrwhitespace (FUNCARGS) static
Definition at line 891 of file pytools.c.
References ASSERT_STRING_ARG, ISSPACE, and strlenx().
static PyObject* tools_lowercasestr (FUNCARGS) static
static PyObject * tools_lowercasestr15 (FUNCARGS) static
Definition at line 710 of file pytools.c.
References ASSERT_STRING_ARG, and STR.
static PyObject * tools_nop (void) static
Definition at line 1547 of file pytools.c.
References __asm__.
static PyObject * tools_printline (void) static
Definition at line 1717 of file pytools.c.
static PyObject * tools_rmgravequote (FUNCARGS) static
Definition at line 945 of file pytools.c.
References ASSERT_STRING_ARG, rmgravequote(), and STR.
static PyObject * tools_strreplace (FUNCARGS) static
Definition at line 912 of file pytools.c.
References ASSERT_3STRING_ARG, STR, strlenx(), and ulint.
static PyObject * tools_strreplace_once (FUNCARGS) static
Definition at line 938 of file pytools.c.
References ASSERT_3STRING_ARG, STR, and strreplace_once().
static PyObject * tools_uppercasestr (FUNCARGS) static
Definition at line 735 of file pytools.c.
References ASSERT_STRING_ARG, STR, and strlenx().
Variable Documentation
m = PyModule_Create(&module)
Definition at line 611 of file pytools.c.
MODINIT
Initial value:
{
    PyObject *m
Definition at line 609 of file pytools.c.
struct PyModuleDef module static
Initial value:
= {
    PyModuleDef_HEAD_INIT,
    MODNAME,
    module_docstring,
    -1,
    module_methods,
    NULL,
    NULL,
    NULL,
    NULL
}
Definition at line 596 of file pytools.c.
char module_docstring[32] = "Miscellaneous Functions" static
Definition at line 202 of file pytools.c.
PyMethodDef module_methods[128] static
Initial value:
= {
    {"lowercasestr", (PyCFunction)tools_lowercasestr, METH_VARARGS, tools_lowercasestr_docstring},
    {"lowercasestr15", (PyCFunction)tools_lowercasestr15, METH_VARARGS, tools_lowercasestr15_docstring},
    {"uppercasestr", (PyCFunction)tools_uppercasestr, METH_VARARGS, tools_uppercasestr_docstring},
    {"isstrlowercase", (PyCFunction)tools_isstrlowercase, METH_VARARGS, tools_isstrlowercase_docstring},
    {"isstruppercase", (PyCFunction)tools_isstruppercase, METH_VARARGS, tools_isstruppercase_docstring},
    {"isstralnum", (PyCFunction)tools_isstralnum, METH_VARARGS, tools_isstralnum_docstring},
    {"isstralpha", (PyCFunction)tools_isstralpha, METH_VARARGS, tools_isstralpha_docstring},
    {"isstrnum", (PyCFunction)tools_isstrnum, METH_VARARGS, tools_isstrnum_docstring},
    {"isstrgraphical", (PyCFunction)tools_isstrgraphical, METH_VARARGS, tools_isstrgraphical_docstring},
    {"isstrprintable", (PyCFunction)tools_isstrprintable, METH_VARARGS, tools_isstrprintable_docstring},
    {"isstrpunctuation", (PyCFunction)tools_isstrpunctuation, METH_VARARGS, tools_isstrpunctuation_docstring},
    {"isstrwhitespace", (PyCFunction)tools_isstrwhitespace, METH_VARARGS, tools_isstrwhitespace_docstring},
    {"isstrhex", (PyCFunction)tools_isstrhex, METH_VARARGS, tools_isstrhex_docstring},
    {"strreplace", (PyCFunction)tools_strreplace, METH_VARARGS, tools_strreplace_docstring},
    {"strreplace_once", (PyCFunction)tools_strreplace_once, METH_VARARGS, tools_strreplace_once_docstring},
    {"rmgravequote", (PyCFunction)tools_rmgravequote, METH_VARARGS, tools_rmgravequote_docstring},
    {"nop", (PyCFunction)tools_nop, METH_NOARGS, tools_nop_docstring},
    {"endianness", (PyCFunction)tools_endianness, METH_NOARGS, tools_endianness_docstring},
    {"isandroid", (PyCFunction)tools_isandroid, METH_NOARGS, tools_isandroid_docstring},
    {"CSTD", (PyCFunction)tools_CSTD, METH_NOARGS, tools_CSTD_docstring},
    {"printline", (PyCFunction)tools_printline, METH_NOARGS, tools_printline_docstring},
    {NULL, NULL, 0, NULL}
}
Definition at line 460 of file pytools.c.