PyBooster: tone.h File Reference
tone.h File Reference
Play tones (header)
#include "MACROS.h"
#include <math.h>
#include <ao/ao.h>
Data Structures
struct tone
Macros
#define BUF_SIZE (4096)
Functions
ao_sample_format defaultsoundformat (void)
tone generatetone (const float freq, ao_sample_format format)
ao_device * initdriver (ao_sample_format format)
int playsound (void)
int playtone (const float freq)
ao_sample_format setsoundformat (const int bits, const int channels, const int rate)
tone tone1000hz (ao_sample_format format)
tone tone440hz (ao_sample_format format)
Detailed Description
Play tones (header)
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.20
DESCRIPTION
This library provides functions that produce tones using libao
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file tone.h.
Data Structure Documentation
struct tone
Definition at line 53 of file tone.h.
Data Fields
int buf_size
char buffer[BUF_SIZE]
int sample
Macro Definition Documentation
#define BUF_SIZE (4096)
Definition at line 51 of file tone.h.
Function Documentation
ao_sample_format defaultsoundformat (void)
Setup the default sound format
Definition at line 40 of file tone.c.
Referenced by playtone().
tone generatetone (const float freq, ao_sample_format format)
Generate a tone lasting one second; remember to use `free(sound.buffer);`
Definition at line 78 of file tone.c.
References tone::buf_size, tone::buffer, and tone::sample.
Referenced by playtone().
ao_device* initdriver (ao_sample_format format)
Setup and open default driver
Definition at line 67 of file tone.c.
Referenced by playtone().
int playsound (void)
Play a sound (440Hz tone for one second); return `1` if unable to open device
Definition at line 129 of file tone.c.
References tone::buf_size, tone::buffer, and tone440hz().
int playtone (const float freq)
Play a tone at the specified frequency; return `1` if unable to open device
Definition at line 150 of file tone.c.
References tone::buf_size, tone::buffer, defaultsoundformat(), generatetone(), and initdriver().
ao_sample_format setsoundformat (const int bits, const int channels, const int rate)
Setup sound format (bits, channels, rate)
Definition at line 52 of file tone.c.
tone tone1000hz (ao_sample_format format)
Generate a 1000Hz tone lasting one second; remember to use `free(sound.buffer);`
Definition at line 110 of file tone.c.
References tone::buf_size, tone::buffer, and tone::sample.
tone tone440hz (ao_sample_format format)
Generate a 440Hz tone lasting one second; remember to use `free(sound.buffer);`
Definition at line 94 of file tone.c.
References tone::buf_size, tone::buffer, and tone::sample.
Referenced by playsound().