PyBooster: tools.c File Reference
tools.c File Reference
Miscellaneous Functions.
#include "tools.h"
Functions
void appendfile (const char *__restrict__ filename, uint8_t *data, const size_t datasize)
void appendfilebuf (const char *__restrict__ filename, char *data, const size_t datasize)
size_t bytelen_utf32 (const uint32_t *__restrict__ utf32str)
int char_in_str (const char *__restrict__ str, const char _char)
long CSTD (void)
const char * endianness (void)
uint16_t fileadler16 (const char *__restrict__ filename)
uint32_t fileadler32 (const char *__restrict__ filename)
uint64_t fileadler64 (const char *__restrict__ filename)
uint64_t fileantiadler64 (const char *__restrict__ filename)
uint64_t fileantiadler64rev2 (const char *__restrict__ filename)
uint8_t filebitparity64 (const char *__restrict__ filename)
uint32_t filecollier32 (const char *__restrict__ filename)
int fileexists (const char *__restrict__ filename)
uint16_t filefletcher16 (const char *__restrict__ filename)
uint16_t filefletcher16fast (const char *__restrict__ filename)
uint32_t filefletcher32 (const char *__restrict__ filename)
uint32_t filefletcher32fast (const char *__restrict__ filename)
uint64_t filesize64 (const char *__restrict__ filename)
int filewritable (const char *__restrict__ filename)
uint8_t * get_hidden_data_from_file (const char *__restrict__ filename)
size_t get_size_of_hidden_data (const char *__restrict__ filename)
uint8_t * getbinfile (const char *__restrict__ filename)
uint8_t * getbinfile_sizet (const char *__restrict__ filename, const size_t filesize)
const char * getcompilername (void)
char * getfile (const char *__restrict__ filename)
char * getfile_sizet (const char *__restrict__ filename, const size_t filesize)
ulint getfilesize (const char *__restrict__ filename)
size_t getfilesize_t (const char *__restrict__ filename)
void hide_data_in_file (const char *__restrict__ filename, const uint8_t *__restrict__ data, const size_t datasize)
void inplace_strsub (char *orig_string, const char *__restrict__ find, const char *__restrict__ sub_with)
int isaix (void)
int isalnumx (const int x)
int isalphax (const int x)
int isandroid (void)
int isasciix (const int x)
int isblankx (const int x)
int iscntrl_ascii (const int x)
int iscntrlx (const int x) __attribute__((alias("iscntrl_ascii")))
int isdigit_ascii (const int x)
int isdigitx (const int x) __attribute__((alias("isdigit_ascii")))
int iseven (const int num)
int isgraph_ascii (const int x)
int isgraphx (const int x) __attribute__((alias("isgraph_ascii")))
int islibelf (void)
int islongeven (const long num)
int islongodd (const long num)
int islower_ascii (const int x)
int islowerx (const int x) __attribute__((alias("islower_ascii")))
int isodd (const int num)
int isprintx (const int x)
int isptr64bit (void)
int ispunct_ascii (const int x)
int ispunctx (const int x) __attribute__((alias("ispunct_ascii")))
int isspace_ascii (const int x)
int isspacex (const int x) __attribute__((alias("isspace_ascii")))
int isstralnum (const char *__restrict__ str)
int isstralpha (const char *__restrict__ str)
int isstrgraphical (const char *__restrict__ str)
int isstrhex (const char *__restrict__ str)
int isstrlowercase (const char *__restrict__ str)
int isstrnum (const char *__restrict__ str)
int isstrprintable (const char *__restrict__ str)
int isstrpunctuation (const char *__restrict__ str)
int isstruppercase (const char *__restrict__ str)
int isstrwhitespace (const char *__restrict__ str)
int isuint64even (const uint64_t num)
int isuint64odd (const uint64_t num)
int isupper_ascii (const int x)
int isupperx (const int x) __attribute__((alias("isupper_ascii")))
int isxdigit_ascii (const int x)
int isxdigitx (const int x) __attribute__((alias("isxdigit_ascii")))
void lowercasestr (char *__restrict__ str)
void lowercasestrx (char *__restrict__ str, const size_t len)
void printline (void)
char * rmgravequote (char *orig_string)
int space_in_str (const char *__restrict__ str)
char * STPCPY (char *__restrict__ dst, const char *__restrict__ src)
char * STPCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t srclen)
char * STPNCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
int str_in_str (const char *__restrict__ str, const char *__restrict__ substr)
char * STRCAT (char *__restrict__ dst, const char *__restrict__ src)
char * STRCATX (char *__restrict__ dst, const char *__restrict__ src, const size_t dstlen, const size_t srclen)
char * STRCPY (char *__restrict__ dst, const char *__restrict__ src)
char * STRCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t srclen)
char * strdupx (const char *__restrict__ s)
size_t STRLCAT (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
size_t STRLCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
size_t strlen_utf32 (const uint32_t *__restrict__ utf32str)
size_t strlenx (const char *__restrict__ str)
size_t strlenx_uint8 (const uint8_t *__restrict__ str)
char * STRNCAT (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
char * STRNCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
char * STRNCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen, const size_t srclen)
char * strreplace (char *orig_string, const char *find, const char *replace_with)
char * strreplace_once (char *orig_string, const char *find, const char *replace_with)
void strrmquotes (char *line)
int tolowerx (const int x)
int toupperx (const int x)
void uppercasestr (char *__restrict__ str)
void uppercasestrx (char *__restrict__ str, const size_t len)
void writefile (const char *__restrict__ filename, uint8_t *data, const size_t filesize)
void writefilebuf (const char *__restrict__ filename, char *data, const size_t filesize)
void xorswap (int *__restrict__ x, int *__restrict__ y)
void xorswap_sll (sllint *__restrict__ x, sllint *__restrict__ y)
Detailed Description
Miscellaneous Functions.
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.20
DESCRIPTION
Various functions that do not fit in other categories. Such functions include string manipulations, file I/O, boolean tests, etc.
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file tools.c.
Function Documentation
void appendfile (const char *__restrict__ filename, uint8_t * data, const size_t datasize)
Append data to a file; unbuffered
Definition at line 497 of file tools.c.
References FAILED_OPEN_FILE, and UNABLE_TO_WRITE_FILE.
void appendfilebuf (const char *__restrict__ filename, char * data, const size_t datasize)
Append data to a file; buffered
Definition at line 510 of file tools.c.
References ALLOC_WRITE_ERROR, FAILED_OPEN_FILE, and UNABLE_TO_WRITE_FILE.
size_t bytelen_utf32 (const uint32_t *__restrict__ utf32str)
Return the number of bytes in a UTF32 string (not counting the NULL terminator)
Definition at line 163 of file tools.c.
int char_in_str (const char *__restrict__ str, const char _char)
Test if the string contains the specified character
Definition at line 1175 of file tools.c.
long CSTD (void)
Return the value of the current C Standard
Definition at line 1678 of file tools.c.
References __STDC_VERSION__.
const char* endianness (void)
Return the system's endianness
Definition at line 1535 of file tools.c.
References UINT32_C.
Referenced by tools_endianness().
uint16_t fileadler16 (const char *__restrict__ filename)
Open the specified file and return the Adler16 checksum of the file
Definition at line 676 of file tools.c.
References getfilesize(), and slint.
uint32_t fileadler32 (const char *__restrict__ filename)
Open the specified file and return the Adler32 checksum of the file
Definition at line 716 of file tools.c.
References getfilesize(), and slint.
uint64_t fileadler64 (const char *__restrict__ filename)
Open the specified file and return the Adler64 checksum of the file
Definition at line 756 of file tools.c.
References getfilesize(), and slint.
uint64_t fileantiadler64 (const char *__restrict__ filename)
Open the specified file and return the Anti-Adler64 (decrementing for-loop) checksum of the file
Definition at line 796 of file tools.c.
References getfilesize(), and slint.
uint64_t fileantiadler64rev2 (const char *__restrict__ filename)
Open the specified file and return the Anti-Adler64rev2 (decrementing and re-arranged for-loop) checksum of the file
Definition at line 836 of file tools.c.
References getfilesize(), and slint.
uint8_t filebitparity64 (const char *__restrict__ filename)
Open the specified file and return the parity of the file
Definition at line 623 of file tools.c.
References getfilesize(), and slint.
uint32_t filecollier32 (const char *__restrict__ filename)
Open the specified file and return the Collier32 checksum of the file
Definition at line 1074 of file tools.c.
References getfilesize(), and slint.
int fileexists (const char *__restrict__ filename)
Test if the file exists
Definition at line 301 of file tools.c.
uint16_t filefletcher16 (const char *__restrict__ filename)
Open the specified file and return the Fletcher16 checksum of the file
Definition at line 876 of file tools.c.
References getfilesize(), and slint.
uint16_t filefletcher16fast (const char *__restrict__ filename)
Open the specified file and return the Fletcher16 checksum (optimized) of the file
Definition at line 916 of file tools.c.
References getfilesize(), and slint.
uint32_t filefletcher32 (const char *__restrict__ filename)
Open the specified file and return the Fletcher32 checksum of the file
Definition at line 973 of file tools.c.
References getfilesize(), and slint.
uint32_t filefletcher32fast (const char *__restrict__ filename)
Open the specified file and return the Fletcher32 checksum (optimized) of the file
Definition at line 1020 of file tools.c.
References getfilesize(), and slint.
uint64_t filesize64 (const char *__restrict__ filename)
Return the size of a file (in bytes); supports larger files
Definition at line 374 of file tools.c.
References FAILED_OPEN_FILE, slint, and UNABLE_TO_READ_FILE.
int filewritable (const char *__restrict__ filename)
Test if the file is writable
Definition at line 313 of file tools.c.
uint8_t* get_hidden_data_from_file (const char *__restrict__ filename)
Get the hidden data stored in the file as a uint8_t-array; remember to use `free()`
Definition at line 586 of file tools.c.
References getfilesize_t().
size_t get_size_of_hidden_data (const char *__restrict__ filename)
Return the size of the data hidden in the file
Definition at line 560 of file tools.c.
References getfilesize_t().
uint8_t* getbinfile (const char *__restrict__ filename)
Return the binary file's contents as an array of uint8_t; remember to use `free()`
Definition at line 426 of file tools.c.
References ALLOC_ERROR, FAILED_OPEN_FILE, getfilesize(), slint, and UNABLE_TO_READ_FILE.
uint8_t* getbinfile_sizet (const char *__restrict__ filename, const size_t filesize)
Given the filesize, return the binary file's contents as an array of uint8_t; remember to use `free()`
Definition at line 450 of file tools.c.
References ALLOC_ERROR, FAILED_OPEN_FILE, and UNABLE_TO_READ_FILE.
const char* getcompilername (void)
Get the name of the compiler that compiled this library
Definition at line 1632 of file tools.c.
char* getfile (const char *__restrict__ filename)
Return the file's contents as a char-array; remember to use `free()`
Definition at line 385 of file tools.c.
References ALLOC_ERROR, FAILED_OPEN_FILE, getfilesize(), slint, and UNABLE_TO_READ_FILE.
char* getfile_sizet (const char *__restrict__ filename, const size_t filesize)
Given the filesize, return the file's contents as a char-array; remember to use `free()`
Definition at line 409 of file tools.c.
References ALLOC_ERROR, FAILED_OPEN_FILE, and UNABLE_TO_READ_FILE.
ulint getfilesize (const char *__restrict__ filename)
Return the size of a file (in bytes)
Definition at line 351 of file tools.c.
References EXIT_ON_ERROR, FAILED_OPEN_FILE, slint, and ulint.
Referenced by fileadler16(), fileadler32(), fileadler64(), fileantiadler64(), fileantiadler64rev2(), filebitparity64(), filecollier32(), filefletcher16(), filefletcher16fast(), filefletcher32(), filefletcher32fast(), getbinfile(), and getfile().
size_t getfilesize_t (const char *__restrict__ filename)
Return the size of a file (in size_t)
Definition at line 362 of file tools.c.
References EXIT_ON_ERROR, FAILED_OPEN_FILE, and slint.
Referenced by get_hidden_data_from_file(), get_size_of_hidden_data(), and hide_data_in_file().
void hide_data_in_file (const char *__restrict__ filename, const uint8_t *__restrict__ data, const size_t datasize)
Hide data by appending the data to an existing file and include the metadata
This IO-stream is buffered
Parameters
[in] filename The name of an existing file
[in] data The data to hide
[in] datasize The size of data in bytes
Definition at line 533 of file tools.c.
References getfilesize_t().
void inplace_strsub (char * orig_string, const char *__restrict__ find, const char *__restrict__ sub_with)
Find and substitute all occurrences of "find" with "sub_with", inplace
Definition at line 1331 of file tools.c.
References strlenx().
int isaix (void)
Test if this system is AIX
Definition at line 1592 of file tools.c.
int isalnumx (const int x)
Test if the char is an alphanum
Definition at line 55 of file tools.c.
Referenced by isstralnum().
int isalphax (const int x)
Test if the char is a letter
Definition at line 61 of file tools.c.
Referenced by isstralpha().
int isandroid (void)
Test if this system is Android
Definition at line 1582 of file tools.c.
int isasciix (const int x)
Test if the char is ascii
Definition at line 67 of file tools.c.
int isblankx (const int x)
Test if the char is a space or tab
Definition at line 73 of file tools.c.
int iscntrl_ascii (const int x)
Test if the char is an control character
Definition at line 79 of file tools.c.
int iscntrlx (const int x)
int isdigit_ascii (const int x)
Test if the char is a number
Definition at line 86 of file tools.c.
Referenced by isstrnum().
int isdigitx (const int x)
int iseven (const int num)
Test if the integer is even
Definition at line 1298 of file tools.c.
int isgraph_ascii (const int x)
Test if the char is a graph
Definition at line 93 of file tools.c.
Referenced by isstrgraphical().
int isgraphx (const int x)
int islibelf (void)
Test if this library is an ELF file
Definition at line 1708 of file tools.c.
int islongeven (const long num)
Test if the long integer is even
Definition at line 1310 of file tools.c.
int islongodd (const long num)
Test if the long integer is odd
Definition at line 1304 of file tools.c.
int islower_ascii (const int x)
Test if the char is lowercase
Definition at line 41 of file tools.c.
int islowerx (const int x)
int isodd (const int num)
Test if the integer is odd
Definition at line 1292 of file tools.c.
int isprintx (const int x)
Test if the char is an printable character
Definition at line 100 of file tools.c.
Referenced by isstrprintable().
int isptr64bit (void)
Test if this system uses 64-bit pointers
Definition at line 1602 of file tools.c.
int ispunct_ascii (const int x)
Test if the char is punctuation
Definition at line 106 of file tools.c.
Referenced by isstrpunctuation().
int ispunctx (const int x)
int isspace_ascii (const int x)
Test if the char is a space
Definition at line 113 of file tools.c.
Referenced by isstrwhitespace().
int isspacex (const int x)
int isstralnum (const char *__restrict__ str)
Check if the string only contains alphanumeric characters
Definition at line 1228 of file tools.c.
References isalnumx(), and strlenx().
int isstralpha (const char *__restrict__ str)
Check if the string only contains alphabetic characters
Definition at line 1236 of file tools.c.
References isalphax(), and strlenx().
int isstrgraphical (const char *__restrict__ str)
Check if the string only contains printable characters and not whitespace
Definition at line 1252 of file tools.c.
References isgraph_ascii(), and strlenx().
int isstrhex (const char *__restrict__ str)
Check if the string only contains hexadecimal characters
Definition at line 1284 of file tools.c.
References isxdigit_ascii(), and strlenx().
int isstrlowercase (const char *__restrict__ str)
Check if the string only contains lowercase letters
Definition at line 1196 of file tools.c.
References ISLOWERASCII, and strlenx().
int isstrnum (const char *__restrict__ str)
Check if the string only contains numbers
Definition at line 1244 of file tools.c.
References isdigit_ascii(), and strlenx().
int isstrprintable (const char *__restrict__ str)
Check if the string only contains printable characters
Definition at line 1260 of file tools.c.
References isprintx(), and strlenx().
int isstrpunctuation (const char *__restrict__ str)
Check if the string only contains punctuation characters
Definition at line 1268 of file tools.c.
References ispunct_ascii(), and strlenx().
int isstruppercase (const char *__restrict__ str)
Check if the string only contains uppercase letters
Definition at line 1212 of file tools.c.
References ISUPPERASCII, and strlenx().
int isstrwhitespace (const char *__restrict__ str)
Check if the string only contains whitespace characters
Definition at line 1276 of file tools.c.
References isspace_ascii(), and strlenx().
int isuint64even (const uint64_t num)
Test if the uint64_t is even
Definition at line 1322 of file tools.c.
int isuint64odd (const uint64_t num)
Test if the uint64_t is odd
Definition at line 1316 of file tools.c.
int isupper_ascii (const int x)
Test if the char is uppercase
Definition at line 48 of file tools.c.
int isupperx (const int x)
int isxdigit_ascii (const int x)
Test if the char is a hexadecimal character
Definition at line 120 of file tools.c.
Referenced by isstrhex().
int isxdigitx (const int x)
void lowercasestr (char *__restrict__ str)
Convert a string (in-place) to all lowercase letters
Definition at line 1124 of file tools.c.
References strlenx().
void lowercasestrx (char *__restrict__ str, const size_t len)
Convert a string (in-place) to all lowercase letters, given the string length
Definition at line 1148 of file tools.c.
void printline (void)
Print a newline character
Definition at line 1721 of file tools.c.
char* rmgravequote (char * orig_string)
Find and remove grave-quotes (`)
Definition at line 1381 of file tools.c.
References strlenx().
Referenced by tools_rmgravequote().
int space_in_str (const char *__restrict__ str)
Test if the string contains a space
Definition at line 1189 of file tools.c.
char* STPCPY (char *__restrict__ dst, const char *__restrict__ src)
Like strcpy, but returns a pointer to the NULL terminator
Definition at line 179 of file tools.c.
References strlenx().
char* STPCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t srclen)
Like strcpy, but returns a pointer to the NULL terminator (re-implemented)
Definition at line 187 of file tools.c.
char* STPNCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
Like strncpy, but returns a pointer to the NULL terminator
Definition at line 194 of file tools.c.
References strlenx().
int str_in_str (const char *__restrict__ str, const char *__restrict__ substr)
Test if the string contains the specified substring
Definition at line 1182 of file tools.c.
char* STRCAT (char *__restrict__ dst, const char *__restrict__ src)
strcat (re-implemented)
Definition at line 208 of file tools.c.
References strlenx().
char* STRCATX (char *__restrict__ dst, const char *__restrict__ src, const size_t dstlen, const size_t srclen)
strcat (re-implemented): Specify source and destination length
Definition at line 215 of file tools.c.
char* STRCPY (char *__restrict__ dst, const char *__restrict__ src)
strcpy (re-implemented)
Definition at line 259 of file tools.c.
References strlenx().
char* STRCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t srclen)
strcpy (re-implemented): Specify length of source
Definition at line 266 of file tools.c.
char* strdupx (const char *__restrict__ s)
Duplicate string; remember to use `free()`
Definition at line 171 of file tools.c.
References strlenx().
size_t STRLCAT (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
Like strcat, but does not guarantee a NULL terminator
Definition at line 222 of file tools.c.
References strlenx().
size_t STRLCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
Like strcpy, but does not guarantee a NULL terminator
Definition at line 236 of file tools.c.
References strlenx().
size_t strlen_utf32 (const uint32_t *__restrict__ utf32str)
Return the number of UTF32 characters in a UTF32 string (not counting the NULL terminator)
Definition at line 155 of file tools.c.
size_t strlenx (const char *__restrict__ str)
Return the length of a string (not counting the NULL terminator)
Definition at line 139 of file tools.c.
Referenced by inplace_strsub(), isstralnum(), isstralpha(), isstrgraphical(), isstrhex(), isstrlowercase(), isstrnum(), isstrprintable(), isstrpunctuation(), isstruppercase(), isstrwhitespace(), lowercasestr(), rmgravequote(), STPCPY(), STPNCPY(), STRCAT(), STRCPY(), strdupx(), STRLCAT(), STRLCPY(), STRNCAT(), STRNCPY(), strreplace(), strreplace_once(), strrmquotes(), and uppercasestr().
size_t strlenx_uint8 (const uint8_t *__restrict__ str)
Return the length of a `uint8_t` string (not counting the NULL terminator)
Definition at line 147 of file tools.c.
char* STRNCAT (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
strncat (re-implemented)
Definition at line 249 of file tools.c.
References strlenx().
char* STRNCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
strncpy (re-implemented)
Definition at line 273 of file tools.c.
References strlenx().
char* STRNCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen, const size_t srclen)
strncpy (re-implemented): Specify length of source
Definition at line 286 of file tools.c.
char* strreplace (char * orig_string, const char * find, const char * replace_with)
Find and replace all occurrences of "find" with "replace_with"
Definition at line 1342 of file tools.c.
References strlenx(), and ulint.
char* strreplace_once (char * orig_string, const char * find, const char * replace_with)
Replace first occurrence of "find" with "replace_with"
Definition at line 1366 of file tools.c.
References strlenx().
Referenced by tools_strreplace_once().
void strrmquotes (char * line)
Remove quotes from a string inplace
Definition at line 1398 of file tools.c.
References strlenx().
int tolowerx (const int x)
Return the lowercase form of a character
Definition at line 127 of file tools.c.
int toupperx (const int x)
Return the uppercase form of a character
Definition at line 133 of file tools.c.
void uppercasestr (char *__restrict__ str)
Convert a string (in-place) to all uppercase letters
Definition at line 1136 of file tools.c.
References strlenx().
void uppercasestrx (char *__restrict__ str, const size_t len)
Convert a string (in-place) to all uppercase letters, given the string length
Definition at line 1160 of file tools.c.
void writefile (const char *__restrict__ filename, uint8_t * data, const size_t filesize)
Write data to a file; unbuffered
Definition at line 467 of file tools.c.
References FAILED_OPEN_FILE, and UNABLE_TO_WRITE_FILE.
void writefilebuf (const char *__restrict__ filename, char * data, const size_t filesize)
Write data to a file; buffered
Definition at line 480 of file tools.c.
References ALLOC_WRITE_ERROR, FAILED_OPEN_FILE, and UNABLE_TO_WRITE_FILE.
void xorswap (int *__restrict__ x, int *__restrict__ y)
Swap the values of `x` and `y` (xorswap(&x, &y))
Definition at line 1729 of file tools.c.
void xorswap_sll (sllint *__restrict__ x, sllint *__restrict__ y)
Swap the values of `x` and `y` (xorswap_sll(&x, &y))
Definition at line 1737 of file tools.c.